import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { ResearchApplication } from "../public/application.js";
import { PUBLIC_SCHEMA_VERSION, type PluginPermission } from "../public/contracts.js";
import { CORE_SERVICE_VERSION, ServiceCapabilitiesSchema, type CoreServiceAddress, type CoreServiceHandle, type CoreServiceOptions } from "../public/service.js";
import { ServiceAuditStore } from "../infrastructure/db/service-audit-store.js";
import { detectPlatformCapabilities } from "../runtime/platform-capabilities.js";

const DEFAULT_PERMISSIONS:PluginPermission[]=["filesystem.read","filesystem.write","process","confirmation"];
const ENDPOINTS=["/v1/health","/v1/capabilities","/v1/commands","/v1/queries","/v1/workers","/v1/stream","/v1/audit"];
interface PermissionDecision{required:PluginPermission[];externalServices:string[]}

export async function startCoreServiceImpl(options:CoreServiceOptions):Promise<CoreServiceHandle>{
  const host=options.host??"127.0.0.1",loopback=isLoopback(host);if(!loopback&&!options.allowRemote)throw new Error("Non-loopback Core Service binding requires allowRemote=true");const dataDir=resolve(options.dataDir),databasePath=resolve(options.databasePath);mkdirSync(dataDir,{recursive:true});mkdirSync(dirname(databasePath),{recursive:true});
  const application=await ResearchApplication.open({databasePath,artifactRoot:options.artifactRoot??join(dataDir,"artifacts"),artifactRoots:options.artifactRoots});let audit:ServiceAuditStore|undefined;try{audit=await ServiceAuditStore.open(databasePath);}catch(error){application.close();throw error;}
  const tokenName=options.tokenSecretName??"AUTO_RESEARCH_SERVICE_TOKEN",defaultTokenFile=join(dataDir,"core-service.token");let token:string,tokenFile:string|null=null,providerName:string;
  if(options.secretProvider){let resolved;try{resolved=await options.secretProvider.resolve(tokenName,"core-service-auth");}catch(error){audit.close();application.close();throw error;}audit.secret({name:tokenName,provider:resolved?.provider??"configured",found:!!resolved,purpose:"core-service-auth"});if(!resolved){audit.close();application.close();throw new Error(`Secret provider did not resolve ${tokenName}`);}token=resolved.value;providerName=resolved.provider;}
  else{if(existsSync(defaultTokenFile))token=readFileSync(defaultTokenFile,"utf8").trim();else{token=randomBytes(32).toString("hex");writeFileSync(defaultTokenFile,`${token}\n`,{mode:0o600,flag:"wx"});}chmodSync(defaultTokenFile,0o600);tokenFile=defaultTokenFile;providerName="local-file";audit.secret({name:tokenName,provider:providerName,found:true,purpose:"core-service-auth"});}
  if(token.length<32){audit.close();application.close();throw new Error("Core Service auth token must contain at least 32 characters");}
  const allowedPermissions=[...new Set(options.allowedPermissions??DEFAULT_PERMISSIONS)],startedAt=new Date().toISOString(),platform=detectPlatformCapabilities({now:startedAt}),streams=new Set<ServerResponse>(),allowedOrigins=new Set(options.allowedOrigins??[]);
  const server=createServer(async(req,res)=>{try{await handle(req,res);}catch(error){if(!res.headersSent)sendJson(res,500,{error:{code:"INTERNAL",message:"Internal Core Service error"}});else res.end();}});
  const handle=async(req:IncomingMessage,res:ServerResponse):Promise<void>=>{
    const started=new Date().toISOString(),requestId=header(req,"x-request-id")??`service-request-${randomUUID()}`,url=new URL(req.url??"/","http://localhost"),endpoint=url.pathname,remoteAddress=req.socket.remoteAddress??null;let raw:unknown=null,decision:PermissionDecision={required:[],externalServices:[]},scope={workspaceId:null as string|null,projectId:null as string|null,actorId:null as string|null};
    const finish=(status:"accepted"|"rejected"|"error",errorCode:string|null)=>audit!.record({requestId,method:req.method??"GET",endpoint,workspaceId:scope.workspaceId,projectId:scope.projectId,actorId:scope.actorId,status,requiredPermissions:decision.required,externalServices:decision.externalServices,payloadHash:hashSanitized(raw),errorCode,remoteAddress,startedAt:started,finishedAt:new Date().toISOString()});
    if(!loopback&&!options.allowRemote){sendJson(res,403,{error:{code:"FORBIDDEN",message:"Remote service access is disabled"}});finish("rejected","FORBIDDEN");return;}
    const origin=header(req,"origin");if(origin&&!allowedOrigins.has(origin)){sendJson(res,403,{error:{code:"FORBIDDEN",message:"Origin is not allowed"}});finish("rejected","FORBIDDEN");return;}
    if(!authenticate(req,token)){sendJson(res,401,{error:{code:"FORBIDDEN",message:"Authentication required"}});finish("rejected","FORBIDDEN");return;}
    if(req.method==="GET"&&endpoint==="/v1/health"){sendJson(res,200,{status:"ok",serviceVersion:CORE_SERVICE_VERSION,schemaVersion:PUBLIC_SCHEMA_VERSION,offline:!allowedPermissions.includes("network")});finish("accepted",null);return;}
    if(req.method==="GET"&&endpoint==="/v1/capabilities"){sendJson(res,200,capabilities());finish("accepted",null);return;}
    if(req.method==="GET"&&endpoint==="/v1/audit"){const workspaceId=url.searchParams.get("workspaceId"),projectId=url.searchParams.get("projectId"),limit=Number(url.searchParams.get("limit")??200);scope={workspaceId,projectId,actorId:null};sendJson(res,200,{records:audit!.list({workspaceId,projectId,limit})});finish("accepted",null);return;}
    if(req.method==="GET"&&endpoint==="/v1/stream"){const workspaceId=url.searchParams.get("workspaceId"),projectId=url.searchParams.get("projectId"),actorId=url.searchParams.get("actorId")??"user:sdk";scope={workspaceId,projectId,actorId};if(!workspaceId||!projectId){sendJson(res,400,{error:{code:"INVALID_COMMAND",message:"workspaceId and projectId are required"}});finish("rejected","INVALID_COMMAND");return;}finish("accepted",null);await stream(req,res,url,workspaceId,projectId,actorId);return;}
    if(req.method!=="POST"||!["/v1/commands","/v1/queries","/v1/workers"].includes(endpoint)){sendJson(res,404,{error:{code:"NOT_FOUND",message:"Unknown Core Service endpoint"}});finish("rejected","NOT_FOUND");return;}
    try{raw=await readJson(req,options.maxBodyBytes??1_000_000);}catch(error){sendJson(res,400,{error:{code:"INVALID_COMMAND",message:error instanceof Error?error.message:"Invalid JSON body"}});finish("rejected","INVALID_COMMAND");return;}
    const object=raw&&typeof raw==="object"?raw as Record<string,any>:{};scope={workspaceId:typeof object.workspaceId==="string"?object.workspaceId:null,projectId:typeof object.projectId==="string"?object.projectId:null,actorId:typeof object.actor?.id==="string"?object.actor.id:null};decision=await requiredPermissions(endpoint,object,application);const denied=decision.required.filter(item=>!allowedPermissions.includes(item));if(denied.length){sendJson(res,403,{error:{code:"FORBIDDEN",message:`Service policy denies permissions: ${denied.join(", ")}`,details:{required:decision.required,allowed:allowedPermissions}}});finish("rejected","FORBIDDEN");return;}
    const result=endpoint==="/v1/commands"?await application.execute(raw,{permissions:decision.required,externalServices:decision.externalServices}):endpoint==="/v1/queries"?await application.query(raw):await application.worker(raw);sendJson(res,200,result);const rejected=(result as{status?:string;error?:{code?:string}|null}).status==="rejected";finish(rejected?"rejected":"accepted",rejected?(result as any).error?.code??"INTERNAL":null);
  };
  const capabilities=()=>ServiceCapabilitiesSchema.parse({serviceVersion:CORE_SERVICE_VERSION,schemaVersion:PUBLIC_SCHEMA_VERSION,transports:{rest:true,sse:true,websocket:false},endpoints:ENDPOINTS,allowedPermissions,offline:!allowedPermissions.includes("network"),telemetry:false,publicExports:[".","./application","./client","./contracts","./kernel","./scenario","./server"],platform,startedAt});
  const stream=async(req:IncomingMessage,res:ServerResponse,url:URL,workspaceId:string,projectId:string,actorId:string)=>{res.writeHead(200,{"content-type":"text/event-stream; charset=utf-8","cache-control":"no-cache, no-transform","connection":"keep-alive","x-accel-buffering":"no"});streams.add(res);res.write(": connected\n\n");let closed=false,eventSequence=Math.max(1,Number(url.searchParams.get("fromSequence")??1)),logSequence=Math.max(1,Number(url.searchParams.get("logFrom")??1)),heartbeat=0;const jobId=url.searchParams.get("jobId");req.on("close",()=>{closed=true;streams.delete(res);});while(!closed){const events=await application.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`stream-events-${randomUUID()}`,type:"project.events",workspaceId,projectId,actor:{id:actorId,kind:"user"},fromSequence:eventSequence,limit:200});if(events.status==="rejected"){writeSse(res,"error",events.error,null);break;}for(const event of (events.data as any).events){writeSse(res,"research-event",event,String(event.sequence));eventSequence=event.sequence+1;}if(jobId){const logs=await application.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`stream-logs-${randomUUID()}`,type:"job.logs",workspaceId,projectId,actor:{id:actorId,kind:"user"},jobId,fromSequence:logSequence,limit:200});if(logs.status==="rejected"){writeSse(res,"error",logs.error,null);break;}for(const log of (logs.data as any).logs){writeSse(res,"job-log",log,`job:${log.sequence}`);logSequence=log.sequence+1;}}if(++heartbeat%50===0)res.write(": heartbeat\n\n");await delay(options.streamPollMs??100);}streams.delete(res);if(!res.writableEnded)res.end();};
  try{await new Promise<void>((resolveListen,reject)=>{server.once("error",reject);server.listen(options.port??0,host,()=>{server.off("error",reject);resolveListen();});});}catch(error){audit.close();application.close();throw error;}const address=server.address();if(!address||typeof address==="string"){server.close();audit.close();application.close();throw new Error("Core Service failed to bind a TCP port");}const baseUrl=`http://${formatHost(host)}:${address.port}`,discoveryFile=join(dataDir,"core-service.json"),serviceAddress:CoreServiceAddress={baseUrl,host,port:address.port,discoveryFile,tokenFile,tokenSecretName:tokenName,capabilities:capabilities()},discovery={...serviceAddress,pid:process.pid,provider:providerName};try{writeAtomic(discoveryFile,JSON.stringify(discovery,null,2)+"\n");}catch(error){server.close();audit.close();application.close();throw error;}
  return{address:serviceAddress,close:async()=>{for(const response of streams)response.destroy();streams.clear();await new Promise<void>(resolveClose=>server.close(()=>resolveClose()));try{if(existsSync(discoveryFile)&&JSON.parse(readFileSync(discoveryFile,"utf8")).pid===process.pid)unlinkSync(discoveryFile);}catch{}audit!.close();application.close();}};
}

async function requiredPermissions(endpoint:string,body:Record<string,any>,application:ResearchApplication):Promise<PermissionDecision>{const required=new Set<PluginPermission>(),externalServices:string[]=[];if(endpoint==="/v1/workers")return{required:[],externalServices:["worker-runtime"]};if(endpoint==="/v1/queries"&&body.type==="plugin.runtime"){const result=await application.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`permission-${randomUUID()}`,type:"plugin.installations",workspaceId:body.workspaceId,projectId:body.projectId,actor:body.actor});if(result.status==="ok")for(const item of (result.data as any).installations)if(item.status==="enabled")for(const permission of item.approvedPermissions)required.add(permission);}
  if(endpoint==="/v1/queries"&&body.type==="project.bundle")required.add("filesystem.read");
  if(endpoint==="/v1/commands"){
    if(body.type==="project.import")required.add("filesystem.write");
    if(body.type==="plugin.source.refresh"){required.add("filesystem.read");const sources=await application.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`permission-${randomUUID()}`,type:"plugin.sources",workspaceId:body.workspaceId,projectId:null,actor:body.actor});const source=(sources.data as any)?.sources?.find((item:any)=>item.id===body.payload?.sourceId);if(source&&needsNetwork(source.kind,source.location)){required.add("network");externalServices.push(`plugin-source:${safeServiceName(source.location)}`);}}
    if(["plugin.install","plugin.update"].includes(body.type)){required.add("filesystem.read");required.add("filesystem.write");}
    if(body.type==="plugin.enable")required.add("filesystem.read");
    if(body.type==="job.submit"){const spec=body.payload?.spec,kind=spec?.execution?.kind;required.add("process");if(kind!=="pi"){required.add("filesystem.read");required.add("filesystem.write");}if(kind==="python"){required.add("network");externalServices.push("unrestricted-python-process");}if(kind==="pi"){required.add("network");required.add("model");externalServices.push("model-provider");}if((spec?.resources?.gpuCount??0)>0)required.add("gpu");if(spec?.dataRole==="confirmation")required.add("confirmation");}
  }return{required:[...required],externalServices};}

function needsNetwork(kind:string,location:string):boolean{return(kind==="git"||kind==="npm")&&!isAbsolute(location)&&!location.startsWith("file://");}
function safeServiceName(location:string):string{try{return new URL(location.replace(/^git:/,"" )).host||"remote";}catch{return"remote";}}
function authenticate(req:IncomingMessage,token:string):boolean{const value=header(req,"authorization");if(!value?.startsWith("Bearer "))return false;const supplied=Buffer.from(value.slice(7)),expected=Buffer.from(token);return supplied.length===expected.length&&timingSafeEqual(supplied,expected);}
function header(req:IncomingMessage,name:string):string|undefined{const value=req.headers[name];return Array.isArray(value)?value[0]:value;}
async function readJson(req:IncomingMessage,maxBytes:number):Promise<unknown>{const chunks:Buffer[]=[];let bytes=0;for await(const chunk of req){const buffer=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);bytes+=buffer.length;if(bytes>maxBytes)throw new Error("Request body exceeds the configured limit");chunks.push(buffer);}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new Error("Request body is not valid JSON");}}
function sendJson(res:ServerResponse,status:number,value:unknown):void{const body=JSON.stringify(value);res.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":Buffer.byteLength(body),"cache-control":"no-store"});res.end(body);}
function writeSse(res:ServerResponse,event:string,data:unknown,id:string|null):void{if(id)res.write(`id: ${id}\n`);res.write(`event: ${event}\n`);res.write(`data: ${JSON.stringify(data)}\n\n`);}
function hashSanitized(value:unknown):string{return createHash("sha256").update(JSON.stringify(sanitize(value))).digest("hex");}
function sanitize(value:unknown):unknown{if(Array.isArray(value))return value.map(sanitize);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,/(authorization|confirmation.?token|api.?key|secret|password|token)/i.test(key)?"[REDACTED]":sanitize(item)]));return value;}
function writeAtomic(path:string,content:string):void{const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,content,{mode:0o600});renameSync(temporary,path);chmodSync(path,0o600);}
function isLoopback(host:string):boolean{return["127.0.0.1","localhost","::1"].includes(host);}
function formatHost(host:string):string{return host.includes(":")?`[${host}]`:host;}
function delay(ms:number):Promise<void>{return new Promise(resolveDelay=>setTimeout(resolveDelay,ms));}
