import { createHash } from "node:crypto";
import { copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { basename, dirname, join, relative, resolve } from "node:path";
import { PluginDescriptorSchema, PluginPermissionSchema, hashJson, type PluginDescriptor, type PluginSource } from "../domain/plugin.js";

const CORE_SCHEMA_VERSION="1.0.0",PI_VERSION="0.85.1",IGNORED=new Set([".git","node_modules","dist","__pycache__"]);
interface PackageJson{name?:string;version?:string;description?:string;license?:string;author?:unknown;contributors?:unknown;maintainers?:unknown;dependencies?:Record<string,string>;peerDependencies?:Record<string,string>;keywords?:string[];pi?:Record<string,unknown>;autoResearch?:Record<string,unknown>}
export interface DiscoveryResult{descriptors:PluginDescriptor[];issues:string[]}

/** Static bridge: reads manifests and bytes only. It never imports modules or invokes Pi/npm/git. */
export class PiPluginBridge{
  constructor(private readonly metadataRoot=resolve(".research-data/plugin-source-cache")){mkdirSync(this.metadataRoot,{recursive:true});}
  discover(source:PluginSource):DiscoveryResult{
    try{const roots=this.packageRoots(source),descriptors:PluginDescriptor[]=[],issues:string[]=[];for(const root of roots)try{descriptors.push(this.inspectPackage(root,source));}catch(error){issues.push(`${root}: ${error instanceof Error?error.message:String(error)}`);}return{descriptors,issues};}
    catch(error){return{descriptors:[],issues:[error instanceof Error?error.message:String(error)]};}
  }

  inspectPackage(rootInput:string,source:PluginSource):PluginDescriptor{
    const root=resolve(rootInput),packagePath=join(root,"package.json");this.assertRegular(packagePath);const raw=JSON.parse(readFileSync(packagePath,"utf8")) as PackageJson,name=raw.name??basename(root),version=raw.version??"0.0.0";if(!/^\d+\.\d+\.\d+$/.test(version))throw new Error(`Package ${name} has a non-semver version`);
    const pi=(raw.pi??{}) as Record<string,unknown>,research=(raw.autoResearch??{}) as Record<string,unknown>,list=(value:unknown)=>Array.isArray(value)?value.filter(item=>typeof item==="string") as string[]:[],manifest=(key:string,folder:string)=>{const declared=list(pi[key]);if(declared.length)return declared;try{return readdirSync(join(root,folder),{withFileTypes:true}).filter(item=>!item.name.startsWith(".")).map(item=>`${folder}/${item.name}`).sort();}catch{return[];}};
    const extensions=manifest("extensions","extensions"),skills=manifest("skills","skills"),prompts=manifest("prompts","prompts"),themes=manifest("themes","themes"),tools=list(research.tools),apps=list(research.apps),mcp=list(research.mcp),scenarios=list(research.scenarios),providedPermissions=list(research.permissions),permissions=[...new Set([...providedPermissions,...(extensions.length?["host.full"]:[]),...(skills.length?["model"]:[])])];
    const parsedPermissions=permissions.map(item=>PluginPermissionSchema.parse(item)),coreSchemaRange=typeof research.coreSchemaRange==="string"?research.coreSchemaRange:"^1.0.0",piVersionRange=typeof research.piVersionRange==="string"?research.piVersionRange:"^0.85.0",compatibilityIssues:string[]=[];if(!satisfies(CORE_SCHEMA_VERSION,coreSchemaRange))compatibilityIssues.push(`Core schema ${CORE_SCHEMA_VERSION} does not satisfy ${coreSchemaRange}`);if(!satisfies(PI_VERSION,piVersionRange))compatibilityIssues.push(`Pi ${PI_VERSION} does not satisfy ${piVersionRange}`);
    const contentHash=this.contentHash(root),discoveredAt=new Date().toISOString(),descriptorId=`plugin-descriptor-${hashJson({sourceId:source.id,name,version,contentHash}).slice(0,32)}`;
    return PluginDescriptorSchema.parse({descriptorId,pluginId:name,name:typeof research.displayName==="string"?research.displayName:name,version,description:typeof research.description==="string"?research.description:raw.description??`Pi package ${name}`,domain:list(research.domain),license:raw.license??"UNKNOWN",maintainers:this.people(raw.maintainers??raw.contributors??raw.author),sourceId:source.id,sourceKind:source.kind,sourceLocation:root,contentHash,contributions:{extensions,skills,prompts,themes,tools,apps,mcp,scenarios},permissions:parsedPermissions,sideEffects:list(research.sideEffects),dependencies:[...new Set([...Object.keys(raw.dependencies??{}),...Object.keys(raw.peerDependencies??{})])].sort(),coreSchemaRange,piVersionRange,compatibilityStatus:compatibilityIssues.length?"incompatible":"compatible",compatibilityIssues,discoveredAt});
  }

  verify(descriptor:PluginDescriptor,source:PluginSource):boolean{try{const current=this.inspectPackage(descriptor.sourceLocation,source);return current.pluginId===descriptor.pluginId&&current.version===descriptor.version&&current.contentHash===descriptor.contentHash;}catch{return false;}}

  materialize(descriptor:PluginDescriptor,cacheRoot:string):string{
    const target=resolve(cacheRoot,descriptor.contentHash);this.walk(descriptor.sourceLocation);mkdirSync(target,{recursive:true});this.copyTree(descriptor.sourceLocation,target);return target;
  }

  private packageRoots(source:PluginSource):string[]{
    if(source.kind==="pi_config"){const settings=resolve(source.location);this.assertRegular(settings);const body=JSON.parse(readFileSync(settings,"utf8")) as{packages?:Array<string|{source?:string}>},base=dirname(settings),roots:string[]=[];for(const item of body.packages??[]){const value=typeof item==="string"?item:item.source;if(!value||value.startsWith("npm:")||value.startsWith("git:")||/^https?:|^ssh:/.test(value))continue;roots.push(resolve(base,value));}return roots;}
    const location=source.kind==="git"&&!existsSync(source.location)?this.prepareGitSnapshot(source):resolve(source.location);if(source.kind==="npm"&&source.location!==resolve(source.location))throw new Error("npm source requires an already installed absolute package path for static inspection");this.assertDirectory(location);try{this.assertRegular(join(location,"package.json"));return[location];}catch{return readdirSync(location,{withFileTypes:true}).filter(item=>item.isDirectory()&&!item.name.startsWith(".")).map(item=>join(location,item.name)).filter(path=>{try{this.assertRegular(join(path,"package.json"));return true;}catch{return false;}});}
  }
  private prepareGitSnapshot(source:PluginSource):string{let remote=source.location,ref="HEAD";const hashIndex=remote.lastIndexOf("#");if(hashIndex>remote.indexOf("://")+2){ref=remote.slice(hashIndex+1)||"HEAD";remote=remote.slice(0,hashIndex);}if(remote.startsWith("git:"))remote=remote.slice(4);if(!/^[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(ref))throw new Error("Git source ref contains unsafe characters");if(!/^(https?|ssh|git|file):\/\//.test(remote)&&!/^git@[^:]+:.+/.test(remote))throw new Error("Git source requires an explicit protocol URL or git@host:path");const mirror=join(this.metadataRoot,`${source.id}.git`),env={...process.env,GIT_TERMINAL_PROMPT:"0",GIT_CONFIG_NOSYSTEM:"1"};if(!existsSync(mirror))execFileSync("git",["clone","--bare","--filter=blob:none","--",remote,mirror],{env,stdio:"pipe",timeout:30000});execFileSync("git",["--git-dir",mirror,"fetch","--depth","1","--no-tags","origin",ref],{env,stdio:"pipe",timeout:30000});const revision=execFileSync("git",["--git-dir",mirror,"rev-parse","FETCH_HEAD"],{env,encoding:"utf8",timeout:5000}).trim(),snapshot=join(this.metadataRoot,"snapshots",source.id,revision);if(existsSync(join(snapshot,"package.json")))return snapshot;mkdirSync(snapshot,{recursive:true});const listing=execFileSync("git",["--git-dir",mirror,"ls-tree","-r","-z",revision],{env,encoding:"buffer",maxBuffer:10_000_000,timeout:10000}).toString().split("\0").filter(Boolean);if(listing.length>2000)throw new Error("Git plugin snapshot exceeds 2000 files");for(const entry of listing){const match=/^(\d+)\s+(\w+)\s+([a-f0-9]+)\t([^\n\r]+)$/.exec(entry);if(!match)throw new Error("Git plugin contains an unsupported tree entry");if(match[2]!=="blob")continue;if(match[1]==="120000")throw new Error(`Symlink is not allowed in plugin snapshot: ${match[4]}`);const rel=match[4]!;if(rel.startsWith("/")||rel.split("/").includes(".."))throw new Error(`Unsafe Git plugin path: ${rel}`);if(rel.split("/").some(part=>IGNORED.has(part)))continue;const content=execFileSync("git",["--git-dir",mirror,"show",`${revision}:${rel}`],{env,encoding:"buffer",maxBuffer:5_000_001,timeout:10000});if(content.length>5_000_000)throw new Error(`Plugin file exceeds 5 MB: ${rel}`);const target=join(snapshot,rel);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,content);}return snapshot;}
  private contentHash(root:string):string{const hash=createHash("sha256");for(const path of this.walk(root)){const rel=relative(root,path);hash.update(rel);hash.update("\0");hash.update(readFileSync(path));hash.update("\0");}return hash.digest("hex");}
  private walk(root:string):string[]{const files:string[]=[],visit=(dir:string)=>{for(const item of readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(IGNORED.has(item.name))continue;const path=join(dir,item.name),stat=lstatSync(path);if(stat.isSymbolicLink())throw new Error(`Symlink is not allowed in plugin snapshot: ${path}`);if(stat.isDirectory())visit(path);else if(stat.isFile()){if(stat.size>5_000_000)throw new Error(`Plugin file exceeds 5 MB: ${path}`);files.push(path);if(files.length>2000)throw new Error("Plugin snapshot exceeds 2000 files");}}};visit(resolve(root));return files;}
  private copyTree(source:string,target:string):void{for(const item of readdirSync(source,{withFileTypes:true})){if(IGNORED.has(item.name))continue;const from=join(source,item.name),to=join(target,item.name),stat=lstatSync(from);if(stat.isSymbolicLink())throw new Error(`Symlink is not allowed in plugin snapshot: ${from}`);if(stat.isDirectory()){mkdirSync(to,{recursive:true});this.copyTree(from,to);}else if(stat.isFile())copyFileSync(from,to);}}
  private people(value:unknown):string[]{const list=Array.isArray(value)?value:[value];return list.flatMap(item=>typeof item==="string"?[item]:item&&typeof item==="object"&&"name" in item&&typeof item.name==="string"?[item.name]:[]);}
  private assertRegular(path:string):void{if(!lstatSync(path).isFile())throw new Error(`Expected regular file ${path}`);}
  private assertDirectory(path:string):void{if(!lstatSync(path).isDirectory())throw new Error(`Expected directory ${path}`);}
}

function parse(value:string):[number,number,number]|null{const match=/^(\d+)\.(\d+)\.(\d+)$/.exec(value.trim());return match?[Number(match[1]),Number(match[2]),Number(match[3])]:null;}
function cmp(a:[number,number,number],b:[number,number,number]):number{for(let index=0;index<3;index++){const value=a[index]!-b[index]!;if(value)return value;}return 0;}
function satisfies(version:string,range:string):boolean{const value=parse(version);if(!value)return false;if(range.startsWith("^")){const base=parse(range.slice(1));return !!base&&cmp(value,base)>=0&&(base[0]>0?value[0]===base[0]:base[1]>0?value[0]===0&&value[1]===base[1]:cmp(value,base)===0);}const exact=parse(range);if(exact)return cmp(value,exact)===0;const low=/>=\s*(\d+\.\d+\.\d+)/.exec(range),high=/<\s*(\d+\.\d+\.\d+)/.exec(range),a=low?parse(low[1]!):null,b=high?parse(high[1]!):null;return !!(a&&b&&cmp(value,a)>=0&&cmp(value,b)<0);}
