import { spawnSync } from "node:child_process";
import { arch as hostArch,platform as hostPlatform } from "node:os";
import { delimiter } from "node:path";
import { createRequire } from "node:module";
import { PlatformCapabilitySnapshotSchema,type PlatformCapabilitySnapshot } from "../domain/job.js";

type ProbeResult={available:boolean;version:string|null};
export interface PlatformDetectionOptions{platform?:NodeJS.Platform|string;arch?:string;now?:string;probe?:(command:string,args:string[])=>ProbeResult}
export function detectPlatformCapabilities(options:PlatformDetectionOptions={}):PlatformCapabilitySnapshot{
  const rawOs=options.platform??hostPlatform(),os=rawOs==="linux"||rawOs==="darwin"||rawOs==="win32"?rawOs:"other",arch=options.arch??hostArch(),probe=options.probe??probeCommand,python=probe(os==="win32"?"python":"python3",["--version"]),bubblewrap=os==="linux"?probe("bwrap",["--version"]):{available:false,version:null},ssh=probe("ssh",["-V"]),sftp=probe("sftp",["-h"]),prlimit=os==="linux"?probe("prlimit",["--version"]):{available:false,version:null},pi=hasPiRuntime();
  const state=(available:boolean,reason:string|null)=>({status:available?"available" as const:"unavailable" as const,reason:available?null:reason});
  return PlatformCapabilitySnapshotSchema.parse({os,arch,nodeVersion:process.version,pythonVersion:python.version,executors:{python:state(python.available,`${os} Python executable was not found`),bubblewrap:state(bubblewrap.available,os==="linux"?"Bubblewrap executable was not found":"Bubblewrap is Linux-only"),pi:state(pi,"Optional Pi runtime is not installed")},sandbox:state(bubblewrap.available,bubblewrap.available?null:os==="linux"?"Bubblewrap executable was not found":"No supported local research sandbox on this platform"),resourceLimits:prlimit.available?state(true,null):{status:"degraded",reason:os==="linux"?"prlimit was not found":"Only wall time and process-tree termination are available"},processGroups:os==="win32"?{status:"degraded",reason:"Windows uses taskkill process-tree termination instead of POSIX process groups"}:state(true,null),storageModes:["local"],filesystem:{pathSeparator:os==="win32"?"\\":"/",caseSensitive:os==="linux"?true:null},ssh:{client:state(ssh.available,"OpenSSH client was not found"),version:ssh.version,sftp:state(sftp.available,"OpenSSH sftp client was not found"),proxyJump:ssh.available?state(true,null):state(false,"OpenSSH client was not found"),multiplexing:os==="win32"?{status:"unavailable",reason:"ControlMaster Unix sockets are not a Windows portability requirement"}:state(ssh.available,"OpenSSH client was not found")},detectedAt:options.now??new Date().toISOString()});
}
function hasPiRuntime():boolean{try{createRequire(import.meta.url).resolve("@earendil-works/pi-coding-agent");return true;}catch{return false;}}
function probeCommand(command:string,args:string[]):ProbeResult{const result=spawnSync(command,args,{encoding:"utf8",windowsHide:true,timeout:3000,env:{PATH:process.env.PATH?.split(delimiter).join(delimiter)}});if(result.error)return{available:false,version:null};const output=`${result.stdout??""}\n${result.stderr??""}`.trim().split(/\r?\n/)[0]??null;return{available:true,version:output||null};}
