import type { JobArtifact,JobFailureClass,JobLease,WorkerDescriptor } from "../domain/job.js";
import { JobStore } from "../infrastructure/db/job-store.js";
import { ContentAddressedStore } from "../infrastructure/artifacts/content-store.js";
import type { RemoteWorkerInstallation,SshHostProfile } from "../public/contracts.js";
import { SystemSshRemoteWorker,type RemoteDataAlias } from "./ssh-remote-worker.js";

export interface SshRemoteJobWorkerOptions{artifactRoot:string;aliases?:RemoteDataAlias[];heartbeatIntervalMs?:number;retainRemoteWorkspace?:boolean}

/** Owns Core credentials locally and forwards only one scoped lease over SSH. */
export class SshRemoteJobWorker{
  private readonly artifacts:ContentAddressedStore;
  readonly descriptor:WorkerDescriptor;
  constructor(private readonly jobs:JobStore,private readonly runtime:SystemSshRemoteWorker,private readonly profile:SshHostProfile,private readonly installation:RemoteWorkerInstallation,private readonly options:SshRemoteJobWorkerOptions){
    this.artifacts=new ContentAddressedStore(options.artifactRoot);const platform=installation.platform;if(!platform)throw new Error("Remote installation has no capability snapshot");this.descriptor={workerId:`ssh:${installation.id}`,protocolVersion:"1",executors:[...(platform.executors.python.status==="available"?["python" as const]:[]),...(platform.executors.bubblewrap.status==="available"?["bubblewrap" as const]:[])],capacity:{cpuCores:1,memoryMiB:1024,diskMiB:1024,gpuCount:installation.gpuDevices.length},gpuDevices:installation.gpuDevices,leaseDurationMs:300_000,platform};if(!this.descriptor.executors.length)throw new Error("Remote Worker has no available executor");
  }
  async runOnce():Promise<JobLease|null>{const lease=this.jobs.claim(this.descriptor);if(!lease)return null;if(!lease.job.spec.portableWorkspace){this.fail(lease,"environment","SSH jobs require portableWorkspace");return lease;}let workspace:string|null=null,bridge:any=null,leaseError:Error|null=null,cancelSent=false,heartbeatTimer:NodeJS.Timeout|null=null;try{const prepared=await this.runtime.prepareWorkspace(this.profile,lease,this.artifacts,this.options.aliases??[]);workspace=prepared.workspace;bridge=await this.runtime.connectInstalled(this.profile,this.installation.remotePath,this.installation.contentHash);await bridge.request({type:"lease.open",leaseId:lease.job.id});for(const transfer of prepared.transfers)this.log(lease,"system","Verified remote input transfer",transfer);const interval=this.options.heartbeatIntervalMs??Math.max(1000,Math.floor(this.descriptor.leaseDurationMs/3));heartbeatTimer=setInterval(()=>{try{const heartbeat=this.jobs.heartbeat({jobId:lease.job.id,attempt:lease.attempt,workerId:this.descriptor.workerId,leaseToken:lease.leaseToken,leaseDurationMs:this.descriptor.leaseDurationMs});if(heartbeat.cancelRequested&&!cancelSent){cancelSent=true;bridge.send({type:"lease.cancel",leaseId:lease.job.id});}}catch(error){leaseError=error instanceof Error?error:new Error(String(error));if(!cancelSent){cancelSent=true;bridge.send({type:"lease.cancel",leaseId:lease.job.id});}}},interval);
      const terminal=await bridge.streamRequest({type:"job.execute",leaseId:lease.job.id,spec:{workspace:prepared.workspace,execution:lease.job.spec.execution,mounts:prepared.mounts,outputs:prepared.spec.outputs,limits:lease.job.spec.limits,resources:lease.job.spec.resources,gpuDevices:lease.allocatedGpuDevices}},{timeoutMs:lease.job.spec.limits.wallTimeMs+15_000,onFrame:(frame:any)=>{if(frame.type==="job.log")this.log(lease,frame.stream,frame.message);}});if(heartbeatTimer){clearInterval(heartbeatTimer);heartbeatTimer=null;}if(leaseError)throw leaseError;if(terminal.type==="lease.cancelled"){this.fail(lease,"cancelled","Remote cancellation acknowledged");return lease;}if(terminal.type!=="job.completed"){this.fail(lease,(terminal.failureClass??"environment") as JobFailureClass,String(terminal.message??terminal.code??"Remote execution failed"));return lease;}this.log(lease,"system","Remote resource usage",terminal.resourceUsage);
      const artifacts:Array<Omit<JobArtifact,"id"|"jobId"|"attempt"|"createdAt">>=[];for(const item of terminal.artifacts as any[]){const downloaded=await this.runtime.downloadVerified(this.profile,item.remotePath,item.contentHash,item.bytes,this.artifacts,prepared.spec.transferQuotaBytes);this.log(lease,"system","Verified remote Artifact transfer",downloaded.audit);artifacts.push({name:item.name,mediaType:item.mediaType,contentHash:item.contentHash,bytes:item.bytes,uri:`cas:sha256:${item.contentHash}`,access:item.access});}this.jobs.complete({jobId:lease.job.id,attempt:lease.attempt,workerId:this.descriptor.workerId,leaseToken:lease.leaseToken,artifacts});return lease;
    }catch(error){try{this.fail(lease,cancelSent?"cancelled":/timeout/i.test(String(error))?"timeout":/hash|manifest|data|quota/i.test(String(error))?"data":"environment",error instanceof Error?error.message:String(error));}catch{}return lease;}finally{if(heartbeatTimer)clearInterval(heartbeatTimer);if(bridge)await bridge.close();if(workspace&&!this.options.retainRemoteWorkspace)try{await this.runtime.cleanupWorkspace(this.profile,workspace);}catch{}}
  }
  private log(lease:JobLease,stream:"stdout"|"stderr"|"progress"|"system",message:string,data?:unknown){this.jobs.appendLog({jobId:lease.job.id,attempt:lease.attempt,workerId:this.descriptor.workerId,leaseToken:lease.leaseToken,stream,message,data});}
  private fail(lease:JobLease,failureClass:JobFailureClass,message:string){this.jobs.fail({jobId:lease.job.id,attempt:lease.attempt,workerId:this.descriptor.workerId,leaseToken:lease.leaseToken,failureClass,message});}
}
