import { createHash,randomUUID } from "node:crypto";
import { execFileSync,spawn,type ChildProcessWithoutNullStreams } from "node:child_process";
import { mkdirSync,readFileSync,writeFileSync } from "node:fs";
import { dirname,join,resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline";
import { runProcess } from "../adapters/process.js";
import { PlatformCapabilitySnapshotSchema,SshPreflightResultSchema,type SshHostProfile } from "../public/contracts.js";

export interface SshRuntimeOptions{stateDir:string;workerSource?:string;sshCommand?:string;sftpCommand?:string;sshKeygenCommand?:string;sshKeyscanCommand?:string}
export class SystemSshRemoteWorker{
  private readonly ssh:string;private readonly sftp:string;private readonly keygen:string;private readonly keyscan:string;private readonly workerSource:string;
  constructor(private readonly options:SshRuntimeOptions){this.ssh=options.sshCommand??"ssh";this.sftp=options.sftpCommand??"sftp";this.keygen=options.sshKeygenCommand??"ssh-keygen";this.keyscan=options.sshKeyscanCommand??"ssh-keyscan";this.workerSource=resolve(options.workerSource??fileURLToPath(new URL("../../remote/worker-stdio.mjs",import.meta.url)));mkdirSync(options.stateDir,{recursive:true});}
  knownHosts(profile:SshHostProfile){return join(this.options.stateDir,"known-hosts",`${profile.workspaceId}-${profile.id}`);}
  async preflight(profile:SshHostProfile){const version=await runProcess(this.ssh,["-V"],{timeoutMs:5000,maxOutputBytes:10000}),effective=await runProcess(this.ssh,[...this.configArgs(profile),"-G",profile.hostAlias],{timeoutMs:5000,maxOutputBytes:100000});if(version.exitCode!==0||effective.exitCode!==0)throw new Error(`OpenSSH preflight failed: ${version.stderr||effective.stderr}`);const config=parseSshConfig(effective.stdout),host=config.hostname??profile.hostAlias,user=config.user??"unknown",port=Number(config.port??22),scan=await runProcess(this.keyscan,["-p",String(port),"-T","5",host],{timeoutMs:10000,maxOutputBytes:200000});if(scan.exitCode!==0||!scan.stdout.trim())throw new Error(`SSH host-key scan failed for ${host}:${port}`);const hostKey=scan.stdout.split(/\r?\n/).find(line=>line&&!line.startsWith("#"))!,fingerprint=execFileSync(this.keygen,["-lf","-","-E","sha256"],{input:`${hostKey}\n`,encoding:"utf8"}).trim().split(/\s+/)[1]!;let remotePlatform:null|{os:"linux";arch:string;nodeVersion:string|null}=null,issues:string[]=[];if(profile.status==="trusted"&&profile.approvedFingerprint===fingerprint){const remote=await this.remoteProbe(profile);remotePlatform=remote.platform;issues.push(...remote.issues);}else if(profile.approvedFingerprint&&profile.approvedFingerprint!==fingerprint)issues.push("approved_host_key_changed");else issues.push("host_key_requires_approval");return SshPreflightResultSchema.parse({profileId:profile.id,sshVersion:(version.stderr||version.stdout).trim().split(/\r?\n/)[0],effectiveHost:host,effectiveUser:user,effectivePort:port,proxyJump:config.proxyjump&&config.proxyjump!=="none"?config.proxyjump:null,fingerprint,hostKey,remotePlatform,trusted:profile.status==="trusted"&&profile.approvedFingerprint===fingerprint,issues});}
  approveKnownHost(profile:SshHostProfile){if(!profile.pendingHostKey)throw new Error("SSH profile has no pending host key");const path=this.knownHosts(profile);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,`${profile.pendingHostKey.trim()}\n`,{mode:0o600});return path;}
  async remoteProbe(profile:SshHostProfile){const command="printf 'ARA_OS='; uname -s; printf 'ARA_ARCH='; uname -m; printf 'ARA_NODE='; (node --version 2>/dev/null || true)",result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,command],{timeoutMs:15000,maxOutputBytes:100000});if(result.exitCode!==0)throw new Error(`SSH trusted connection failed: ${result.stderr}`);const values=Object.fromEntries(result.stdout.split(/\r?\n/).filter(line=>line.startsWith("ARA_")).map(line=>{const i=line.indexOf("=");return[line.slice(4,i),line.slice(i+1)];})),issues:string[]=[],remoteArch=normalizeArch(values.ARCH??"unknown");if(values.OS!=="Linux")issues.push(`remote_os_${values.OS||"unknown"}`);if(profile.expectedArch&&remoteArch!==profile.expectedArch)issues.push(`remote_arch_${remoteArch}`);if(!values.NODE)issues.push("remote_node_missing");return{platform:values.OS==="Linux"?{os:"linux" as const,arch:remoteArch,nodeVersion:values.NODE||null}:null,issues};}
  bundle(){const content=readFileSync(this.workerSource),contentHash=createHash("sha256").update(content).digest("hex");return{path:this.workerSource,content,contentHash,protocolVersion:"1" as const};}
  async install(profile:SshHostProfile){if(profile.status!=="trusted")throw new Error("Remote Worker installation requires a trusted SSH profile");const probe=await this.preflight(profile);if(!probe.trusted||!probe.remotePlatform||probe.issues.length)throw new Error(`Remote Worker preflight is not ready: ${probe.issues.join(",")}`);const bundle=this.bundle(),base=`${profile.remoteRoot}/workers/1`,target=`${base}/${bundle.contentHash}`,temporary=`${base}/.${bundle.contentHash}.partial-${randomUUID()}`;for(const value of [base,target,temporary])assertSafeRemotePath(value);await this.runFixed(profile,`mkdir -p ${base} ${temporary}`);const batch=`put "${escapeSftp(this.workerSource)}" "${temporary}/worker-stdio.mjs"\n`;const transfer=await runProcess(this.sftp,[...this.connectionOptions(profile),"-b","-",profile.hostAlias],{stdin:batch,timeoutMs:30000,maxOutputBytes:200000});if(transfer.exitCode!==0)throw new Error(`SFTP Worker upload failed: ${transfer.stderr}`);const remoteHash=(await this.runFixed(profile,`sha256sum ${temporary}/worker-stdio.mjs`)).stdout.trim().split(/\s+/)[0];if(remoteHash!==bundle.contentHash){await this.runFixed(profile,`rm -rf ${temporary}`);throw new Error("Remote Worker bundle hash mismatch");}await this.runFixed(profile,`rm -rf ${target}`);await this.runFixed(profile,`mv ${temporary} ${target}`);const remotePath=`${target}/worker-stdio.mjs`,bridge=await this.connectInstalled(profile,remotePath,bundle.contentHash),hello=bridge.hello;await bridge.close();const unknown={status:"not_checked" as const,reason:"Executor probing is deferred to the remote Worker capability handshake"},platform=PlatformCapabilitySnapshotSchema.parse({os:"linux",arch:probe.remotePlatform.arch,nodeVersion:probe.remotePlatform.nodeVersion??"unknown",pythonVersion:null,executors:{python:unknown,bubblewrap:unknown,pi:unknown},sandbox:unknown,resourceLimits:unknown,processGroups:{status:"available",reason:null},storageModes:["remote_existing"],filesystem:{pathSeparator:"/",caseSensitive:true},ssh:{client:unknown,version:null,sftp:unknown,proxyJump:unknown,multiplexing:unknown},detectedAt:new Date().toISOString()});return{contentHash:bundle.contentHash,remotePath,platform,hello};}
  connectInstalled(profile:SshHostProfile,remotePath:string,contentHash:string){assertSafeRemotePath(remotePath);if(profile.status!=="trusted")throw new Error("SSH Worker connection requires a trusted profile");return SshWorkerBridge.connect({sshCommand:this.ssh,args:[...this.connectionArgs(profile),profile.hostAlias,`node ${remotePath} --stdio --content-hash ${contentHash}`],expectedHash:contentHash});}
  private async runFixed(profile:SshHostProfile,command:string){if(!/^[A-Za-z0-9_./ -]+$/.test(command))throw new Error("Unsafe fixed SSH command");const result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,command],{timeoutMs:30000,maxOutputBytes:200000});if(result.exitCode!==0)throw new Error(`Remote fixed command failed: ${result.stderr}`);return result;}
  private configArgs(profile:SshHostProfile){return profile.sshConfigFile?["-F",profile.sshConfigFile]:[];}
  private connectionOptions(profile:SshHostProfile){return[...this.configArgs(profile),"-o","BatchMode=yes","-o","StrictHostKeyChecking=yes","-o",`UserKnownHostsFile=${this.knownHosts(profile)}`,"-o","ForwardAgent=no","-o","ForwardX11=no","-o","PermitLocalCommand=no","-o","ConnectTimeout=10","-o","ServerAliveInterval=15","-o","ServerAliveCountMax=3"];}
  private connectionArgs(profile:SshHostProfile){return[...this.connectionOptions(profile),"-T"];}
}

export class SshWorkerBridge{
  readonly hello:any;private constructor(private readonly child:ChildProcessWithoutNullStreams,hello:any,private readonly lines:ReturnType<typeof createInterface>){this.hello=hello;}
  static async connect(input:{sshCommand:string;args:string[];expectedHash:string;timeoutMs?:number}){const child=spawn(input.sshCommand,input.args,{stdio:["pipe","pipe","pipe"],windowsHide:true}),lines=createInterface({input:child.stdout,crlfDelay:Infinity}),hello=await nextFrame(lines,input.timeoutMs??15000);if(hello.type!=="hello"||hello.protocolVersion!=="1"||hello.contentHash!==input.expectedHash){child.kill("SIGKILL");throw new Error("Remote Worker handshake mismatch");}return new SshWorkerBridge(child,hello,lines);}
  async request(frame:Record<string,unknown>,timeoutMs=5000){const response=nextFrame(this.lines,timeoutMs);this.child.stdin.write(`${JSON.stringify(frame)}\n`);return response;}
  async close(){try{await this.request({type:"shutdown"},2000);}catch{}this.lines.close();this.child.kill("SIGTERM");}
  disconnect(){this.lines.close();this.child.kill("SIGKILL");}
}
function parseSshConfig(text:string){const result:Record<string,string>={};for(const line of text.split(/\r?\n/)){const match=/^(\S+)\s+(.*)$/.exec(line.trim());if(match)result[match[1]!.toLowerCase()]=match[2]!;}return result;}
function assertSafeRemotePath(value:string){if(!/^\/[A-Za-z0-9._/-]+$/.test(value)||value.split("/").includes(".."))throw new Error("Unsafe remote Worker path");}
function escapeSftp(value:string){return value.replaceAll("\\","\\\\").replaceAll('"','\\"');}
function normalizeArch(value:string){const normalized=value.toLowerCase();if(normalized==="x86_64"||normalized==="amd64")return"x64";if(normalized==="aarch64")return"arm64";return normalized;}
function nextFrame(lines:ReturnType<typeof createInterface>,timeoutMs:number):Promise<any>{return new Promise((resolveFrame,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error("SSH Worker frame timeout"));},timeoutMs),onLine=(line:string)=>{cleanup();try{resolveFrame(JSON.parse(line));}catch(error){reject(error);}},onClose=()=>{cleanup();reject(new Error("SSH Worker channel closed"));},cleanup=()=>{clearTimeout(timer);lines.off("line",onLine);lines.off("close",onClose);};lines.once("line",onLine);lines.once("close",onClose);});}
