import { createHash,randomUUID } from "node:crypto";
import { execFileSync,spawn,type ChildProcessWithoutNullStreams } from "node:child_process";
import { createReadStream,existsSync,mkdirSync,readFileSync,statSync,unlinkSync,writeFileSync } from "node:fs";
import { dirname,join,posix,resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline";
import { runProcess } from "../adapters/process.js";
import { PlatformCapabilitySnapshotSchema,SshPreflightResultSchema,type SshHostProfile } from "../public/contracts.js";
import { PortableWorkspaceSpecSchema,type JobLease } from "../domain/job.js";
import { ContentAddressedStore } from "../infrastructure/artifacts/content-store.js";

export interface RemoteDataAlias{alias:string;manifestHash:string;remotePath:string;access:"project"|"private"}
export interface TransferAudit{direction:"upload"|"download";contentHash:string;bytes:number;resumed:boolean;remotePath:string}

export interface SshRuntimeOptions{stateDir:string;workerSource?:string;sshCommand?:string;sftpCommand?:string;sshKeygenCommand?:string;sshKeyscanCommand?:string}
export class SystemSshRemoteWorker{
  private readonly ssh:string;private readonly sftp:string;private readonly keygen:string;private readonly keyscan:string;private readonly workerSource:string;
  constructor(private readonly options:SshRuntimeOptions){this.ssh=options.sshCommand??"ssh";this.sftp=options.sftpCommand??"sftp";this.keygen=options.sshKeygenCommand??"ssh-keygen";this.keyscan=options.sshKeyscanCommand??"ssh-keyscan";this.workerSource=resolve(options.workerSource??fileURLToPath(new URL("../../remote/worker-stdio.mjs",import.meta.url)));mkdirSync(options.stateDir,{recursive:true});}
  knownHosts(profile:SshHostProfile){return join(this.options.stateDir,"known-hosts",`${profile.workspaceId}-${profile.id}`);}
  async preflight(profile:SshHostProfile){const version=await runProcess(this.ssh,["-V"],{timeoutMs:5000,maxOutputBytes:10000}),effective=await runProcess(this.ssh,[...this.configArgs(profile),"-G",profile.hostAlias],{timeoutMs:5000,maxOutputBytes:100000});if(version.exitCode!==0||effective.exitCode!==0)throw new Error(`OpenSSH preflight failed: ${version.stderr||effective.stderr}`);const config=parseSshConfig(effective.stdout),host=config.hostname??profile.hostAlias,user=config.user??"unknown",port=Number(config.port??22),scan=await runProcess(this.keyscan,["-p",String(port),"-T","5",host],{timeoutMs:10000,maxOutputBytes:200000});if(scan.exitCode!==0||!scan.stdout.trim())throw new Error(`SSH host-key scan failed for ${host}:${port}`);const hostKeys=scan.stdout.split(/\r?\n/).filter(line=>line&&!line.startsWith("#")).sort(),hostKey=hostKeys[0];if(!hostKey)throw new Error(`SSH host-key scan returned no keys for ${host}:${port}`);const fingerprint=execFileSync(this.keygen,["-lf","-","-E","sha256"],{input:`${hostKey}\n`,encoding:"utf8"}).trim().split(/\s+/)[1]!;let remotePlatform:null|{os:"linux";arch:string;nodeVersion:string|null}=null,issues:string[]=[];if(profile.status==="trusted"&&profile.approvedFingerprint===fingerprint){const remote=await this.remoteProbe(profile);remotePlatform=remote.platform;issues.push(...remote.issues);}else if(profile.approvedFingerprint&&profile.approvedFingerprint!==fingerprint)issues.push("approved_host_key_changed");else issues.push("host_key_requires_approval");return SshPreflightResultSchema.parse({profileId:profile.id,sshVersion:(version.stderr||version.stdout).trim().split(/\r?\n/)[0],effectiveHost:host,effectiveUser:user,effectivePort:port,proxyJump:config.proxyjump&&config.proxyjump!=="none"?config.proxyjump:null,fingerprint,hostKey,remotePlatform,trusted:profile.status==="trusted"&&profile.approvedFingerprint===fingerprint,issues});}
  approveKnownHost(profile:SshHostProfile){if(!profile.pendingHostKey)throw new Error("SSH profile has no pending host key");const path=this.knownHosts(profile);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,`${profile.pendingHostKey.trim()}\n`,{mode:0o600});return path;}
  async remoteProbe(profile:SshHostProfile){const command="printf 'ARA_OS='; uname -s; printf 'ARA_ARCH='; uname -m; printf 'ARA_NODE='; (node --version 2>/dev/null || true)",result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,command],{timeoutMs:15000,maxOutputBytes:100000});if(result.exitCode!==0)throw new Error(`SSH trusted connection failed: ${result.stderr}`);const values=Object.fromEntries(result.stdout.split(/\r?\n/).filter(line=>line.startsWith("ARA_")).map(line=>{const i=line.indexOf("=");return[line.slice(4,i),line.slice(i+1)];})),issues:string[]=[],remoteArch=normalizeArch(values.ARCH??"unknown");if(values.OS!=="Linux")issues.push(`remote_os_${values.OS||"unknown"}`);if(profile.expectedArch&&remoteArch!==profile.expectedArch)issues.push(`remote_arch_${remoteArch}`);if(!values.NODE)issues.push("remote_node_missing");return{platform:values.OS==="Linux"?{os:"linux" as const,arch:remoteArch,nodeVersion:values.NODE||null}:null,issues};}
  bundle(){const content=readFileSync(this.workerSource),contentHash=createHash("sha256").update(content).digest("hex");return{path:this.workerSource,content,contentHash,protocolVersion:"1" as const};}
  async install(profile:SshHostProfile){if(profile.status!=="trusted")throw new Error("Remote Worker installation requires a trusted SSH profile");const probe=await this.preflight(profile);if(!probe.trusted||!probe.remotePlatform||probe.issues.length)throw new Error(`Remote Worker preflight is not ready: ${probe.issues.join(",")}`);const bundle=this.bundle(),base=`${profile.remoteRoot}/workers/1`,target=`${base}/${bundle.contentHash}`,temporary=`${base}/.${bundle.contentHash}.partial-${randomUUID()}`;for(const value of [base,target,temporary])assertSafeRemotePath(value);await this.runFixed(profile,`mkdir -p ${base} ${temporary}`);const batch=`put "${escapeSftp(this.workerSource)}" "${temporary}/worker-stdio.mjs"\n`;const transfer=await runProcess(this.sftp,[...this.connectionOptions(profile),"-b","-",profile.hostAlias],{stdin:batch,timeoutMs:30000,maxOutputBytes:200000});if(transfer.exitCode!==0)throw new Error(`SFTP Worker upload failed: ${transfer.stderr}`);const remoteHash=(await this.runFixed(profile,`sha256sum ${temporary}/worker-stdio.mjs`)).stdout.trim().split(/\s+/)[0];if(remoteHash!==bundle.contentHash){await this.runFixed(profile,`rm -rf ${temporary}`);throw new Error("Remote Worker bundle hash mismatch");}await this.runFixed(profile,`rm -rf ${target}`);await this.runFixed(profile,`mv ${temporary} ${target}`);const remotePath=`${target}/worker-stdio.mjs`,bridge=await this.connectInstalled(profile,remotePath,bundle.contentHash),hello=bridge.hello;await bridge.close();const available=(yes:boolean,reason:string)=>({status:yes?"available" as const:"unavailable" as const,reason:yes?null:reason}),notChecked={status:"not_checked" as const,reason:"Not probed by the remote Worker"},platform=PlatformCapabilitySnapshotSchema.parse({os:"linux",arch:probe.remotePlatform.arch,nodeVersion:probe.remotePlatform.nodeVersion??"unknown",pythonVersion:hello.platform.pythonVersion,executors:{python:available(hello.platform.executors.python,"python3 is unavailable"),bubblewrap:available(hello.platform.executors.bubblewrap,"Bubblewrap is unavailable"),pi:notChecked},sandbox:available(hello.platform.executors.bubblewrap,"Bubblewrap is unavailable"),resourceLimits:available(hello.platform.resourceLimits,"prlimit is unavailable"),processGroups:{status:"available",reason:null},storageModes:hello.platform.storageModes,filesystem:{pathSeparator:"/",caseSensitive:true},ssh:{client:notChecked,version:null,sftp:notChecked,proxyJump:notChecked,multiplexing:notChecked},detectedAt:new Date().toISOString()});return{contentHash:bundle.contentHash,remotePath,platform,gpuDevices:hello.platform.gpuDevices??[],hello};}
  connectInstalled(profile:SshHostProfile,remotePath:string,contentHash:string){assertSafeRemotePath(remotePath);assertSafeRemotePath(profile.remoteRoot);if(profile.status!=="trusted")throw new Error("SSH Worker connection requires a trusted profile");return SshWorkerBridge.connect({sshCommand:this.ssh,args:[...this.connectionArgs(profile),profile.hostAlias,`node ${remotePath} --stdio --content-hash ${contentHash} --remote-root ${profile.remoteRoot}`],expectedHash:contentHash});}
  async prepareWorkspace(profile:SshHostProfile,lease:JobLease,artifacts:ContentAddressedStore,aliases:RemoteDataAlias[]=[]){const spec=PortableWorkspaceSpecSchema.parse(lease.job.spec.portableWorkspace),workspace=`${profile.remoteRoot}/jobs/${lease.job.id}-${lease.attempt}`;assertSafeRemotePath(workspace);const declared=spec.inputs.reduce((sum,item)=>sum+item.bytes,0);if(declared>spec.transferQuotaBytes||declared>lease.job.spec.resources.diskMiB*1024**2)throw new Error("Portable workspace transfer quota exceeded");await this.runFixed(profile,`mkdir -p ${workspace}`);const transfers:TransferAudit[]=[];for(const input of spec.inputs){if(!artifacts.has(input.contentHash))throw new Error(`Local CAS input is missing: ${input.contentHash}`);const local=artifacts.pathFor(input.contentHash),actual=await hashFile(local);if(actual!==input.contentHash||statSync(local).size!==input.bytes)throw new Error(`Local CAS input manifest mismatch: ${input.contentHash}`);const remoteCas=`${profile.remoteRoot}/cas/sha256/${input.contentHash.slice(0,2)}/${input.contentHash.slice(2,4)}/${input.contentHash}`,target=portableRemotePath(workspace,input.target);await this.runFixed(profile,`mkdir -p ${posix.dirname(remoteCas)} ${posix.dirname(target)}`);transfers.push(await this.uploadVerified(profile,local,remoteCas,input.contentHash,spec.transferQuotaBytes));await this.runFixed(profile,`cp ${remoteCas} ${target}`);}
    const mounts=spec.remoteData.map(declaration=>{if(lease.job.spec.dataRole==="confirmation"&&!lease.authorizedMounts.some(mount=>"kind" in mount&&mount.kind==="remote_alias"&&mount.alias===declaration.alias&&mount.manifestHash===declaration.manifestHash&&mount.target===declaration.target))throw new Error(`Confirmation remote alias is not authorized by this lease: ${declaration.alias}`);const alias=aliases.find(item=>item.alias===declaration.alias);if(!alias||alias.manifestHash!==declaration.manifestHash)throw new Error(`Remote data alias manifest mismatch: ${declaration.alias}`);assertRemoteDataPath(profile,alias.remotePath);return{source:alias.remotePath,target:declaration.target,alias:alias.alias,manifestHash:alias.manifestHash};});for(const mount of mounts){const remoteHash=(await this.runFixed(profile,`sha256sum ${mount.source}`)).stdout.trim().split(/\s+/)[0];if(remoteHash!==mount.manifestHash)throw new Error(`Remote data alias content mismatch: ${mount.alias}`);}return{workspace,mounts,transfers,spec};}
  async uploadVerified(profile:SshHostProfile,localPath:string,remotePath:string,contentHash:string,quotaBytes:number):Promise<TransferAudit>{assertSafeRemotePath(remotePath);const bytes=statSync(localPath).size;if(bytes>quotaBytes)throw new Error("Transfer quota exceeded");const existing=await this.remoteHash(profile,remotePath);if(existing===contentHash)return{direction:"upload",contentHash,bytes,resumed:false,remotePath};const partial=`${remotePath}.partial`;await this.runFixed(profile,`mkdir -p ${posix.dirname(remotePath)}`);const partialSize=await this.remoteSize(profile,partial),resumed=partialSize>0&&partialSize<bytes;const batch=`put ${resumed?"-a ":""}"${escapeSftp(localPath)}" "${partial}"\n`;const transfer=await runProcess(this.sftp,[...this.connectionOptions(profile),"-b","-",profile.hostAlias],{stdin:batch,timeoutMs:120000,maxOutputBytes:200000});if(transfer.exitCode!==0)throw new Error(`SFTP upload failed: ${transfer.stderr}`);const remoteHash=await this.remoteHash(profile,partial);if(remoteHash!==contentHash){await this.runFixed(profile,`rm -f ${partial}`);throw new Error("Uploaded content hash mismatch");}await this.runFixed(profile,`mv ${partial} ${remotePath}`);return{direction:"upload",contentHash,bytes,resumed,remotePath};}
  async downloadVerified(profile:SshHostProfile,remotePath:string,expectedHash:string,expectedBytes:number,artifacts:ContentAddressedStore,quotaBytes:number):Promise<{audit:TransferAudit;path:string}>{assertSafeRemotePath(remotePath);if(expectedBytes>quotaBytes)throw new Error("Download quota exceeded");const remoteHash=await this.remoteHash(profile,remotePath);if(remoteHash!==expectedHash)throw new Error("Remote Artifact hash mismatch");const staging=join(this.options.stateDir,"downloads",`${expectedHash}.partial`);mkdirSync(dirname(staging),{recursive:true});const current=existsSync(staging)?statSync(staging).size:0,resumed=current>0&&current<expectedBytes;if(current>expectedBytes)unlinkSync(staging);const batch=`get ${resumed?"-a ":""}"${remotePath}" "${escapeSftp(staging)}"\n`,transfer=await runProcess(this.sftp,[...this.connectionOptions(profile),"-b","-",profile.hostAlias],{stdin:batch,timeoutMs:120000,maxOutputBytes:200000});if(transfer.exitCode!==0)throw new Error(`SFTP download failed: ${transfer.stderr}`);const localHash=await hashFile(staging);if(localHash!==expectedHash||statSync(staging).size!==expectedBytes){unlinkSync(staging);throw new Error("Downloaded Artifact manifest mismatch");}const stored=artifacts.put(readFileSync(staging));unlinkSync(staging);return{audit:{direction:"download",contentHash:expectedHash,bytes:expectedBytes,resumed,remotePath},path:stored.path};}
  async cleanupWorkspace(profile:SshHostProfile,workspace:string){assertRemoteJobPath(profile,workspace);await this.runFixed(profile,`rm -rf ${workspace}`);}
  private async remoteHash(profile:SshHostProfile,path:string){assertSafeRemotePath(path);const result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,`test -f ${path} && sha256sum ${path} || true`],{timeoutMs:30000,maxOutputBytes:1000});if(result.exitCode!==0)throw new Error(`Remote hash negotiation failed: ${result.stderr}`);return result.stdout.trim().split(/\s+/)[0]??"";}
  private async remoteSize(profile:SshHostProfile,path:string){assertSafeRemotePath(path);const result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,`test -f ${path} && stat -c %s ${path} || true`],{timeoutMs:30000,maxOutputBytes:1000});if(result.exitCode!==0)return 0;return Number(result.stdout.trim())||0;}
  private async runFixed(profile:SshHostProfile,command:string){if(!/^[A-Za-z0-9_./ -]+$/.test(command))throw new Error("Unsafe fixed SSH command");const result=await runProcess(this.ssh,[...this.connectionArgs(profile),profile.hostAlias,command],{timeoutMs:30000,maxOutputBytes:200000});if(result.exitCode!==0)throw new Error(`Remote fixed command failed: ${result.stderr}`);return result;}
  private configArgs(profile:SshHostProfile){return profile.sshConfigFile?["-F",profile.sshConfigFile]:[];}
  private connectionOptions(profile:SshHostProfile){return[...this.configArgs(profile),"-o","BatchMode=yes","-o","StrictHostKeyChecking=yes","-o",`UserKnownHostsFile=${this.knownHosts(profile)}`,"-o","ForwardAgent=no","-o","ForwardX11=no","-o","PermitLocalCommand=no","-o","ConnectTimeout=10","-o","ServerAliveInterval=15","-o","ServerAliveCountMax=3"];}
  private connectionArgs(profile:SshHostProfile){return[...this.connectionOptions(profile),"-T"];}
}

export class SshWorkerBridge{
  readonly hello:any;private constructor(private readonly child:ChildProcessWithoutNullStreams,hello:any,private readonly lines:ReturnType<typeof createInterface>){this.hello=hello;}
  static async connect(input:{sshCommand:string;args:string[];expectedHash:string;timeoutMs?:number}){const child=spawn(input.sshCommand,input.args,{stdio:["pipe","pipe","pipe"],windowsHide:true}),lines=createInterface({input:child.stdout,crlfDelay:Infinity}),hello=await nextFrame(lines,input.timeoutMs??15000);if(hello.type!=="hello"||hello.protocolVersion!=="1"||hello.contentHash!==input.expectedHash){child.kill("SIGKILL");throw new Error("Remote Worker handshake mismatch");}return new SshWorkerBridge(child,hello,lines);}
  async request(frame:Record<string,unknown>,timeoutMs=5000){const response=nextFrame(this.lines,timeoutMs);this.child.stdin.write(`${JSON.stringify(frame)}\n`);return response;}
  send(frame:Record<string,unknown>){this.child.stdin.write(`${JSON.stringify(frame)}\n`);}
  async streamRequest(frame:Record<string,unknown>,options:{timeoutMs:number;onFrame?:(frame:any)=>void;terminal?:(frame:any)=>boolean}){this.child.stdin.write(`${JSON.stringify(frame)}\n`);const deadline=Date.now()+options.timeoutMs;for(;;){const value=await nextFrame(this.lines,Math.max(1,deadline-Date.now()));options.onFrame?.(value);if(options.terminal?.(value)??["job.completed","job.failed","error","lease.cancelled"].includes(value.type))return value;}}
  async close(){try{await this.request({type:"shutdown"},2000);}catch{}this.lines.close();this.child.kill("SIGTERM");}
  disconnect(){this.lines.close();this.child.kill("SIGKILL");}
}
function parseSshConfig(text:string){const result:Record<string,string>={};for(const line of text.split(/\r?\n/)){const match=/^(\S+)\s+(.*)$/.exec(line.trim());if(match)result[match[1]!.toLowerCase()]=match[2]!;}return result;}
function assertSafeRemotePath(value:string){if(!/^\/[A-Za-z0-9._/-]+$/.test(value)||value.split("/").includes(".."))throw new Error("Unsafe remote Worker path");}
function portableRemotePath(root:string,value:string){if(!value||/[\0\r\n]/.test(value)||value.startsWith("/")||value.startsWith("\\")||/^[A-Za-z]:/.test(value)||value.split(/[\\/]/).some(part=>part===".."||part===""))throw new Error("Unsafe portable workspace path");const result=posix.resolve(root,value),relative=posix.relative(root,result);if(relative.startsWith("..")||posix.isAbsolute(relative))throw new Error("Portable workspace path escapes root");assertSafeRemotePath(result);return result;}
function assertRemoteDataPath(profile:SshHostProfile,value:string){assertSafeRemotePath(value);const root=`${profile.remoteRoot}/data/`;if(!value.startsWith(root))throw new Error("Remote data alias escapes profile data root");}
function assertRemoteJobPath(profile:SshHostProfile,value:string){assertSafeRemotePath(value);if(!value.startsWith(`${profile.remoteRoot}/jobs/`))throw new Error("Remote job workspace escapes profile root");}
function escapeSftp(value:string){return value.replaceAll("\\","\\\\").replaceAll('"','\\"');}
function normalizeArch(value:string){const normalized=value.toLowerCase();if(normalized==="x86_64"||normalized==="amd64")return"x64";if(normalized==="aarch64")return"arm64";return normalized;}
function nextFrame(lines:ReturnType<typeof createInterface>,timeoutMs:number):Promise<any>{return new Promise((resolveFrame,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error("SSH Worker frame timeout"));},timeoutMs),onLine=(line:string)=>{cleanup();try{resolveFrame(JSON.parse(line));}catch(error){reject(error);}},onClose=()=>{cleanup();reject(new Error("SSH Worker channel closed"));},cleanup=()=>{clearTimeout(timer);lines.off("line",onLine);lines.off("close",onClose);};lines.once("line",onLine);lines.once("close",onClose);});}
async function hashFile(path:string){const hash=createHash("sha256");for await(const chunk of createReadStream(path))hash.update(chunk);return hash.digest("hex");}
