import { randomUUID } from "node:crypto";
import { z } from "zod";
import { hashPayload } from "./research.js";

const Hash=z.string().regex(/^[a-f0-9]{64}$/);
export const BaselineFailureClassSchema=z.enum(["none","environment","data","scientific","budget","timeout","cancelled","missing_run","unit_drift","manifest_mismatch","tolerance"]);
export const BaselineSpecSchema=z.object({protocolHash:Hash,dataManifestHash:Hash,experimentalUnit:z.string().min(1),metric:z.string().min(1),direction:z.enum(["maximize","minimize"]),expectedRunIds:z.array(z.string().min(1)).min(1),expectedMin:z.number().finite(),expectedMax:z.number().finite(),absoluteTolerance:z.number().nonnegative(),requiredArtifacts:z.array(z.string().min(1)).default([])}).strict().refine(value=>value.expectedMin<=value.expectedMax,"expectedMin must not exceed expectedMax").refine(value=>new Set(value.expectedRunIds).size===value.expectedRunIds.length,"expectedRunIds must be unique");
export type BaselineSpec=z.infer<typeof BaselineSpecSchema>;
export const BaselineRunSchema=z.object({runId:z.string().min(1),protocolHash:Hash,dataManifestHash:Hash,experimentalUnit:z.string().min(1),status:z.enum(["succeeded","failed"]),observed:z.number().finite().nullable(),failureClass:BaselineFailureClassSchema.exclude(["none"]).nullable(),artifacts:z.array(z.object({name:z.string().min(1),contentHash:Hash,bytes:z.number().int().nonnegative()}).strict())}).strict().refine(value=>(value.status==="succeeded")===(value.observed!==null),"Succeeded runs require observed; failed runs forbid it").refine(value=>(value.status==="failed")===(value.failureClass!==null),"Failed runs require failureClass");
export type BaselineRun=z.infer<typeof BaselineRunSchema>;
export const BaselineResultSchema=z.object({id:z.string().min(1),status:z.enum(["passed","failed"]),failureClass:BaselineFailureClassSchema,protocolHash:Hash,dataManifestHash:Hash,experimentalUnit:z.string().min(1),observedMean:z.number().finite().nullable(),runIds:z.array(z.string()),artifactHashes:z.array(Hash),issues:z.array(z.string()),contentHash:Hash,evaluatedAt:z.string()}).strict();
export type BaselineResult=z.infer<typeof BaselineResultSchema>;

export function evaluateBaseline(rawSpec:unknown,rawRuns:unknown[],now=new Date()):BaselineResult{const spec=BaselineSpecSchema.parse(rawSpec),runs=rawRuns.map(item=>BaselineRunSchema.parse(item)),issues:string[]=[];let failure:z.infer<typeof BaselineFailureClassSchema>="none";const mark=(value:z.infer<typeof BaselineFailureClassSchema>)=>{if(failure==="none")failure=value;};const byId=new Map(runs.map(run=>[run.runId,run]));if(runs.length!==byId.size){issues.push("duplicate_run");mark("missing_run");}for(const id of spec.expectedRunIds)if(!byId.has(id)){issues.push(`missing_run:${id}`);mark("missing_run");}for(const run of runs)if(!spec.expectedRunIds.includes(run.runId)){issues.push(`unexpected_run:${run.runId}`);mark("missing_run");}for(const run of runs){if(run.protocolHash!==spec.protocolHash||run.dataManifestHash!==spec.dataManifestHash){issues.push(`manifest_mismatch:${run.runId}`);mark("manifest_mismatch");}else if(run.experimentalUnit!==spec.experimentalUnit){issues.push(`unit_drift:${run.runId}`);mark("unit_drift");}else if(run.status==="failed"){issues.push(`failed_run:${run.runId}:${run.failureClass}`);mark(run.failureClass!);}for(const required of spec.requiredArtifacts)if(!run.artifacts.some(item=>item.name===required)){issues.push(`missing_artifact:${run.runId}:${required}`);mark("data");}}
  const values=runs.flatMap(run=>run.observed===null?[]:[run.observed]),mean=values.length?values.reduce((a,b)=>a+b,0)/values.length:null;if(failure==="none"&&(mean===null||mean<spec.expectedMin-spec.absoluteTolerance||mean>spec.expectedMax+spec.absoluteTolerance)){issues.push("outside_tolerance");mark("tolerance");}const body={id:`baseline-result-${randomUUID()}`,status:failure==="none"?"passed" as const:"failed" as const,failureClass:failure,protocolHash:spec.protocolHash,dataManifestHash:spec.dataManifestHash,experimentalUnit:spec.experimentalUnit,observedMean:mean,runIds:runs.map(item=>item.runId).sort(),artifactHashes:[...new Set(runs.flatMap(run=>run.artifacts.map(item=>item.contentHash)))].sort(),issues,evaluatedAt:now.toISOString()};return BaselineResultSchema.parse({...body,contentHash:hashPayload(body)});}

export const ReleaseCheckIdSchema=z.enum(["migration","bundle","real_scenario","t3","package","license","secret","platform_matrix"]);
export const ReleaseEvidenceSchema=z.object({checks:z.array(z.object({id:ReleaseCheckIdSchema,status:z.enum(["passed","failed","not_evaluated"]),mandatory:z.boolean(),artifactHashes:z.array(Hash).default([]),detail:z.string().min(1)}).strict()),knownLimitations:z.array(z.string()).default([])}).strict();
export const ReleaseEvaluationSchema=z.object({status:z.enum(["ready","blocked"]),checks:z.array(z.object({id:ReleaseCheckIdSchema,status:z.enum(["passed","failed","not_evaluated"]),mandatory:z.boolean(),artifactHashes:z.array(Hash),detail:z.string()}).strict()).length(8),blockers:z.array(z.string()),knownLimitations:z.array(z.string()),evaluatedAt:z.string(),sideEffects:z.literal("none")}).strict();
export type ReleaseEvaluation=z.infer<typeof ReleaseEvaluationSchema>;
export function evaluateRelease(raw:unknown,now=new Date()):ReleaseEvaluation{const evidence=ReleaseEvidenceSchema.parse(raw),ids=ReleaseCheckIdSchema.options,duplicates=ids.filter(id=>evidence.checks.filter(item=>item.id===id).length>1);if(duplicates.length)throw new Error(`Duplicate release checks: ${duplicates.join(",")}`);const checks=ids.map(id=>evidence.checks.find(item=>item.id===id)??{id,status:"not_evaluated" as const,mandatory:true,artifactHashes:[],detail:"No evidence supplied"}),blockers=checks.flatMap(item=>!item.mandatory?[]:item.status!=="passed"?[`${item.id}:${item.status}`]:item.artifactHashes.length===0?[`${item.id}:missing_artifact`]:[]);return ReleaseEvaluationSchema.parse({status:blockers.length?"blocked":"ready",checks,blockers,knownLimitations:evidence.knownLimitations,evaluatedAt:now.toISOString(),sideEffects:"none"});}
