import { randomUUID } from "node:crypto";
import { z } from "zod";
import { FactAssertionSchema,auditFactAssertions,assertFactAudit,type FactLedger } from "./facts.js";
import { hashPayload } from "./research.js";

export const ExperimentOptionSchema=z.object({id:z.string().min(1),description:z.string().min(10),discriminates:z.array(z.tuple([z.string().min(1),z.string().min(1)])).min(1),expectedObservation:z.string().min(10),estimatedGpuHours:z.number().nonnegative(),estimatedWallHours:z.number().nonnegative(),usesConfirmation:z.boolean().default(false)});
export type ExperimentOption=z.infer<typeof ExperimentOptionSchema>;
export const ScientificDecisionSchema=z.object({id:z.string().min(1),programId:z.string().min(1),studyId:z.string().min(1),sequence:z.number().int().positive(),action:z.enum(["run_discriminating_experiment","continue_exploration","freeze_candidate","redesign","stop_inconclusive","stop_low_value"]),selectedOptionId:z.string().nullable(),options:z.array(ExperimentOptionSchema),hypothesisIds:z.array(z.string()).min(2),rivalHypothesisIds:z.array(z.string()).min(1),factLedgerId:z.string().min(1),factAssertions:z.array(FactAssertionSchema).min(1),budgetSnapshot:z.object({remainingGpuHours:z.number().nonnegative(),remainingWallHours:z.number().nonnegative()}),rationale:z.string().min(20),stopCondition:z.string().min(10),registeredBeforeResult:z.literal(true),inputHash:z.string().regex(/^[a-f0-9]{64}$/),createdAt:z.string()});
export type ScientificDecision=z.infer<typeof ScientificDecisionSchema>;
export const ScientificDecisionResultSchema=z.object({id:z.string().min(1),decisionId:z.string().min(1),studyId:z.string().min(1),factLedgerId:z.string().min(1),factAssertions:z.array(FactAssertionSchema).min(1),conclusion:z.enum(["supports_target","supports_rival","supports_null","mixed","execution_failure"]),details:z.string().min(20),createdAt:z.string()});
export type ScientificDecisionResult=z.infer<typeof ScientificDecisionResultSchema>;

export function createScientificDecision(input:{programId:string;studyId:string;sequence:number;action:ScientificDecision["action"];selectedOptionId?:string|null;hypothesisIds:string[];rivalHypothesisIds:string[];factLedger:FactLedger;factAssertions:z.infer<typeof FactAssertionSchema>[];rationale:string;stopCondition:string;options:ExperimentOption[];remainingGpuHours:number;remainingWallHours:number;confirmationVisible:boolean}):ScientificDecision{const options=input.options.map(option=>ExperimentOptionSchema.parse(option)),selected=input.selectedOptionId?options.find(option=>option.id===input.selectedOptionId):undefined;if(input.action==="run_discriminating_experiment"&&!selected)throw new Error("A discriminating experiment action requires a selected option");if(selected&&!selected.discriminates.some(pair=>pair.some(id=>input.rivalHypothesisIds.includes(id))))throw new Error("Selected experiment must discriminate at least one rival hypothesis");if(selected&&(selected.estimatedGpuHours>input.remainingGpuHours||selected.estimatedWallHours>input.remainingWallHours))throw new Error("Selected experiment exceeds the remaining resource wall");if(selected?.usesConfirmation&&!input.confirmationVisible)throw new Error("Confirmation data cannot be selected during exploration");const audit=auditFactAssertions(input.factLedger,`scientific-decision-${input.sequence}`,input.factAssertions,{requireAll:true});assertFactAudit(audit);const body={programId:input.programId,studyId:input.studyId,sequence:input.sequence,action:input.action,selectedOptionId:input.selectedOptionId??null,options,hypothesisIds:input.hypothesisIds,rivalHypothesisIds:input.rivalHypothesisIds,factLedgerId:input.factLedger.id,factAssertions:input.factAssertions,budgetSnapshot:{remainingGpuHours:input.remainingGpuHours,remainingWallHours:input.remainingWallHours},rationale:input.rationale,stopCondition:input.stopCondition,registeredBeforeResult:true as const};return ScientificDecisionSchema.parse({...body,id:`scientific-decision-${randomUUID()}`,inputHash:hashPayload(body),createdAt:new Date().toISOString()});}
