import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { BaselineResultSchema,PUBLIC_SCHEMA_VERSION,ReleaseEvaluationSchema,ResearchApplication,type Actor } from "../src/public/index.js";
import { evaluateBaseline,evaluateRelease } from "../src/domain/baseline-release.js";

const actor:Actor={id:"user:y",kind:"user"},workspaceId="workspace:y";let n=0;const ctx=(projectId:string|null)=>({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:`y-${++n}`,idempotencyKey:`y-${n}`,workspaceId,projectId,actor,issuedAt:new Date().toISOString()});
const spec={protocolHash:"a".repeat(64),dataManifestHash:"b".repeat(64),experimentalUnit:"training seed",metric:"accuracy",direction:"maximize" as const,expectedRunIds:["r1","r2"],expectedMin:.79,expectedMax:.82,absoluteTolerance:.01,requiredArtifacts:["metrics"]};
const run=(runId:string,value:number,patch:Record<string,unknown>={})=>({runId,protocolHash:spec.protocolHash,dataManifestHash:spec.dataManifestHash,experimentalUnit:spec.experimentalUnit,status:"succeeded",observed:value,failureClass:null,artifacts:[{name:"metrics",contentHash:(runId==="r1"?"c":"d").repeat(64),bytes:10}],...patch});
const jobSpec=(gate?:{resultId:string;resultHash:string})=>({name:"candidate exploration",dataRole:"exploration",studyId:null,execution:{kind:"bubblewrap",workspace:"/tmp",command:"/bin/true",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:64,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:1000,maxArtifactBytes:1000},priority:0,resumable:false,maxAttempts:1,executionPhase:"exploration",baselineGate:gate});
async function project(app:ResearchApplication){const result=await app.execute({...ctx(null),type:"project.create",payload:{intent:{title:"Y gate fixture",direction:"Validate baseline and release public gates with deterministic fixtures.",domain:"systems",constraints:[],allowedData:["fixture"],prohibitions:[],profile:"smoke",budget:{gpuHours:.001,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}}});assert.equal(result.status,"accepted");return result.projectId!;}

test("BaselineSpec rejects false baselines, unit drift, missing and failed runs",()=>{assert.equal(evaluateBaseline(spec,[run("r1",.80),run("r2",.81)]).status,"passed");assert.equal(evaluateBaseline(spec,[run("r1",.80)]).failureClass,"missing_run");assert.equal(evaluateBaseline(spec,[run("r1",.80),run("r2",.81,{experimentalUnit:"test row"})]).failureClass,"unit_drift");assert.equal(evaluateBaseline(spec,[run("r1",.80),run("r2",.81,{protocolHash:"e".repeat(64)})]).failureClass,"manifest_mismatch");assert.equal(evaluateBaseline(spec,[run("r1",.80),run("r2",.81,{status:"failed",observed:null,failureClass:"environment"})]).failureClass,"environment");assert.equal(evaluateBaseline(spec,[run("r1",.9),run("r2",.91)]).failureClass,"tolerance");});

test("only a recorded passed baseline can open candidate exploration",async t=>{const dir=mkdtempSync(join(tmpdir(),"ara-y-baseline-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await project(app),fake=await app.execute({...ctx(projectId),type:"job.submit",payload:{spec:jobSpec({resultId:"fake",resultHash:"f".repeat(64)}),confirmationToken:null}});assert.equal(fake.status,"rejected");assert.equal(fake.error?.code,"GATE_REJECTED");const evaluated=await app.execute({...ctx(projectId),type:"baseline.evaluate",payload:{spec,runs:[run("r1",.80),run("r2",.81)]}});assert.equal(evaluated.status,"accepted");const result=BaselineResultSchema.parse((evaluated.data as any).result);assert.equal(result.status,"passed");const accepted=await app.execute({...ctx(projectId),type:"job.submit",payload:{spec:jobSpec({resultId:result.id,resultHash:result.contentHash}),confirmationToken:null}});assert.equal(accepted.status,"accepted");});

test("release.evaluate is fail closed, preserves not_evaluated, and has no publish side effect",async t=>{const ids=["migration","bundle","real_scenario","t3","package","license","secret","platform_matrix"] as const,passed=ids.map(id=>({id,status:"passed" as const,mandatory:true,artifactHashes:["a".repeat(64)],detail:`${id} passed`}));assert.equal(evaluateRelease({checks:passed,knownLimitations:[]}).status,"ready");const blocked=evaluateRelease({checks:passed.filter(item=>item.id!=="platform_matrix").map(item=>item.id==="license"?{...item,status:"not_evaluated" as const}:item).map(item=>item.id==="secret"?{...item,status:"failed" as const}:item),knownLimitations:["fixture"]});assert.equal(blocked.status,"blocked");assert.ok(blocked.blockers.includes("license:not_evaluated"));assert.ok(blocked.blockers.includes("secret:failed"));assert.ok(blocked.blockers.includes("platform_matrix:not_evaluated"));assert.equal(blocked.sideEffects,"none");const noAudit=evaluateRelease({checks:passed.map(item=>item.id==="package"?{...item,artifactHashes:[]}:item),knownLimitations:[]});assert.ok(noAudit.blockers.includes("package:missing_artifact"));const dir=mkdtempSync(join(tmpdir(),"ara-y-release-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());await project(app);const queried=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"release",type:"release.evaluate",workspaceId,projectId:null,actor,evidence:{checks:passed,knownLimitations:["No publish"]}});assert.equal(queried.status,"ok",JSON.stringify(queried));assert.equal(ReleaseEvaluationSchema.parse(queried.data).status,"ready");});
