import assert from "node:assert/strict";
import Database from "better-sqlite3";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { ResearchClient } from "../src/public/client.js";
import { MemorySecretProvider, startCoreService } from "../src/public/service.js";
import { PUBLIC_SCHEMA_VERSION, type Actor } from "../src/public/contracts.js";
import { runProcess } from "../src/adapters/process.js";
import { ServiceAuditStore } from "../src/infrastructure/db/service-audit-store.js";
import { ResearchApplication } from "../src/public/application.js";
import { applyMigrationTransaction } from "../src/infrastructure/db/research-store.js";

const actor:Actor={id:"user:s",kind:"user"},workspaceId="workspace:s";
const base={schemaVersion:PUBLIC_SCHEMA_VERSION,workspaceId,actor,issuedAt:"2026-10-01T00:00:00.000Z"};
let counter=0;const command=(type:string,projectId:string|null,payload:unknown)=>({...base,type,projectId,payload,commandId:`s-command-${++counter}`,idempotencyKey:`s-key-${counter}`});
const query=(type:string,projectId:string|null,extra:Record<string,unknown>={})=>({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`s-query-${++counter}`,type,workspaceId,projectId,actor,...extra});
const intent={title:"S service study",direction:"Verify that the headless service and clients preserve public research gates.",domain:"AI/ML",constraints:[],allowedData:["fixture"],prohibitions:["no internal client access"],profile:"exploratory" as const,budget:{gpuHours:1,wallHours:1,diskGiB:1,modelCalls:2,knownCostUsd:0}};

async function openClient(baseUrl:string,tokenFile:string){return ResearchClient.connect({baseUrl,token:readFileSync(tokenFile,"utf8").trim()});}
async function cli(dataDir:string,databasePath:string,args:string[]){const output=await runProcess(process.execPath,["--import","tsx","src/reference-cli.ts",...args],{timeoutMs:10000,env:{PATH:process.env.PATH,AUTO_RESEARCH_SERVICE_DIR:dataDir,AUTO_RESEARCH_DATABASE:databasePath}});assert.equal(output.exitCode,0,output.stderr);return JSON.parse(output.stdout);}

test("Core Service authenticates, streams events, audits permissions and survives restart",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-s-service-")),databasePath=join(dir,"research.db"),dataDir=join(dir,"service");t.after(()=>rmSync(dir,{recursive:true,force:true}));let service=await startCoreService({databasePath,dataDir,streamPollMs:10});let closed=false;t.after(async()=>{if(!closed)await service.close();});assert.equal(service.address.host,"127.0.0.1");assert.equal(service.address.capabilities.offline,true);assert.equal(service.address.capabilities.telemetry,false);assert.ok(service.address.tokenFile);
  const unauthenticated=await fetch(`${service.address.baseUrl}/v1/capabilities`);assert.equal(unauthenticated.status,401);const discovery=JSON.parse(readFileSync(service.address.discoveryFile,"utf8"));assert.equal("token" in discovery,false);const token=readFileSync(service.address.tokenFile!,"utf8").trim(),client=await openClient(service.address.baseUrl,service.address.tokenFile!);
  const created=await client.execute(command("project.create",null,{intent}));assert.equal(created.status,"accepted");const projectId=created.projectId!;const status=await client.query(query("project.status",projectId));assert.equal(status.status,"ok");
  const abort=new AbortController(),stream=client.stream({workspaceId,projectId,fromSequence:1,signal:abort.signal}),first=await stream.next();assert.equal(first.value?.event,"research-event");assert.equal((first.value?.data as any).type,"project.created");abort.abort();
  const pythonSpec={name:"unsafe python",dataRole:"exploration",studyId:null,execution:{kind:"python",workspace:dir,script:"run.py",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:10000,maxArtifactBytes:10000},priority:0,resumable:true,maxAttempts:1};await assert.rejects(()=>client.execute(command("job.submit",projectId,{spec:pythonSpec,confirmationToken:null})),/denies permissions: network/);
  const bubbleSpec={...pythonSpec,name:"offline bubblewrap",execution:{kind:"bubblewrap",workspace:dir,command:"/bin/true",args:[],env:{},artifactPaths:[]}},submitted=await client.execute(command("job.submit",projectId,{spec:bubbleSpec,confirmationToken:null}));assert.equal(submitted.status,"accepted");const eventPage=await client.query(query("project.events",projectId,{fromSequence:1,limit:100})),jobEvent=(eventPage.data as any).events.find((item:any)=>item.type==="job.submitted");assert.deepEqual(jobEvent.permissions.sort(),["filesystem.read","filesystem.write","process"].sort());assert.deepEqual(jobEvent.externalServices,[]);const jobId=(submitted.data as any).job.id,worker={workerId:"worker:s",protocolVersion:"1",executors:["bubblewrap"],capacity:{cpuCores:1,memoryMiB:512,diskMiB:512,gpuCount:0},gpuDevices:[],leaseDurationMs:5000},claimed=await client.worker({type:"worker.claim",requestId:"worker-claim",worker}),lease=(claimed.data as any).lease;await client.worker({type:"worker.log",requestId:"worker-log",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"progress",message:"service-worker-progress"});const logAbort=new AbortController(),logStream=client.stream({workspaceId,projectId,fromSequence:999,jobId,logFrom:1,signal:logAbort.signal}),logEvent=await logStream.next();assert.equal(logEvent.value?.event,"job-log");logAbort.abort();await client.worker({type:"worker.complete",requestId:"worker-complete",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,artifacts:[]});assert.equal(((await client.query(query("job.get",projectId,{jobId}))).data as any).job.status,"succeeded");
  const audit=await client.audit({workspaceId,limit:100}) as any,allAudit=await client.audit({limit:200}) as any;assert.equal(audit.records.some((item:any)=>item.status==="rejected"&&item.requiredPermissions.includes("network")),true);assert.equal(allAudit.records.some((item:any)=>item.externalServices.includes("worker-runtime")),true);const databaseBytes=Buffer.concat([readFileSync(databasePath),...(existsSync(`${databasePath}-wal`)?[readFileSync(`${databasePath}-wal`)]:[])]);assert.equal(databaseBytes.includes(Buffer.from(token)),false,"service auth secret must not enter SQLite/WAL");
  await service.close();closed=true;assert.equal(existsSync(service.address.discoveryFile),false);service=await startCoreService({databasePath,dataDir});closed=false;const reopened=await openClient(service.address.baseUrl,service.address.tokenFile!);assert.equal((await reopened.query(query("project.status",projectId))).status,"ok");
});

test("Python SDK and reference CLI use only the service contract for a scoped workflow and plugin catalog",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-s-clients-")),databasePath=join(dir,"research.db"),dataDir=join(dir,"service"),plugin=join(dir,"plugin");mkdirSync(plugin);writeFileSync(join(plugin,"package.json"),JSON.stringify({name:"fixture-skill",version:"1.0.0",description:"CLI plugin fixture",license:"MIT",pi:{skills:["skills"]},autoResearch:{permissions:["filesystem.read"]}}));mkdirSync(join(plugin,"skills"));writeFileSync(join(plugin,"skills","SKILL.md"),"# Fixture\n");t.after(()=>rmSync(dir,{recursive:true,force:true}));const service=await startCoreService({databasePath,dataDir,streamPollMs:10});t.after(()=>service.close());
  const created=await cli(dataDir,databasePath,["new",workspaceId,writeJson(dir,"intent.json",intent)]),projectId=created.projectId as string;let chatted=await cli(dataDir,databasePath,["chat",workspaceId,projectId,"给出下一步"]),data=chatted.data,sessionId=data.sessionId,set=data.candidates,action=set.candidates.find((item:any)=>item.kind==="action");await cli(dataDir,databasePath,["choose",workspaceId,projectId,sessionId,set.id,action.id]);chatted=await cli(dataDir,databasePath,["chat",workspaceId,projectId,"继续",sessionId]);data=chatted.data;action=data.candidates.candidates.find((item:any)=>item.kind==="action");await cli(dataDir,databasePath,["choose",workspaceId,projectId,sessionId,data.candidates.id,action.id]);const approved=await cli(dataDir,databasePath,["approve",workspaceId,projectId,"Reference CLI approval"]);assert.equal(approved.status,"accepted");const report=await cli(dataDir,databasePath,["report",workspaceId,projectId]);assert.equal(report.status.status,"ok");assert.equal(report.status.data.project.status,"scoped");
  const freeOffer=await cli(dataDir,databasePath,["chat",workspaceId,projectId,"更多选项",sessionId]),freeSet=freeOffer.data.candidates,freeResult=await cli(dataDir,databasePath,["choose",workspaceId,projectId,sessionId,freeSet.id,"--free","自由研究输入"]);assert.equal(freeResult.status,"accepted");
  const jobPath=writeJson(dir,"job.json",{name:"CLI queued job",dataRole:"exploration",studyId:null,execution:{kind:"bubblewrap",workspace:dir,command:"/bin/true",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:10000,maxArtifactBytes:10000},priority:0,resumable:true,maxAttempts:1}),job=await cli(dataDir,databasePath,["job-submit",workspaceId,projectId,jobPath]),jobId=job.data.job.id;assert.equal((await cli(dataDir,databasePath,["job-status",workspaceId,projectId,jobId])).data.job.status,"queued");assert.equal((await cli(dataDir,databasePath,["job-cancel",workspaceId,projectId,jobId])).status,"accepted");
  const source=await cli(dataDir,databasePath,["plugin-source-add",workspaceId,"local",plugin,"CLI fixture"]),sourceId=source.data.source.id;await cli(dataDir,databasePath,["plugin-source-refresh",workspaceId,sourceId]);const search=await cli(dataDir,databasePath,["plugin-search",workspaceId,"fixture-skill"]),descriptor=search.data.plugins[0];assert.equal((await cli(dataDir,databasePath,["plugin-inspect",workspaceId,descriptor.descriptorId])).data.inspectionStatus,"inspected");const installation=(await cli(dataDir,databasePath,["plugin-install",workspaceId,projectId,descriptor.descriptorId,descriptor.permissions.join(",")])).data.installation;await cli(dataDir,databasePath,["plugin-enable",workspaceId,projectId,installation.id]);await cli(dataDir,databasePath,["plugin-disable",workspaceId,projectId,installation.id]);
  const pythonCode=`import json,os\nfrom research_sdk import ResearchClient\nc=ResearchClient.connect(os.environ['BASE'],token=os.environ['TOKEN'])\nr=c.query(${JSON.stringify(query("project.status",projectId))})\nprint(json.dumps({'status':r['status'],'project':r['data']['project']['id']}))\n`,python=await runProcess("python3",["-c",pythonCode],{timeoutMs:10000,env:{PATH:process.env.PATH,PYTHONPATH:resolve("python"),BASE:service.address.baseUrl,TOKEN:readFileSync(service.address.tokenFile!,"utf8").trim()}});assert.equal(python.exitCode,0,python.stderr);assert.deepEqual(JSON.parse(python.stdout),{status:"ok",project:projectId});
});

test("service secrets can remain external and unsafe binding or origins fail closed",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-s-security-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));await assert.rejects(()=>startCoreService({databasePath:join(dir,"bad.db"),dataDir:join(dir,"bad"),host:"0.0.0.0"}),/allowRemote/);const secret="s".repeat(64),provider=new MemorySecretProvider({SERVICE_TOKEN:secret}),service=await startCoreService({databasePath:join(dir,"research.db"),dataDir:join(dir,"service"),secretProvider:provider,tokenSecretName:"SERVICE_TOKEN",maxBodyBytes:100});t.after(()=>service.close());assert.equal(service.address.tokenFile,null);assert.equal("token" in JSON.parse(readFileSync(service.address.discoveryFile,"utf8")),false);const client=await ResearchClient.connect({baseUrl:service.address.baseUrl,token:secret});assert.equal((await client.negotiate()).schemaVersion,PUBLIC_SCHEMA_VERSION);const denied=await fetch(`${service.address.baseUrl}/v1/health`,{headers:{authorization:`Bearer ${secret}`,origin:"https://evil.example"}});assert.equal(denied.status,403);const oversized=await fetch(`${service.address.baseUrl}/v1/commands`,{method:"POST",headers:{authorization:`Bearer ${secret}`,"content-type":"application/json"},body:JSON.stringify({payload:"x".repeat(200)})});assert.equal(oversized.status,400);
});

test("schema 15 service audit migration backs up and rolls back atomically",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-s-migration-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));for(const[name,pass]of[["pass",true],["fail",false]]as const){const path=join(dir,`${name}.db`),app=await ResearchApplication.open({databasePath:path});app.close();const raw=new Database(path);raw.pragma("foreign_keys = OFF");raw.pragma("user_version = 14");if(pass){raw.close();const store=await ServiceAuditStore.open(path);assert.ok(store.migrationBackupPath);store.close();const check=new Database(path,{readonly:true});assert.equal(check.pragma("user_version",{simple:true}),15);check.close();}else{const sql=readFileSync(resolve("migrations/014_core_service_audit.sql"),"utf8");assert.throws(()=>applyMigrationTransaction(raw,`${sql}\nCREATE TABLE broken (`));assert.equal(raw.pragma("user_version",{simple:true}),14);assert.equal(raw.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='service_audit_v15'").get(),undefined);raw.close();}}
});

test("TypeScript local client auto-starts a discoverable service",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-s-autostart-")),dataDir=join(dir,"service"),databasePath=join(dir,"research.db");t.after(()=>rmSync(dir,{recursive:true,force:true}));let pid:number|undefined;t.after(()=>{if(pid)try{process.kill(pid,"SIGTERM");}catch{}});const client=await ResearchClient.connectLocal({dataDir,databasePath,serviceEntryPath:resolve("src/service/cli.ts"),timeoutMs:10000}),capabilities=await client.negotiate();assert.equal(capabilities.offline,true);const discovery=JSON.parse(readFileSync(join(dataDir,"core-service.json"),"utf8"));pid=discovery.pid;assert.equal(typeof pid,"number");process.kill(pid!,"SIGTERM");for(let index=0;index<100&&existsSync(join(dataDir,"core-service.json"));index++)await new Promise(resolveDelay=>setTimeout(resolveDelay,20));assert.equal(existsSync(join(dataDir,"core-service.json")),false);pid=undefined;
});

function writeJson(dir:string,name:string,value:unknown):string{const path=join(dir,name);writeFileSync(path,JSON.stringify(value));return path;}
