import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { runProcess } from "../src/adapters/process.js";
import { ScenarioManifestSchema, negotiateScenario } from "../src/public/scenario.js";

const scenarioRoot=resolve("examples/scenarios/fasttext-agnews"),lock=JSON.parse(readFileSync(join(scenarioRoot,"source-lock.json"),"utf8")),manifest=ScenarioManifestSchema.parse(JSON.parse(readFileSync(join(scenarioRoot,"manifest.json"),"utf8")));
function canonical(value:any):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);}

test("T2b Scenario manifest and source lock satisfy public contracts",()=>{const result=negotiateScenario({scenario:manifest,coreSchemaVersion:"1.0.0",approvedPermissions:manifest.permissions,availableExecutors:["bubblewrap"]});assert.equal(result.compatible,true);const{manifestHash,...body}=lock;assert.equal(createHash("sha256").update(canonical(body)).digest("hex"),manifestHash);assert.deepEqual(lock.protocol.seeds,[11,23,47]);assert.equal(lock.data["train.ft"].rows,120000);assert.equal(lock.data["test.ft"].rows,7600);});

test("T2b Python Scenario declares an offline bounded exploration Job",async()=>{const result=await runProcess("python3",[join(scenarioRoot,"scenario.py"),"--job-workspace","/tmp/t2b-public-scenario"],{timeoutMs:5000,env:{PATH:process.env.PATH,PYTHONPATH:resolve("python")}});assert.equal(result.exitCode,0,result.stderr);const job=JSON.parse(result.stdout);assert.equal(job.dataRole,"exploration");assert.equal(job.execution.kind,"bubblewrap");assert.equal(job.resources.gpuCount,0);assert.equal(job.resources.cpuCores,1);assert.equal(job.limits.wallTimeMs,600000);});

test("T2b public Evaluator and Analyzer use model trainings as units",async t=>{const dir=mkdtempSync(join(tmpdir(),"ara-t2b-contract-")),path=join(dir,"result.json");t.after(()=>rmSync(dir,{recursive:true,force:true}));const groups={baseline:{runs:[11,23,47].map((seed,index)=>({seed,accuracy:0.90+index/1000}))},candidate:{runs:[11,23,47].map((seed,index)=>({seed,accuracy:0.91+index/1000}))}};writeFileSync(path,JSON.stringify({...groups,resultHash:"a".repeat(64)}));const result=await runProcess("python3",[join(scenarioRoot,"scenario.py"),"--evaluate",path],{timeoutMs:5000,env:{PATH:process.env.PATH,PYTHONPATH:resolve("python")}});assert.equal(result.exitCode,0,result.stderr);const contracts=JSON.parse(result.stdout);assert.equal(contracts.evaluations.length,6);assert.equal(contracts.analysis.clusterUnit,"independent model training seed pair");assert.ok(Math.abs(contracts.analysis.estimate-0.01)<1e-12);assert.equal(contracts.analysis.sensitivity[0].stable,true);});

test("T2b recorded run proves real training, public Worker execution, and Bundle import",()=>{const report=JSON.parse(readFileSync(resolve("docs/reports/validation/t2b-fasttext-run.json"),"utf8"));assert.equal(report.status,"pass");assert.equal(report.source.manifestHash,lock.manifestHash);assert.equal(report.execution.kind,"new_offline_training_experiment");assert.equal(report.execution.sandbox,"bubblewrap_unshare_net");assert.equal(report.execution.jobStatus,"succeeded");assert.equal(report.experiment.contractEvaluationCount,6);assert.equal(report.experiment.baseline.runs.reduce((sum:number,item:any)=>sum+item.correct,0),20734);assert.equal(report.experiment.candidate.runs.reduce((sum:number,item:any)=>sum+item.correct,0),20955);assert.ok(Math.abs(report.experiment.analysis.meanDifference-0.009692982456140364)<1e-15);assert.equal(report.experiment.analysis.allDifferencesPositive,true);assert.equal(report.experiment.analysis.inference,"descriptive_only");assert.equal(report.bundle.artifactDisposition,"embedded");assert.equal(report.bundle.targetDependencies.artifacts[0].status,"available");assert.deepEqual(report.bundle.importCompatibility.issues.map((item:any)=>item.code),["job_environment_redacted"]);assert.equal(report.assertions.publicServiceOnly,true);assert.equal(report.assertions.noModelFilesRetained,true);});
