import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import Database from "better-sqlite3";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { JobLogListSchema, JobReadModelSchema, PUBLIC_SCHEMA_VERSION, ResearchApplication, type Actor, type JobSpec } from "../src/public/index.js";
import { JobStore } from "../src/infrastructure/db/job-store.js";
import { LocalJobWorker } from "../src/runtime/local-job-worker.js";
import { PiJobRunner } from "../src/runtime/pi-job-runner.js";
import { applyMigrationTransaction } from "../src/infrastructure/db/research-store.js";
import type { BubblewrapSpec } from "../src/adapters/bubblewrap-runner.js";

const user:Actor={id:"user:q",kind:"user"},agent:Actor={id:"agent:q",kind:"agent"};
const base={schemaVersion:PUBLIC_SCHEMA_VERSION,workspaceId:"workspace:q",actor:user,issuedAt:"2026-10-01T00:00:00.000Z"};
const worker={workerId:"worker:local",protocolVersion:"1" as const,executors:["python","bubblewrap","pi"] as Array<"python"|"bubblewrap"|"pi">,capacity:{cpuCores:2,memoryMiB:1024,diskMiB:1024,gpuCount:1},gpuDevices:["0"],leaseDurationMs:200};

async function project(app:ResearchApplication,key:string):Promise<string>{const result=await app.execute({...base,type:"project.create",commandId:`${key}:create`,idempotencyKey:`${key}:create`,projectId:null,payload:{intent:{title:`Q ${key} study`,direction:"Verify persistent scientific jobs, workers, resource limits and confirmation isolation.",domain:"AI/ML",constraints:[],allowedData:["fixture"],prohibitions:["no permission bypass"],profile:"confirmatory",budget:{gpuHours:1,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}}});assert.equal(result.status,"accepted");return result.projectId!;}
function pythonSpec(workspace:string,script:string,overrides:Partial<JobSpec>={}):JobSpec{return{name:"python fixture",dataRole:"exploration",studyId:null,execution:{kind:"python",workspace,script,args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:256,diskMiB:128,gpuCount:0},limits:{wallTimeMs:2000,cpuTimeSeconds:2,maxOutputBytes:100000,maxArtifactBytes:100000},priority:0,resumable:true,maxAttempts:3,...overrides} as JobSpec;}
async function submit(app:ResearchApplication,projectId:string,key:string,spec:JobSpec,confirmationToken:string|null=null,actorOverride:Actor=user){return app.execute({...base,actor:actorOverride,type:"job.submit",commandId:`${key}:submit`,idempotencyKey:`${key}:submit`,projectId,payload:{spec,confirmationToken}});}
async function getJob(app:ResearchApplication,projectId:string,jobId:string){const result=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`job:${jobId}:${Math.random()}`,type:"job.get",workspaceId:base.workspaceId,projectId,actor:user,jobId});assert.equal(result.status,"ok");return JobReadModelSchema.parse(result.data);}
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

test("public worker protocol persists lease, logs and atomically commits artifacts",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-protocol-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await project(app,"protocol"),submitted=await submit(app,projectId,"protocol",pythonSpec(dir,"task.py"));assert.equal(submitted.status,"accepted");const jobId=(submitted.data as any).job.id;
  assert.deepEqual(await app.execute({...base,type:"job.submit",commandId:"protocol:submit",idempotencyKey:"protocol:submit",projectId,payload:{spec:pythonSpec(dir,"task.py"),confirmationToken:null}}),submitted);
  const claimed=await app.worker({type:"worker.claim",requestId:"claim",worker}),lease=(claimed.data as any).lease;assert.equal(claimed.status,"ok");assert.equal(lease.job.id,jobId);assert.equal(lease.allocatedGpuDevices.length,0);
  const logged=await app.worker({type:"worker.log",requestId:"log",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"progress",message:"halfway",data:{fraction:.5}});assert.equal(logged.status,"ok");
  const malformed=await app.worker({type:"worker.complete",requestId:"bad-complete",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,artifacts:[{name:"result",mediaType:"text/plain",contentHash:"bad",bytes:2,uri:"cas:bad"}]});assert.equal(malformed.status,"rejected");assert.equal((await getJob(app,projectId,jobId)).job.status,"running");
  const completed=await app.worker({type:"worker.complete",requestId:"complete",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,artifacts:[{name:"result",mediaType:"text/plain",contentHash:"a".repeat(64),bytes:2,uri:`cas:sha256:${"a".repeat(64)}`}]});assert.equal(completed.status,"ok");const read=await getJob(app,projectId,jobId);assert.equal(read.job.status,"succeeded");assert.equal(read.artifacts.length,1);
  const logs=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"logs",type:"job.logs",workspaceId:base.workspaceId,projectId,actor:user,jobId,fromSequence:1,limit:2}),page=JobLogListSchema.parse(logs.data);assert.equal(page.logs.length,2);assert.ok(page.nextSequence);assert.deepEqual(page.logs.map(item=>item.sequence),[1,2]);
});

test("local Python worker streams output, commits CAS artifacts and classifies timeout",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-python-")),dbPath=join(dir,"research.db"),artifactRoot=join(dir,"artifacts");t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:dbPath});t.after(()=>app.close());const projectId=await project(app,"python");
  writeFileSync(join(dir,"success.py"),'from pathlib import Path\nprint("progress-one")\nPath("result.txt").write_text("verified artifact")\n');
  const successSpec=pythonSpec(dir,"success.py");successSpec.execution={...successSpec.execution,artifactPaths:["result.txt"]};const accepted=await submit(app,projectId,"python-success",successSpec),jobId=(accepted.data as any).job.id,local=app.createLocalWorker({descriptor:worker,artifactRoot,heartbeatIntervalMs:30});await local.runOnce();const result=await getJob(app,projectId,jobId);assert.equal(result.job.status,"succeeded");assert.equal(readFileSync(join(artifactRoot,"sha256",result.artifacts[0]!.contentHash.slice(0,2),result.artifacts[0]!.contentHash.slice(2,4),result.artifacts[0]!.contentHash),"utf8"),"verified artifact");const jobLogs=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"python:logs",type:"job.logs",workspaceId:base.workspaceId,projectId,actor:user,jobId,fromSequence:1,limit:100});assert.equal(JobLogListSchema.parse(jobLogs.data).logs.some(item=>item.message==="progress-one"),true);
  writeFileSync(join(dir,"timeout.py"),"import time\ntime.sleep(2)\n");const timeoutSpec=pythonSpec(dir,"timeout.py");timeoutSpec.limits.wallTimeMs=100;timeoutSpec.limits.cpuTimeSeconds=1;const timed=await submit(app,projectId,"python-timeout",timeoutSpec),timedId=(timed.data as any).job.id;await local.runOnce();const timedResult=await getJob(app,projectId,timedId);assert.equal(timedResult.job.status,"failed");assert.equal(timedResult.job.failureClass,"timeout");const idle=await app.worker({type:"worker.claim",requestId:"python:idle",worker});assert.equal((idle.data as any).lease,null,"timeout must release the resource lease");
});

test("classified failure can be retried with a new attempt and a stale lease cannot mutate it",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-retry-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await project(app,"retry"),submitted=await submit(app,projectId,"retry",pythonSpec(dir,"task.py")),jobId=(submitted.data as any).job.id,first=(await app.worker({type:"worker.claim",requestId:"retry:claim1",worker}).then(result=>(result.data as any).lease));
  const failed=await app.worker({type:"worker.fail",requestId:"retry:fail",jobId,attempt:first.attempt,workerId:worker.workerId,leaseToken:first.leaseToken,failureClass:"data",message:"fixture data mismatch"});assert.equal(failed.status,"ok");assert.equal((await getJob(app,projectId,jobId)).job.failureClass,"data");
  const retried=await app.execute({...base,type:"job.retry",commandId:"retry:command",idempotencyKey:"retry:command",projectId,payload:{jobId}});assert.equal(retried.status,"accepted");const second=(await app.worker({type:"worker.claim",requestId:"retry:claim2",worker}).then(result=>(result.data as any).lease));assert.equal(second.attempt,2);
  const stale=await app.worker({type:"worker.log",requestId:"retry:stale",jobId,attempt:first.attempt,workerId:worker.workerId,leaseToken:first.leaseToken,stream:"system",message:"stale"});assert.equal(stale.status,"rejected");assert.equal(stale.error?.code,"CONFLICT");
  const completed=await app.worker({type:"worker.complete",requestId:"retry:complete",jobId,attempt:second.attempt,workerId:worker.workerId,leaseToken:second.leaseToken,artifacts:[]});assert.equal(completed.status,"ok");assert.equal((await getJob(app,projectId,jobId)).job.status,"succeeded");
});

test("cancellation reaches the running process and releases its lease",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-cancel-")),dbPath=join(dir,"research.db");t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:dbPath});t.after(()=>app.close());const projectId=await project(app,"cancel");writeFileSync(join(dir,"slow.py"),"import time\nprint('started',flush=True)\ntime.sleep(10)\n");const submitted=await submit(app,projectId,"cancel",pythonSpec(dir,"slow.py")),jobId=(submitted.data as any).job.id,store=await JobStore.open(dbPath);t.after(()=>store.close());const local=new LocalJobWorker(store,worker,{artifactRoot:join(dir,"artifacts"),heartbeatIntervalMs:20}),running=local.runOnce();for(let index=0;index<100&&(await getJob(app,projectId,jobId)).job.status!=="running";index++)await wait(10);const cancelled=await app.execute({...base,type:"job.cancel",commandId:"cancel:command",idempotencyKey:"cancel:command",projectId,payload:{jobId}});assert.equal(cancelled.status,"accepted");await running;const result=await getJob(app,projectId,jobId);assert.equal(result.job.status,"cancelled");assert.equal(result.job.failureClass,"cancelled");assert.equal(store.claim(worker),null);
});

test("expired leases recover after restart and resource capacity prevents over-allocation",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-recover-")),dbPath=join(dir,"research.db");t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:dbPath}),projectId=await project(app,"recover");for(const key of ["one","two"])await submit(app,projectId,`recover-${key}`,pythonSpec(dir,"task.py",{resources:{cpuCores:2,memoryMiB:1024,diskMiB:1024,gpuCount:1}}));app.close();let store=await JobStore.open(dbPath),now=new Date(Date.now()+1000),first=store.claim(worker,now)!;assert.equal(first.allocatedGpuDevices[0],"0");assert.equal(store.claim(worker,now),null,"active lease must consume all advertised resources");store.close();store=await JobStore.open(dbPath);const recovered=store.recoverExpired(new Date(now.getTime()+201));assert.equal(recovered.length,1);assert.equal(recovered[0]!.status,"queued");const resumed=store.claim(worker,new Date(now.getTime()+202))!;assert.equal(resumed.job.id,first.job.id);assert.equal(resumed.attempt,2);store.close();
});

test("confirmation capability is reserved without persisting the secret and opens only inside a bubblewrap lease",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-confirm-")),dbPath=join(dir,"research.db"),sealed=join(dir,"sealed");mkdirSync(sealed);t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:dbPath});t.after(()=>app.close());const projectId=await project(app,"confirmation"),token="confirmation-secret-token-value-123456",tokenHash=createHash("sha256").update(token).digest("hex"),now=new Date().toISOString(),study={id:"study:q",programId:projectId,protocolId:"protocol:q",hypothesisSetId:"hypotheses:q",evidenceMapId:"evidence:q",status:"confirmation_ready",experimentalUnit:"independent run",design:"paired_repeated_run",reliabilityPolicy:"fact_bound_v1",confirmationExecutionPolicy:"bubblewrap_required",units:[{id:"u1",kind:"run",clusterId:null,attributes:{},legacySeed:null},{id:"u2",kind:"run",clusterId:null,attributes:{},legacySeed:null}],seeds:[],blockingFactors:[],nuisanceFactors:[],randomizationSeed:1,contentHash:"b".repeat(64),createdAt:now,updatedAt:now},freeze={id:"freeze:q",studyId:"study:q",searchRunId:"search:q",nodeId:"node:q",nodeSignature:"signature",protocolHash:"c".repeat(64),analysisPlanHash:"d".repeat(64),codeHash:"e".repeat(64),configHash:"f".repeat(64),dataManifestHash:"1".repeat(64),status:"approved",createdAt:now,approvedAt:now,approvedBy:"user:q"},confirmation={id:"token:q",studyId:"study:q",candidateFreezeId:"freeze:q",tokenHash,status:"issued",issuedAt:now,consumedAt:null,runId:null},role={id:"role:q",studyId:"study:q",role:"confirmation",path:sealed,manifestHash:"2".repeat(64),sealed:true,createdAt:now};const raw=new Database(dbPath);raw.pragma("foreign_keys = OFF");raw.prepare("INSERT INTO studies(id,program_id,protocol_id,hypothesis_set_id,evidence_map_id,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(study.id,study.programId,study.protocolId,study.hypothesisSetId,study.evidenceMapId,study.status,JSON.stringify(study),study.contentHash,now,now);raw.prepare("INSERT INTO candidate_freezes(id,study_id,search_run_id,node_id,status,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").run(freeze.id,study.id,freeze.searchRunId,freeze.nodeId,freeze.status,JSON.stringify(freeze),now);raw.prepare("INSERT INTO confirmation_tokens(id,study_id,candidate_freeze_id,token_hash,status,payload_json,issued_at,consumed_at) VALUES(?,?,?,?,?,?,?,NULL)").run(confirmation.id,study.id,freeze.id,tokenHash,"issued",JSON.stringify(confirmation),now);raw.prepare("INSERT INTO study_data_roles(id,study_id,role,manifest_hash,sealed,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").run(role.id,study.id,role.role,role.manifestHash,1,JSON.stringify(role),now);raw.close();
  const spec:JobSpec={name:"sealed confirmation",dataRole:"confirmation",studyId:study.id,execution:{kind:"bubblewrap",workspace:dir,command:"/bin/true",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:10000,maxArtifactBytes:10000},priority:0,resumable:true,maxAttempts:2};const denied=await submit(app,projectId,"confirm-agent",spec,token,agent);assert.equal(denied.status,"rejected");assert.equal(denied.error?.code,"FORBIDDEN");const wrong=await submit(app,projectId,"confirm-wrong",spec,"x".repeat(32));assert.equal(wrong.status,"rejected");const accepted=await submit(app,projectId,"confirm-user",spec,token);assert.equal(accepted.status,"accepted");assert.equal(JSON.stringify(accepted).includes(token),false,"command result must not expose capability secret");const duplicate=await submit(app,projectId,"confirm-duplicate",spec,token);assert.equal(duplicate.status,"rejected");assert.equal(duplicate.error?.code,"CONFLICT");
  const store=await JobStore.open(dbPath);t.after(()=>store.close());let captured:BubblewrapSpec|undefined;const local=new LocalJobWorker(store,worker,{artifactRoot:join(dir,"artifacts"),bubblewrapRunner:async input=>{captured=input;return{stdout:"",stderr:"",exitCode:0,timedOut:false,cancelled:false,durationMs:1};}});await local.runOnce();assert.deepEqual(captured?.readOnlyMounts,[{source:sealed,target:"/data/confirmation"}]);const readonly=new Database(dbPath,{readonly:true}),tokenRow=readonly.prepare("SELECT status,payload_json FROM confirmation_tokens WHERE id=?").get(confirmation.id) as any;readonly.close();assert.equal(tokenRow.status,"consumed");assert.equal(JSON.parse(tokenRow.payload_json).runId,(accepted.data as any).job.id);
});

test("Pi adapter forwards SDK lifecycle events and aborts through AgentSession",async()=>{
  let listener:(event:any)=>void=()=>{},aborted=false,resolvePrompt:()=>void=()=>{};const fake={sessionFile:"/tmp/pi-session.jsonl",messages:[{role:"user"}],subscribe(fn:(event:any)=>void){listener=fn;return()=>{};},async prompt(){listener({type:"agent_start"});listener({type:"message_update",assistantMessageEvent:{type:"text_delta",delta:"hello"}});await new Promise<void>(resolve=>{resolvePrompt=resolve;setTimeout(resolve,30);});listener({type:"agent_end",messages:[],willRetry:false});},async abort(){aborted=true;resolvePrompt();},async waitForIdle(){},dispose(){}};const runner=new PiJobRunner(async()=>fake as any),controller=new AbortController(),output:Array<{stream:string;message:string}>=[],lease={job:{spec:{execution:{kind:"pi",prompt:"work",sessionFile:null,allowedTools:[]}}}} as any,pending=runner.run(lease,controller.signal,(stream,message)=>output.push({stream,message}));setTimeout(()=>controller.abort(),5);await assert.rejects(pending,/cancelled/);assert.equal(aborted,true);assert.equal(output.some(item=>item.message==="hello"),true);
});

test("schema 13 Job migration backs up and rolls back atomically",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-q-migration-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));for(const [name,shouldPass] of [["pass",true],["fail",false]] as const){const path=join(dir,`${name}.db`),app=await ResearchApplication.open({databasePath:path});app.close();const raw=new Database(path);raw.pragma("foreign_keys = OFF");for(const table of ["job_confirmation_grants_v15","job_artifacts_v15","job_logs_v15","job_leases_v15","job_attempts_v15","research_jobs_v15"])raw.exec(`DROP TABLE ${table}`);raw.pragma("user_version = 12");if(shouldPass){raw.close();const store=await JobStore.open(path);assert.ok(store.migrationBackupPath);store.close();const check=new Database(path,{readonly:true});assert.equal(check.pragma("user_version",{simple:true}),13);check.close();}else{const sql=readFileSync(resolve("migrations/012_job_worker.sql"),"utf8");assert.throws(()=>applyMigrationTransaction(raw,`${sql}\nCREATE TABLE broken (`));assert.equal(raw.pragma("user_version",{simple:true}),12);assert.equal(raw.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='research_jobs_v15'").get(),undefined);raw.close();}}
});
