import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { runProcess } from "../src/adapters/process.js";
import { ScenarioManifestSchema, negotiateScenario } from "../src/public/scenario.js";

const scenarioRoot=resolve("examples/scenarios/mllm-routing"),sourceRoot=resolve(process.env.MLLM_RESEARCH_ROOT??"/data0/linsihan/mllm-routing-generalization"),lock=JSON.parse(readFileSync(join(scenarioRoot,"source-lock.json"),"utf8")),manifest=ScenarioManifestSchema.parse(JSON.parse(readFileSync(join(scenarioRoot,"manifest.json"),"utf8")));
function canonical(value:any):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);}

test("T2a Scenario manifest is compatible with the public SDK",()=>{const result=negotiateScenario({scenario:manifest,coreSchemaVersion:"1.0.0",approvedPermissions:manifest.permissions,availableExecutors:["bubblewrap"]});assert.equal(result.compatible,true);const{manifestHash,...body}=lock;assert.equal(createHash("sha256").update(canonical(body)).digest("hex"),manifestHash);assert.equal(lock.sourceCommit,"a954fc66fa44854df37fc5535e97380793eb4648");assert.equal(lock.images.length,15);assert.equal(lock.files.length,10);});

test("T2a Python Scenario adapter loads only the generated public SDK",async()=>{const result=await runProcess("python3",[join(scenarioRoot,"scenario.py"),"--job-workspace","/tmp/t2a-public-scenario"],{timeoutMs:5000,env:{PATH:process.env.PATH,PYTHONPATH:resolve("python")}});assert.equal(result.exitCode,0,result.stderr);const job=JSON.parse(result.stdout);assert.equal(job.execution.kind,"bubblewrap");assert.equal(job.resources.gpuCount,0);assert.equal(job.limits.maxKnownCostUsd,undefined);});

test("T2a evaluator reanalyzes locked real multimodal artifacts without model inference",async t=>{if(!existsSync(join(sourceRoot,"results/final-analysis.json"))){t.skip("frozen MLLM research workspace is unavailable");return;}const dir=mkdtempSync(join(tmpdir(),"ara-t2a-eval-")),input=join(dir,"input"),output=join(dir,"evaluation.json");t.after(()=>rmSync(dir,{recursive:true,force:true}));for(const item of [...lock.files,...lock.images]){const from=join(sourceRoot,item.path),to=join(input,item.path);mkdirSync(dirname(to),{recursive:true});copyFileSync(from,to);}const result=await runProcess("python3",[join(scenarioRoot,"evaluate_frozen.py"),"--lock",join(scenarioRoot,"source-lock.json"),"--input",input,"--output",output],{timeoutMs:120000,env:{PATH:process.env.PATH}});assert.equal(result.exitCode,0,result.stderr);const evaluation=JSON.parse(readFileSync(output,"utf8"));assert.equal(evaluation.executionKind,"artifact_reanalysis_no_model_inference");assert.equal(evaluation.sampleEvaluation.routerAccuracy,1);assert.equal(evaluation.sampleEvaluation.rowCount,45);assert.equal(evaluation.frozenResult.nUnits,80);assert.ok(Math.abs(evaluation.frozenResult.estimate-0.04074074074074074)<1e-15);assert.match(evaluation.claimBoundary,/RIO-format transport only/);});

test("T2a recorded run proves public service execution and Bundle v2 import",()=>{const report=JSON.parse(readFileSync(resolve("docs/reports/validation/t2a-mllm-run.json"),"utf8"));assert.equal(report.status,"pass");assert.equal(report.source.commit,lock.sourceCommit);assert.equal(report.source.manifestHash,lock.manifestHash);assert.equal(report.execution.kind,"artifact_reanalysis_no_model_inference");assert.equal(report.execution.sandbox,"bubblewrap_unshare_net");assert.equal(report.execution.artifactHash,"809c7cb6d76210abd8791d2471671d2d0f9b1c88e06f8ff4819dc45e0d47bd1b");assert.equal(report.execution.jobStatus,"succeeded");assert.ok(report.execution.jobLogCount>0);assert.ok(report.execution.researchEventCount>0);assert.ok(report.execution.serviceAuditCount>0);assert.equal(report.bundle.artifactDisposition,"embedded");assert.equal(report.bundle.targetDependencies.artifacts[0].status,"available");assert.deepEqual(report.bundle.importCompatibility.issues.map((item:any)=>item.code),["job_environment_redacted"]);assert.equal(report.assertions.publicServiceOnly,true);assert.equal(report.assertions.noNewModelInference,true);});
