import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { JobSpecSchema,PlatformCapabilitySnapshotSchema,PortableRelativePathSchema,PUBLIC_SCHEMA_VERSION,ResearchApplication,type Actor } from "../src/public/index.js";
import { detectPlatformCapabilities } from "../src/runtime/platform-capabilities.js";
import { processTreeTerminationPlan } from "../src/runtime/process-control.js";

const actor:Actor={id:"user:platform",kind:"user"};let sequence=0,workspaceId="workspace:platform";const context=(projectId:string|null)=>({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:`platform-${++sequence}`,idempotencyKey:`platform-${sequence}`,workspaceId,projectId,actor,issuedAt:"2026-10-02T00:00:00.000Z"});
const probe=(available:Set<string>)=>(command:string,_args:string[])=>({available:available.has(command),version:available.has(command)?`${command} fixture`:null});
function snapshot(os:"linux"|"darwin"|"win32",arch:string){return detectPlatformCapabilities({platform:os,arch,now:"2026-10-02T00:00:00.000Z",probe:probe(new Set(os==="linux"?["python3","bwrap","prlimit","ssh","sftp"]:os==="win32"?["python","ssh","sftp"]:["python3","ssh","sftp"]))});}
async function scoped(app:ResearchApplication){const created=await app.execute({...context(null),type:"project.create",payload:{intent:{title:"Platform scheduler fixture",direction:"Verify platform-aware scheduling without silently weakening the requested executor.",domain:"systems",constraints:["public API"],allowedData:["fixture"],prohibitions:["no executor fallback"],profile:"smoke",budget:{gpuHours:0.001,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}}}),projectId=created.projectId!,proposed=await app.execute({...context(projectId),type:"question.propose",payload:{question:{question:"Does the scheduler lease jobs only to workers satisfying declared platform capabilities?",rationale:"Cross-platform clients must wait for a qualified Linux worker rather than weaken sandbox requirements.",targetPopulation:"Registered research workers",intervention:"Platform capability matching",comparator:"Executor-name-only matching",primaryOutcome:"Correct lease eligibility",scope:"One synthetic Bubblewrap scheduling fixture",sourceIds:[]}}}),questionId=(proposed.data as any).question.id;await app.execute({...context(projectId),type:"question.select",payload:{questionId}});await app.execute({...context(projectId),type:"scope.approve",payload:{note:"Platform fixture."}});return projectId;}
const worker=(id:string,platform:any)=>({workerId:id,protocolVersion:"1",executors:["python","bubblewrap"],capacity:{cpuCores:2,memoryMiB:1024,diskMiB:1024,gpuCount:0},gpuDevices:[],leaseDurationMs:5000,platform});

test("platform detection reports explicit availability instead of emulating Linux",()=>{const linux=snapshot("linux","x64"),mac=snapshot("darwin","arm64"),windows=snapshot("win32","x64");assert.equal(linux.executors.bubblewrap.status,"available");for(const value of [mac,windows]){assert.equal(value.executors.bubblewrap.status,"unavailable");assert.match(value.executors.bubblewrap.reason!,/Linux-only/);assert.equal(value.ssh.client.status,"available");}assert.equal(windows.processGroups.status,"degraded");assert.equal(mac.filesystem.caseSensitive,null);for(const value of [linux,mac,windows])PlatformCapabilitySnapshotSchema.parse(value);});

test("scheduler waits for a platform-qualified worker without executor fallback",async t=>{const dir=mkdtempSync(join(tmpdir(),"ara-platform-scheduler-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await scoped(app),spec={name:"Linux sandbox requirement",dataRole:"exploration",studyId:null,execution:{kind:"bubblewrap",workspace:dir,command:"/bin/true",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:1000,maxArtifactBytes:1000},priority:0,resumable:true,maxAttempts:1,platformConstraints:{os:["linux"],arch:[],requiresSandbox:true,storageModes:["local"]}},submitted=await app.execute({...context(projectId),type:"job.submit",payload:{spec,confirmationToken:null}}),jobId=(submitted.data as any).job.id;for(const [id,platform] of [["mac",snapshot("darwin","arm64")],["windows",snapshot("win32","x64")]] as const){const result=await app.worker({type:"worker.claim",requestId:`claim-${id}`,worker:worker(`worker:${id}`,platform)});assert.equal((result.data as any).lease,null);}const qualified=worker("worker:linux",snapshot("linux","x64")),claim=await app.worker({type:"worker.claim",requestId:"claim-linux",worker:qualified}),lease=(claim.data as any).lease;assert.equal(lease.job.id,jobId);assert.equal(lease.job.spec.execution.kind,"bubblewrap");await app.worker({type:"worker.complete",requestId:"complete-linux",jobId,attempt:lease.attempt,workerId:qualified.workerId,leaseToken:lease.leaseToken,artifacts:[]});});

test("portable paths allow spaces and reject drive, UNC, traversal, absolute, and newline paths",()=>{assert.equal(PortableRelativePathSchema.safeParse("output dir/result.json").success,true);for(const value of ["../secret","C:\\secret.txt","\\\\server\\share","/etc/passwd","output//result","output\nresult"])assert.equal(PortableRelativePathSchema.safeParse(value).success,false,value);const base={name:"path fixture",dataRole:"exploration",studyId:null,resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:1000,maxArtifactBytes:1000},priority:0,resumable:true,maxAttempts:1};assert.equal(JobSpecSchema.safeParse({...base,execution:{kind:"python",workspace:"C:\\Research Workspace",script:"scripts/run.py",args:[],env:{},artifactPaths:["output dir/result.json"]}}).success,true);});

test("process-tree termination plans are argument-safe on Windows and POSIX",()=>{assert.deepEqual(processTreeTerminationPlan(42,"SIGKILL","win32"),{command:"taskkill",args:["/pid","42","/t","/f"],processGroup:false});assert.deepEqual(processTreeTerminationPlan(42,"SIGTERM","linux"),{command:"process.kill",args:["-42","SIGTERM"],processGroup:true});});
