import assert from "node:assert/strict";
import Database from "better-sqlite3";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { hashPayload } from "../src/domain/research.js";
import { ProjectStore } from "../src/infrastructure/db/project-store.js";
import { applyMigrationTransaction } from "../src/infrastructure/db/research-store.js";
import {
  PUBLIC_SCHEMA_VERSION, ProjectEventListSchema, ProjectStatusReadModelSchema, PublicProjectBundleV1Schema,
  ResearchApplication, type Actor,
} from "../src/public/index.js";

const actor:Actor={id:"user:o-stage",kind:"user",displayName:"O stage tester"};
const base={schemaVersion:PUBLIC_SCHEMA_VERSION,workspaceId:"workspace:o",actor,issuedAt:"2026-10-01T00:00:00.000Z"};
const intent={title:"Persistent project fixture",direction:"Verify append-only project events, branches, projections and portable bundles.",domain:"AI/ML",constraints:["deterministic"],allowedData:["fixture"],prohibitions:["no silent replay"],profile:"confirmatory" as const,budget:{gpuHours:1,wallHours:2,diskGiB:1,modelCalls:2,knownCostUsd:0}};

async function scopedProject(application:ResearchApplication){
  const create=await application.execute({...base,type:"project.create",commandId:"o:create",idempotencyKey:"o-create",projectId:null,payload:{intent}}),projectId=create.projectId!;
  const proposed=await application.execute({...base,type:"question.propose",commandId:"o:question",idempotencyKey:"o-question",projectId,payload:{question:{question:"Does persistent public state survive process restarts without bypassing research gates?",rationale:"A reusable kernel needs durable commands and projections while preserving the existing scientific state machine.",targetPopulation:"Self-hosted research projects",intervention:"Persistent event-backed public facade",comparator:"Process-local compatibility facade",primaryOutcome:"State and event consistency",scope:"One deterministic scope-stage fixture",sourceIds:[]}}});
  const questionId=(proposed.data as{question:{id:string}}).question.id;
  await application.execute({...base,type:"question.select",commandId:"o:select",idempotencyKey:"o-select",projectId,payload:{questionId}});
  await application.execute({...base,type:"scope.approve",commandId:"o:scope",idempotencyKey:"o-scope",projectId,payload:{note:"O-stage fixture approval."}});
  return{projectId,create,proposed};
}

test("O public flow persists events, idempotency, projection and fork lineage",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-flow-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"research.db"),app=await ResearchApplication.open({databasePath:path}),flow=await scopedProject(app),projectId=flow.projectId;
  const eventResult=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:events",type:"project.events",workspaceId:base.workspaceId,projectId,actor,fromSequence:1,limit:100}),events=ProjectEventListSchema.parse(eventResult.data);
  assert.deepEqual(events.events.map(item=>item.type),["project.created","question.proposed","question.selected","scope.approved"]);
  assert.deepEqual(events.events.map(item=>item.sequence),[1,2,3,4]);
  assert.equal(events.nextSequence,null);
  const page=ProjectEventListSchema.parse((await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:event-page",type:"project.events",workspaceId:base.workspaceId,projectId,actor,fromSequence:2,limit:2})).data);assert.deepEqual(page.events.map(item=>item.sequence),[2,3]);assert.equal(page.nextSequence,4);
  const status=ProjectStatusReadModelSchema.parse((await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:status",type:"project.status",workspaceId:base.workspaceId,projectId,actor})).data);
  assert.equal(status.project.status,"scoped");assert.equal(status.persistence.lastEventSequence,4);assert.equal(status.persistence.rootProjectId,projectId);

  const fork=await app.execute({...base,type:"project.fork",commandId:"o:fork",idempotencyKey:"o-fork",projectId,payload:{branchName:"alternative",reason:"Preserve an independent alternative research direction."}});assert.equal(fork.status,"accepted");assert.equal(fork.eventIds.length,2);const childId=(fork.data as{project:{id:string}}).project.id,child=ProjectStatusReadModelSchema.parse((await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:child",type:"project.status",workspaceId:base.workspaceId,projectId:childId,actor})).data);assert.equal(child.persistence.parentProjectId,projectId);assert.equal(child.persistence.rootProjectId,projectId);assert.equal(child.persistence.branchName,"alternative");assert.equal(child.persistence.eventCount,1);
  app.close();

  const reopened=await ResearchApplication.open({databasePath:path}),replay=await reopened.execute({...base,type:"question.propose",commandId:"o:question",idempotencyKey:"o-question",projectId,payload:{question:{question:"Does persistent public state survive process restarts without bypassing research gates?",rationale:"A reusable kernel needs durable commands and projections while preserving the existing scientific state machine.",targetPopulation:"Self-hosted research projects",intervention:"Persistent event-backed public facade",comparator:"Process-local compatibility facade",primaryOutcome:"State and event consistency",scope:"One deterministic scope-stage fixture",sourceIds:[]}}});assert.deepEqual(replay,flow.proposed);const after=ProjectEventListSchema.parse((await reopened.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:events-after",type:"project.events",workspaceId:base.workspaceId,projectId,actor,fromSequence:1,limit:100})).data);assert.equal(after.events.length,5,"fork adds one parent event but replay adds none");reopened.close();

  const store=await ProjectStore.open(path);assert.deepEqual(store.auditProject(projectId),{status:"pass",issues:[]});assert.deepEqual(store.auditProject(childId),{status:"pass",issues:[]});store.close();
});

test("scope-stage bundle verifies hashes and imports into another instance",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-bundle-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const sourcePath=join(dir,"source.db"),source=await ResearchApplication.open({databasePath:sourcePath}),{projectId}=await scopedProject(source),bundleResult=await source.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:bundle",type:"project.bundle",workspaceId:base.workspaceId,projectId,actor,bundleVersion:"1",artifactPolicy:"metadata",maxEmbeddedBytes:1}),bundle=PublicProjectBundleV1Schema.parse(bundleResult.data);source.close();
  const tampered=structuredClone(bundle);tampered.project.branchName="tampered";const target=await ResearchApplication.open({databasePath:join(dir,"target.db")}),bad=await target.execute({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:"o:bad-import",idempotencyKey:"o-bad-import",workspaceId:"workspace:imported",projectId:null,actor,issuedAt:base.issuedAt,type:"project.import",payload:{bundle:tampered}});assert.equal(bad.status,"rejected");assert.equal(bad.error?.code,"CONFLICT");const imported=await target.execute({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:"o:import",idempotencyKey:"o-import",workspaceId:"workspace:imported",projectId:null,actor,issuedAt:base.issuedAt,type:"project.import",payload:{bundle}});assert.equal(imported.status,"accepted");assert.equal(imported.projectId,projectId);assert.equal((imported.data as{eventCount:number}).eventCount,bundle.events.length+1);const status=ProjectStatusReadModelSchema.parse((await target.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"o:imported-status",type:"project.status",workspaceId:"workspace:imported",projectId,actor})).data);assert.equal(status.project.status,"scoped");assert.equal(status.questions.some(item=>item.status==="selected"),true);target.close();
  const store=await ProjectStore.open(join(dir,"target.db"));assert.equal(store.events(projectId).at(-1)?.type,"project.imported");assert.deepEqual(store.auditProject(projectId),{status:"pass",issues:[]});store.close();
});

function createV10(path:string):Database.Database{const db=new Database(path);db.pragma("foreign_keys = OFF");for(const name of ["003_research_protocol.sql","003b_research_cognitive_objects.sql","004_evidence_synthesis.sql","005_study_analysis.sql","006_claim_review_decision.sql","007_reliability_foundations.sql","008_enforced_reliability_gates.sql","009_scientific_decisions.sql"])db.exec(readFileSync(resolve("migrations",name),"utf8"));return db;}

test("schema 11 migration backs up, adopts legacy projects and rolls back on failure",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-migration-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"migrated.db"),raw=createV10(path),now=new Date().toISOString(),program={id:"legacy-project",title:"Legacy project",direction:"A sufficiently detailed legacy research direction.",domain:"AI/ML",constraints:[],allowedData:[],prohibitions:[],profile:"exploratory",budget:{gpuHours:1,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0},status:"draft",contentHash:"a".repeat(64),derivedFromId:null,createdAt:now,updatedAt:now};raw.prepare("INSERT INTO research_programs(id,profile,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(program.id,program.profile,program.status,JSON.stringify(program),program.contentHash,now,now);raw.close();const store=await ProjectStore.open(path);assert.ok(store.migrationBackupPath);const adopted=store.adoptLegacyProject({projectId:program.id,workspaceId:"workspace:legacy",actor:{id:"user:legacy",kind:"user"},schemaVersion:PUBLIC_SCHEMA_VERSION});assert.equal(adopted.workspaceId,"workspace:legacy");assert.equal(store.events(program.id)[0]?.type,"project.adopted");assert.deepEqual(store.auditProject(program.id),{status:"pass",issues:[]});store.close();const migrated=new Database(path,{readonly:true});assert.equal(migrated.pragma("user_version",{simple:true}),11);migrated.close();

  const failed=createV10(join(dir,"failed.db")),migration=readFileSync(resolve("migrations/010_project_events.sql"),"utf8");assert.throws(()=>applyMigrationTransaction(failed,`${migration}\nCREATE TABLE broken (`));assert.equal(failed.pragma("user_version",{simple:true}),10);assert.equal(failed.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='workspaces'").get(),undefined);failed.close();
});

test("pending command receipts survive restart and block uncertain replay",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-pending-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"research.db"),bootstrap=await ResearchApplication.open({databasePath:path});bootstrap.close();let store=await ProjectStore.open(path);store.prepareCommand({workspaceId:"workspace:pending",projectId:null,commandId:"pending-command",idempotencyKey:"pending-key",commandHash:"b".repeat(64),actor});store.close();store=await ProjectStore.open(path);assert.equal(store.pendingReceipts("workspace:pending").length,1);assert.throws(()=>store.prepareCommand({workspaceId:"workspace:pending",projectId:null,commandId:"retry-command",idempotencyKey:"pending-key",commandHash:"b".repeat(64),actor}),/in doubt/);store.close();
});

test("post-domain event failure remains in doubt and cannot duplicate mutation",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-saga-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"research.db"),app=await ResearchApplication.open({databasePath:path}),created=await app.execute({...base,type:"project.create",commandId:"saga:create",idempotencyKey:"saga-create",projectId:null,payload:{intent}}),projectId=created.projectId!,raw=new Database(path);raw.exec("CREATE TRIGGER fail_question_event BEFORE INSERT ON research_events_v15 WHEN NEW.event_type='question.proposed' BEGIN SELECT RAISE(FAIL,'injected event failure'); END");raw.close();const command={...base,type:"question.propose" as const,commandId:"saga:question",idempotencyKey:"saga-question",projectId,payload:{question:{question:"Does an event persistence failure block uncertain command replay without duplicating domain state?",rationale:"A fail-closed saga must preserve the mutation and expose an in-doubt receipt instead of retrying silently.",targetPopulation:"Persistent public commands",intervention:"Injected event insertion failure",comparator:"Silent automatic retry",primaryOutcome:"Single domain mutation",scope:"One fault-injected public command",sourceIds:[]}}},failed=await app.execute(command);assert.equal(failed.status,"rejected");assert.equal(failed.error?.code,"CONFLICT");assert.match(failed.error!.message,/in doubt/);const retry=await app.execute(command);assert.equal(retry.status,"rejected");assert.equal(retry.error?.code,"CONFLICT");const status=ProjectStatusReadModelSchema.parse((await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"saga:status",type:"project.status",workspaceId:base.workspaceId,projectId,actor})).data);assert.equal(status.questions.length,1,"domain mutation is retained exactly once");app.close();const store=await ProjectStore.open(path);assert.equal(store.pendingReceipts(base.workspaceId).filter(item=>item.commandId==="saga:question").length,1);assert.equal(store.events(projectId).length,1,"failed event was never appended");store.close();
});

test("event reader upcasts known legacy envelopes and rejects unknown versions",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-upcast-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"research.db"),app=await ResearchApplication.open({databasePath:path}),created=await app.execute({...base,type:"project.create",commandId:"upcast:create",idempotencyKey:"upcast-create",projectId:null,payload:{intent}}),projectId=created.projectId!;app.close();const raw=new Database(path),payload={schemaVersion:"0.9.0",eventId:"legacy-event",type:"legacy.note",workspaceId:base.workspaceId,projectId,sequence:2,actorId:actor.id,actorKind:actor.kind,causationId:"legacy-cause",correlationId:"legacy-correlation",occurredAt:new Date().toISOString(),payloadHash:"0".repeat(64),payload:{note:"legacy"}};raw.prepare("INSERT INTO research_events_v15(event_id,workspace_id,project_id,sequence,event_type,schema_version,actor_id,actor_kind,causation_id,correlation_id,payload_json,payload_hash,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(payload.eventId,payload.workspaceId,payload.projectId,payload.sequence,payload.type,payload.schemaVersion,payload.actorId,payload.actorKind,payload.causationId,payload.correlationId,JSON.stringify(payload),payload.payloadHash,payload.occurredAt);raw.close();let store=await ProjectStore.open(path);const legacy=store.events(projectId)[1]!;assert.equal(legacy.schemaVersion,PUBLIC_SCHEMA_VERSION);assert.equal(legacy.actor.id,actor.id);store.close();const corrupt=new Database(path),unknown={...payload,eventId:"future-event",sequence:3,schemaVersion:"9.0.0"};corrupt.prepare("INSERT INTO research_events_v15(event_id,workspace_id,project_id,sequence,event_type,schema_version,actor_id,actor_kind,causation_id,correlation_id,payload_json,payload_hash,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(unknown.eventId,unknown.workspaceId,unknown.projectId,unknown.sequence,unknown.type,unknown.schemaVersion,unknown.actorId,unknown.actorKind,unknown.causationId,unknown.correlationId,JSON.stringify(unknown),unknown.payloadHash,unknown.occurredAt);corrupt.close();store=await ProjectStore.open(path);assert.throws(()=>store.events(projectId),/No event upcaster/);store.close();
});

test("projection audit detects corruption and deterministic rebuild repairs it",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-o-projection-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,"research.db"),app=await ResearchApplication.open({databasePath:path}),{projectId}=await scopedProject(app);app.close();const raw=new Database(path),row=raw.prepare("SELECT payload_json FROM project_projections_v15 WHERE project_id=?").get(projectId) as{payload_json:string},payload=JSON.parse(row.payload_json);payload.lastSequence=0;raw.prepare("UPDATE project_projections_v15 SET payload_json=? WHERE project_id=?").run(JSON.stringify(payload),projectId);raw.close();const store=await ProjectStore.open(path);assert.equal(store.auditProject(projectId).status,"fail");store.rebuildProjection(projectId);assert.deepEqual(store.auditProject(projectId),{status:"pass",issues:[]});store.close();
});
