import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { PUBLIC_SCHEMA_VERSION, ResearchApplication, type Actor } from "../src/public/index.js";

const actor:Actor={id:"user:capability",kind:"user"};let seq=0;
const base={schemaVersion:PUBLIC_SCHEMA_VERSION,workspaceId:"workspace:capability",actor,issuedAt:"2026-10-02T00:00:00.000Z"};
function command(projectId:string|null,type:string,payload:any){return{...base,commandId:`cap-${++seq}`,idempotencyKey:`cap-${seq}`,projectId,type,payload};}
async function project(app:ResearchApplication){const created=await app.execute(command(null,"project.create",{intent:{title:"Scientific capability fixture",direction:"Verify all public scientific capability interfaces and adversarial gates.",domain:"research methods",constraints:["public only"],allowedData:["fixtures"],prohibitions:["no hidden stores"],profile:"smoke",budget:{gpuHours:0.001,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}})),projectId=created.projectId!,proposed=await app.execute(command(projectId,"question.propose",{question:{question:"Do public scientific capability interfaces preserve their declared correctness gates?",rationale:"Independent clients need stable scientific operations without importing internal stores or workflows.",targetPopulation:"Public Core Service clients",intervention:"Versioned capability invocation",comparator:"Unavailable internal-only access",primaryOutcome:"Expected acceptance or rejection",scope:"Seven capability pairs under one approved synthetic fixture",sourceIds:[]}})),questionId=(proposed.data as any).question.id;await app.execute(command(projectId,"question.select",{questionId}));await app.execute(command(projectId,"scope.approve",{note:"Capability fixture scope."}));return projectId;}
async function invoke(app:ResearchApplication,projectId:string,capability:string,input:any){return app.execute(command(projectId,"capability.invoke",{capability,input}));}
const hypothesis=(kind:"target"|"null"|"rival")=>({kind,statement:`This is a sufficiently detailed ${kind} scientific hypothesis statement.`,prediction:`Observable prediction for ${kind} condition.`,falsification:`Falsification condition for ${kind}.`,discriminatingObservations:[`Discriminating observation for ${kind}.`],updateRules:[{observation:`Observed outcome for ${kind}.`,effect:kind==="null"?"strengthen":"weaken",rationale:`Outcome changes confidence in ${kind}.`}],evidenceIds:[]});

test("seven public scientific capability interfaces accept bounded inputs and reject adversarial ones",async t=>{const dir=mkdtempSync(join(tmpdir(),"ara-capabilities-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await project(app),catalog=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"catalog",type:"capability.catalog",workspaceId:base.workspaceId,projectId,actor});assert.equal(catalog.status,"ok");assert.equal((catalog.data as any).capabilities.length,7);
  const now="2026-10-02T00:00:00.000Z",hash="a".repeat(64),document={source:{id:"source",title:"Controlled evidence",authors:["Researcher"],year:2026,abstract:"A controlled source.",identifiers:[],sourceUrl:"https://example.org/source",accessUrl:"https://example.org/source",accessStatus:"open",license:"CC-BY-4.0",origin:"fixture",accessedAt:now},version:{id:"version",sourceId:"source",artifactHash:null,contentType:"text",parser:"fixture",parserVersion:"1",parserConfigHash:hash,contentHash:hash,status:"parsed",warning:null,createdAt:now},passages:[{id:"passage",documentVersionId:"version",parentId:null,kind:"paragraph",sectionPath:["Results"],text:"The bounded intervention improved the declared outcome.",pageStart:null,pageEnd:null,charStart:0,charEnd:58,locatorHash:hash,ordinal:0}],references:[],quality:{warnings:[],parserConfidence:1}};
  assert.equal((await invoke(app,projectId,"literature-evidence",{action:"ingest",document})).status,"accepted");const search=await invoke(app,projectId,"literature-evidence",{action:"search",query:"bounded intervention",limit:10});assert.equal((search.data as any).result.passages.length,1);assert.equal((await invoke(app,projectId,"literature-evidence",{action:"claim-check",claim:{id:"supported",runId:null,kind:"fact",text:"The intervention improved the outcome.",status:"verified",createdAt:now},links:[{claimId:"supported",passageId:"passage",experimentRunId:null,relation:"supports",note:"Direct support",createdAt:now}]})).status,"accepted");assert.equal((await invoke(app,projectId,"literature-evidence",{action:"claim-check",claim:{id:"unsupported",runId:null,kind:"fact",text:"An unsupported factual claim.",status:"candidate",createdAt:now},links:[]})).status,"rejected");
  assert.equal((await invoke(app,projectId,"novelty-boundary",{coverageStatus:"complete",noveltyStatus:"supported_with_scope",noveltyScope:"Only this bounded configuration",comparisons:[{status:"distinct",evidencePassageIds:["passage"]}],gaps:[]})).status,"accepted");assert.equal((await invoke(app,projectId,"novelty-boundary",{coverageStatus:"incomplete",noveltyStatus:"supported_with_scope",noveltyScope:"Overclaim",comparisons:[],gaps:[{kind:"coverage",severity:"high",resolved:false}]})).status,"rejected");
  assert.equal((await invoke(app,projectId,"rival-hypotheses",{hypotheses:[hypothesis("target"),hypothesis("null"),hypothesis("rival")],rivalAbsenceJustification:null})).status,"accepted");assert.equal((await invoke(app,projectId,"rival-hypotheses",{hypotheses:[hypothesis("target"),hypothesis("rival")],rivalAbsenceJustification:null})).status,"rejected");
  assert.equal((await invoke(app,projectId,"design-confounding",{experimentalUnit:"independent training seed",assignment:"blocked",comparator:"baseline",primaryOutcome:"accuracy",confounders:["hardware"],controls:["hardware"],repeatedMeasures:true,clusterField:"seed"})).status,"accepted");assert.equal((await invoke(app,projectId,"design-confounding",{experimentalUnit:"test row",assignment:"observational",comparator:"baseline",primaryOutcome:"accuracy",confounders:["dataset"],controls:[],repeatedMeasures:true,clusterField:null})).status,"rejected");
  const observations=[{unitId:"seed-1",variant:"baseline",value:0.8,missingReason:null},{unitId:"seed-1",variant:"candidate",value:0.9,missingReason:null},{unitId:"seed-2",variant:"baseline",value:0.82,missingReason:null},{unitId:"seed-2",variant:"candidate",value:0.91,missingReason:null}];const statistics=await invoke(app,projectId,"statistics-units",{direction:"maximize",observations});assert.equal(statistics.status,"accepted");assert.equal((statistics.data as any).result.nUnits,2);assert.equal((await invoke(app,projectId,"statistics-units",{direction:"maximize",observations:[...observations,{unitId:"seed-1",variant:"baseline",value:0.81,missingReason:null}]})).status,"rejected");
  assert.equal((await invoke(app,projectId,"memory-improvement",{action:"create",id:"verified-memory",memoryType:"procedure",content:"Use paired experimental units.",evidenceIds:["passage"],applicability:"paired designs",invalidationCondition:null,revalidateAfter:null})).status,"accepted");await invoke(app,projectId,"memory-improvement",{action:"review",id:"verified-memory",note:"reviewed"});await invoke(app,projectId,"memory-improvement",{action:"verify",id:"verified-memory",note:"verified"});const found=await invoke(app,projectId,"memory-improvement",{action:"search",query:"paired experimental",limit:10});assert.equal((found.data as any).result.items.length,1);await invoke(app,projectId,"memory-improvement",{action:"create",id:"candidate-memory",memoryType:"claim",content:"Unverified candidate injection.",evidenceIds:[],applicability:"",invalidationCondition:null,revalidateAfter:null});const hidden=await invoke(app,projectId,"memory-improvement",{action:"search",query:"Unverified candidate",limit:10});assert.equal((hidden.data as any).result.items.length,0);
  const facts=[{id:"result.accuracy",kind:"result",value:0.91,unit:"accuracy",sourceObjectId:"analysis",sourcePath:"estimate",sourceHash:hash}],assertions=[{factId:"result.accuracy",assertedValue:0.91,context:"results"}];const writing=await invoke(app,projectId,"scientific-writing",{ledgerId:"ledger-success",studyId:null,facts,requiredFactIds:["result.accuracy"],assertions,report:{title:"Results",blocks:[{type:"fact_text",template:"Accuracy was {{result.accuracy}}."}]}});assert.equal(writing.status,"accepted");assert.match((writing.data as any).result.rendered,/0.91 accuracy/);assert.equal((await invoke(app,projectId,"scientific-writing",{ledgerId:"ledger-invalid",studyId:null,facts,requiredFactIds:["result.accuracy"],assertions,report:{title:"Invalid",blocks:[{type:"qualitative",text:"Accuracy was 0.91."}]}})).status,"rejected");
  const events=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"events",type:"project.events",workspaceId:base.workspaceId,projectId,actor,fromSequence:1,limit:200});assert.ok((events.data as any).events.filter((item:any)=>item.type==="capability.invoked").length>=7);assert.ok((events.data as any).events.filter((item:any)=>item.type==="command.rejected").length>=6);
  const bundle=await app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:"capability-bundle",type:"project.bundle",workspaceId:base.workspaceId,projectId,actor,bundleVersion:"2",artifactPolicy:"metadata",maxEmbeddedBytes:1});assert.equal(bundle.status,"ok");const tables=new Set((bundle.data as any).sections.flatMap((section:any)=>section.rows.map((row:any)=>row.table)));for(const table of ["evidence_sources","document_versions","passages","claims","claim_evidence","memory_items","fact_ledgers","fact_audits"])assert.equal(tables.has(table),true,table);
  const otherProject=await project(app),otherEvidence=await invoke(app,otherProject,"literature-evidence",{action:"search",query:"bounded intervention",limit:10}),otherMemory=await invoke(app,otherProject,"memory-improvement",{action:"search",query:"paired experimental",limit:10});assert.equal((otherEvidence.data as any).result.passages.length,0);assert.equal((otherMemory.data as any).result.items.length,0);
});

test("scientific capabilities require approved scope and user memory verification",async t=>{const dir=mkdtempSync(join(tmpdir(),"ara-capability-gates-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const created=await app.execute(command(null,"project.create",{intent:{title:"Capability gate fixture",direction:"Verify scope and human memory review gates on public scientific capabilities.",domain:"research methods",constraints:[],allowedData:["fixture"],prohibitions:[],profile:"smoke",budget:{gpuHours:0.001,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}})),draftId=created.projectId!,blocked=await invoke(app,draftId,"novelty-boundary",{coverageStatus:"complete",noveltyStatus:"unresolved",noveltyScope:null,comparisons:[],gaps:[]});assert.equal(blocked.status,"rejected");assert.equal(blocked.error?.code,"GATE_REJECTED");const projectId=await project(app);await invoke(app,projectId,"memory-improvement",{action:"create",id:"human-gated",memoryType:"procedure",content:"Human gated memory.",evidenceIds:[],applicability:"",invalidationCondition:null,revalidateAfter:null});await invoke(app,projectId,"memory-improvement",{action:"review",id:"human-gated",note:"reviewed"});const attempted=await app.execute({...command(projectId,"capability.invoke",{capability:"memory-improvement",input:{action:"verify",id:"human-gated",note:"agent attempt"}}),actor:{id:"agent:capability",kind:"agent"}});assert.equal(attempted.status,"rejected");assert.equal(attempted.error?.code,"FORBIDDEN");});
