import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

const pkg=JSON.parse(readFileSync(resolve("package.json"),"utf8")),lock=JSON.parse(readFileSync(resolve("package-lock.json"),"utf8")),audit=JSON.parse(readFileSync(resolve("docs/reports/validation/t4-package-audit.json"),"utf8")),v16Audit=JSON.parse(readFileSync(resolve("docs/reports/validation/v1.6-package-audit.json"),"utf8"));

test("T4 package metadata exposes only the documented release boundary",()=>{assert.equal(pkg.name,"research-explorer-core");assert.equal(pkg.version,"1.6.0");assert.equal(lock.version,pkg.version);assert.equal(lock.packages[""].version,pkg.version);assert.equal(pkg.private,false);assert.equal(pkg.license,"Apache-2.0");assert.deepEqual(Object.keys(pkg.exports).sort(),[".","./application","./client","./contracts","./kernel","./scenario","./server","./ssh"].sort());assert.ok(pkg.files.includes("migrations/*.sql"));assert.ok(pkg.files.includes("python/research_sdk/*.py"));assert.equal(pkg.files.some((item:string)=>/^(src|tests|scripts|examples|benchmarks)\//.test(item)),false);});

test("T4 machine audit proves package contents and clean installation",()=>{assert.equal(audit.stage,"T4");assert.equal(audit.package.version,"1.5.0-rc.1");assert.equal(audit.status,"pass");assert.equal(audit.audits.license,"Apache-2.0");assert.equal(audit.audits.private,false);assert.deepEqual(audit.audits.forbiddenFiles,[]);assert.deepEqual(audit.audits.secretMatches,[]);assert.equal(audit.freshInstall.offline,true);assert.equal(audit.freshInstall.quickstart.projectCreated,true);assert.deepEqual(audit.freshInstall.extensions,{scenario:true,workerClient:true,pluginDescriptor:true});assert.equal(audit.assertions.noPublishPerformed,true);assert.equal(audit.assertions.noTagCreated,true);});

test("bundled migrations resolve from the installed package instead of process cwd",()=>{const files=readdirSync(resolve("src/infrastructure/db")).filter(name=>name.endsWith(".ts"));for(const name of files)assert.doesNotMatch(readFileSync(resolve("src/infrastructure/db",name),"utf8"),/resolve\(["']migrations\//,name);const helper=readFileSync(resolve("src/infrastructure/db/migration-path.ts"),"utf8");assert.match(helper,/new URL\(`\.\.\/\.\.\/\.\.\/migrations\//);assert.match(helper,/fileURLToPath/);});

test("T4 governance, notices, extension guides and templates are present",()=>{for(const path of ["LICENSE","NOTICE","THIRD_PARTY_NOTICES.md","CONTRIBUTING.md","CODE_OF_CONDUCT.md","SECURITY.md","SUPPORT.md","docs/guides/compatibility-and-deprecation.md","docs/guides/extensions/scenario-development.md","docs/guides/extensions/plugin-development.md","docs/guides/extensions/worker-development.md","docs/guides/extensions/client-sdk-development.md","docs/templates/scenario/manifest.json","docs/templates/plugin/package.json","docs/templates/rfc.md","docs/templates/adr.md"])assert.ok(readFileSync(resolve(path),"utf8").length>20,path);});

test("v1.6 package contains and runs the public scientific capability facade",()=>{assert.equal(v16Audit.status,"pass");assert.equal(v16Audit.package.version,"1.6.0-alpha.1");assert.deepEqual(v16Audit.freshInstall.capabilities,{catalog:7,invoke:"accepted"});assert.equal(v16Audit.assertions.scientificCapabilitiesFixture,true);assert.deepEqual(v16Audit.audits.forbiddenFiles,[]);assert.deepEqual(v16Audit.audits.secretMatches,[]);});
