import assert from "node:assert/strict";
import Database from "better-sqlite3";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import {
  PluginInspectionSchema, PluginInstallationsResultSchema, PluginSearchResultSchema, PUBLIC_SCHEMA_VERSION, ResearchApplication,
  type Actor,
} from "../src/public/index.js";
import { ScenarioManifestSchema, assertScenarioJob, negotiateScenario, type ScenarioManifest } from "../src/public/scenario.js";
import { PluginStore } from "../src/infrastructure/db/plugin-store.js";
import { applyMigrationTransaction } from "../src/infrastructure/db/research-store.js";
import { runProcess } from "../src/adapters/process.js";

const user:Actor={id:"user:r",kind:"user"},agent:Actor={id:"agent:r",kind:"agent"};
const base={schemaVersion:PUBLIC_SCHEMA_VERSION,workspaceId:"workspace:r",actor:user,issuedAt:"2026-10-01T00:00:00.000Z"};
async function project(app:ResearchApplication):Promise<string>{const result=await app.execute({...base,type:"project.create",commandId:"r:create",idempotencyKey:"r:create",projectId:null,payload:{intent:{title:"R SDK study",direction:"Validate public research scenarios and permission-aware plugin lifecycle behavior.",domain:"AI/ML",constraints:[],allowedData:["fixture"],prohibitions:["no plugin execution during search"],profile:"exploratory",budget:{gpuHours:1,wallHours:1,diskGiB:1,modelCalls:1,knownCostUsd:0}}}});assert.equal(result.status,"accepted");return result.projectId!;}
let sequence=0;
async function command(app:ResearchApplication,input:Record<string,unknown>){sequence++;return app.execute({...base,commandId:`r:command:${sequence}`,idempotencyKey:`r:key:${sequence}`,issuedAt:new Date().toISOString(),...input});}
async function query(app:ResearchApplication,input:Record<string,unknown>){sequence++;return app.query({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`r:query:${sequence}`,workspaceId:base.workspaceId,actor:user,...input});}

function scenarioManifest():ScenarioManifest{return ScenarioManifestSchema.parse({id:"fixture.scenario",name:"Fixture scenario",version:"1.0.0",description:"A complete public Scenario contract fixture.",domain:"testing",scenarioSdkVersion:"1.0.0",coreSchemaRange:"^1.0.0",languages:["typescript","python"],executors:["python"],permissions:["filesystem.read","process"],budget:{maxWallTimeMs:1000,maxCpuCores:1,maxMemoryMiB:256,maxDiskMiB:256,maxGpuCount:0,maxKnownCostUsd:0},capabilities:[{id:"data",kind:"data",description:"Describe data",permissions:["filesystem.read"],inputSchema:{},outputSchema:{},failureClasses:["data"]},{id:"experiment",kind:"experiment",description:"Create job",permissions:["process"],inputSchema:{},outputSchema:{},failureClasses:["scientific"]},{id:"evaluation",kind:"evaluation",description:"Evaluate",permissions:[],inputSchema:{},outputSchema:{},failureClasses:["data"]},{id:"analysis",kind:"analysis",description:"Analyze",permissions:[],inputSchema:{},outputSchema:{},failureClasses:["scientific"]}],artifacts:[{name:"result.json",mediaType:"application/json",required:true,maxBytes:10000,access:"project"}]});}

test("TypeScript and generated Python Scenario SDK share compatibility, permission and budget gates",async()=>{
  const manifest=scenarioManifest(),accepted=negotiateScenario({scenario:manifest,coreSchemaVersion:"1.0.0",approvedPermissions:["filesystem.read","process"],availableExecutors:["python"]});assert.equal(accepted.compatible,true);
  const blocked=negotiateScenario({scenario:manifest,coreSchemaVersion:"2.0.0",approvedPermissions:["filesystem.read"],availableExecutors:["pi"]});assert.equal(blocked.compatible,false);assert.equal(blocked.issues.some(item=>item.includes("not approved")),true);assert.equal(blocked.issues.some(item=>item.includes("unavailable")),true);
  const job={name:"fixture",dataRole:"exploration",studyId:null,execution:{kind:"python",workspace:"/tmp",script:"run.py",args:[],env:{},artifactPaths:[]},resources:{cpuCores:1,memoryMiB:128,diskMiB:128,gpuCount:0},limits:{wallTimeMs:1000,cpuTimeSeconds:1,maxOutputBytes:1000,maxArtifactBytes:1000},priority:0,resumable:true,maxAttempts:1};assert.equal(assertScenarioJob(manifest,job).name,"fixture");assert.throws(()=>assertScenarioJob(manifest,{...job,resources:{...job.resources,cpuCores:2}}),/exceeds/);
  const python=await runProcess("python3",["examples/scenarios/public-python/scenario.py"],{timeoutMs:5000,env:{PATH:process.env.PATH,PYTHONPATH:resolve("python")}});assert.equal(python.exitCode,0,python.stderr);assert.equal(python.timedOut,false);
});

function writePlugin(root:string,input:{version:string;permissions:string[];coreRange?:string;marker:string}):void{mkdirSync(join(root,"extensions"),{recursive:true});mkdirSync(join(root,"skills","fixture"),{recursive:true});writeFileSync(join(root,"package.json"),JSON.stringify({name:"@fixture/research-plugin",version:input.version,description:"Static Pi bridge fixture",license:"MIT",maintainers:["Fixture maintainer"],dependencies:{zod:"4.6.5"},pi:{extensions:["extensions/index.ts"],skills:["skills/fixture"]},autoResearch:{description:"Research plugin with static metadata",domain:["vision"],permissions:input.permissions,sideEffects:["writes project artifacts"],tools:["fixture_tool"],apps:["fixture_app"],mcp:["fixture_mcp"],scenarios:["fixture.scenario"],coreSchemaRange:input.coreRange??"^1.0.0",piVersionRange:"^0.85.0"}},null,2));writeFileSync(join(root,"skills","fixture","SKILL.md"),"# Fixture\nStatic skill metadata.\n");writeFileSync(join(root,"extensions","index.ts"),`import { writeFileSync } from "node:fs"; writeFileSync(${JSON.stringify(input.marker)}, "EXECUTED");\n`);}

test("plugin search is static; install locks content; drift quarantines and permission expansion requires approval",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-r-plugin-")),dbPath=join(dir,"research.db"),catalog=join(dir,"catalog"),pluginRoot=join(catalog,"fixture"),badRoot=join(catalog,"incompatible"),marker=join(dir,"executed.marker");mkdirSync(pluginRoot,{recursive:true});mkdirSync(badRoot,{recursive:true});writePlugin(pluginRoot,{version:"1.0.0",permissions:["filesystem.read"],marker});writePlugin(badRoot,{version:"1.0.0",permissions:["filesystem.read"],coreRange:"^2.0.0",marker:join(dir,"bad.marker")});t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:dbPath});t.after(()=>app.close());const projectId=await project(app);
  const sourceResult=await command(app,{type:"plugin.source.add",projectId:null,payload:{kind:"local",location:catalog,label:"Local fixtures"}});assert.equal(sourceResult.status,"accepted");const sourceId=(sourceResult.data as any).source.id;
  const refresh=await command(app,{type:"plugin.source.refresh",projectId:null,payload:{sourceId}});assert.equal(refresh.status,"accepted");assert.equal(existsSync(marker),false,"metadata refresh must not execute extension code");
  const searched=await query(app,{type:"plugin.search",projectId:null,query:"Research plugin",filters:{contribution:"apps",compatibleOnly:true}}),plugins=PluginSearchResultSchema.parse(searched.data).plugins;assert.equal(plugins.length,1);const descriptor=plugins[0]!;assert.equal(descriptor.contributions.apps[0],"fixture_app");assert.equal(descriptor.contributions.mcp[0],"fixture_mcp");assert.deepEqual(descriptor.permissions.sort(),["filesystem.read","host.full","model"].sort(),"Pi extension and skill effective permissions must be visible");
  const inspection=PluginInspectionSchema.parse((await query(app,{type:"plugin.inspect",projectId:null,descriptorId:descriptor.descriptorId})).data);assert.equal(inspection.inspectionStatus,"inspected");assert.equal(inspection.plugin.dependencies.includes("zod"),true);
  const agentInstall=await command(app,{actor:agent,type:"plugin.install",projectId,payload:{descriptorId:descriptor.descriptorId,approvedPermissions:descriptor.permissions}});assert.equal(agentInstall.status,"rejected");assert.equal(agentInstall.error?.code,"FORBIDDEN");
  const underApproved=await command(app,{type:"plugin.install",projectId,payload:{descriptorId:descriptor.descriptorId,approvedPermissions:["filesystem.read"]}});assert.equal(underApproved.status,"rejected");assert.equal(underApproved.error?.code,"GATE_REJECTED");
  const installed=await command(app,{type:"plugin.install",projectId,payload:{descriptorId:descriptor.descriptorId,approvedPermissions:descriptor.permissions}});assert.equal(installed.status,"accepted");const installation=(installed.data as any).installation;assert.equal(installation.scope,"project","Project is the default install scope");assert.equal(existsSync(join(installation.cachePath,"package.json")),true);assert.equal(existsSync(marker),false,"install snapshots bytes without importing code");const incompleteBundle=await query(app,{type:"project.bundle",projectId,bundleVersion:"1",artifactPolicy:"metadata",maxEmbeddedBytes:1});assert.equal(incompleteBundle.status,"rejected");assert.equal(incompleteBundle.error?.code,"GATE_REJECTED","Bundle v1 must fail closed instead of dropping plugin locks");
  const enabled=await command(app,{type:"plugin.enable",projectId,payload:{installationId:installation.id}});assert.equal((enabled.data as any).installation.status,"enabled");
  writeFileSync(join(pluginRoot,"extensions","index.ts"),"// source drift\n");await command(app,{type:"plugin.disable",projectId,payload:{installationId:installation.id}});const drifted=await command(app,{type:"plugin.enable",projectId,payload:{installationId:installation.id}});assert.equal(drifted.status,"rejected");assert.equal(drifted.error?.code,"CONFLICT");let listed=PluginInstallationsResultSchema.parse((await query(app,{type:"plugin.installations",projectId})).data).installations;assert.equal(listed.find(item=>item.id===installation.id)?.status,"quarantined");
  writePlugin(pluginRoot,{version:"1.1.0",permissions:["filesystem.read","network"],marker});await command(app,{type:"plugin.source.refresh",projectId:null,payload:{sourceId}});const versions=PluginSearchResultSchema.parse((await query(app,{type:"plugin.search",projectId:null,query:"@fixture/research-plugin",filters:{compatibleOnly:true}})).data).plugins,target=versions.find(item=>item.version==="1.1.0")!;assert.ok(target);assert.equal(target.permissions.includes("network"),true);
  const unapprovedUpdate=await command(app,{type:"plugin.update",projectId,payload:{installationId:installation.id,targetDescriptorId:target.descriptorId,approvedPermissions:descriptor.permissions}});assert.equal(unapprovedUpdate.status,"rejected");assert.equal(unapprovedUpdate.error?.code,"GATE_REJECTED");const updated=await command(app,{type:"plugin.update",projectId,payload:{installationId:installation.id,targetDescriptorId:target.descriptorId,approvedPermissions:target.permissions}});assert.equal(updated.status,"accepted");assert.deepEqual((updated.data as any).permissionDiff.added,["network"]);assert.equal((updated.data as any).installation.status,"installed");
  const incompatible=PluginSearchResultSchema.parse((await query(app,{type:"plugin.search",projectId:null,query:"",filters:{compatibleOnly:false}})).data).plugins.find(item=>item.compatibilityStatus==="incompatible")!;assert.ok(incompatible);const rejected=await command(app,{type:"plugin.install",projectId,payload:{descriptorId:incompatible.descriptorId,approvedPermissions:incompatible.permissions}});assert.equal(rejected.status,"rejected");assert.equal(rejected.error?.code,"INCOMPATIBLE_VERSION");
  await command(app,{type:"plugin.enable",projectId,payload:{installationId:installation.id}});const runtime=(await query(app,{type:"plugin.runtime",projectId})).data as any;assert.equal(runtime.plugins.length,1);assert.equal(runtime.plugins[0].contentHash,target.contentHash);await command(app,{type:"plugin.remove",projectId,payload:{installationId:installation.id}});listed=PluginInstallationsResultSchema.parse((await query(app,{type:"plugin.installations",projectId})).data).installations;assert.equal(listed.find(item=>item.id===installation.id)?.status,"removed","removal keeps historical installation record");assert.equal(((await query(app,{type:"plugin.runtime",projectId})).data as any).plugins.length,0,"disabled or removed plugins cannot enter future Pi sessions");
});

test("schema 14 plugin migration backs up and rolls back atomically",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-r-migration-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));for(const [name,pass] of [["pass",true],["fail",false]] as const){const path=join(dir,`${name}.db`),app=await ResearchApplication.open({databasePath:path});app.close();const raw=new Database(path);raw.pragma("foreign_keys = OFF");for(const table of ["plugin_lifecycle_v15","plugin_installations_v15","plugin_catalog_v15","plugin_sources_v15"])raw.exec(`DROP TABLE ${table}`);raw.pragma("user_version = 13");if(pass){raw.close();const store=await PluginStore.open(path);assert.ok(store.migrationBackupPath);store.close();const check=new Database(path,{readonly:true});assert.equal(check.pragma("user_version",{simple:true}),14);check.close();}else{const sql=readFileSync(resolve("migrations/013_scenarios_plugins.sql"),"utf8");assert.throws(()=>applyMigrationTransaction(raw,`${sql}\nCREATE TABLE broken (`));assert.equal(raw.pragma("user_version",{simple:true}),13);assert.equal(raw.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='plugin_sources_v15'").get(),undefined);raw.close();}}
});

test("Pi settings sources are inspected statically and workspace plugins flow into project runtime selection",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-r-pi-config-")),pluginRoot=join(dir,"plugin"),settings=join(dir,"settings.json"),marker=join(dir,"marker");mkdirSync(pluginRoot);writePlugin(pluginRoot,{version:"1.0.0",permissions:["filesystem.read"],marker});writeFileSync(settings,JSON.stringify({packages:["./plugin","npm:remote-package"]}));t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());const projectId=await project(app),source=await command(app,{type:"plugin.source.add",projectId:null,payload:{kind:"pi_config",location:settings,label:"Pi settings"}}),sourceId=(source.data as any).source.id;const refreshed=await command(app,{type:"plugin.source.refresh",projectId:null,payload:{sourceId}});assert.equal(refreshed.status,"accepted");assert.equal((refreshed.data as any).plugins.length,1);assert.equal(existsSync(marker),false);const descriptor=PluginSearchResultSchema.parse((await query(app,{type:"plugin.search",projectId:null,query:"@fixture/research-plugin",filters:{sourceKind:"pi_config"}})).data).plugins[0]!;const installed=await command(app,{type:"plugin.install",projectId:null,payload:{scope:"workspace",descriptorId:descriptor.descriptorId,approvedPermissions:descriptor.permissions}}),installation=(installed.data as any).installation;assert.equal(installation.scope,"workspace");await command(app,{type:"plugin.enable",projectId:null,payload:{installationId:installation.id}});const runtime=(await query(app,{type:"plugin.runtime",projectId})).data as any;assert.equal(runtime.plugins.some((item:any)=>item.installationId===installation.id),true);writeFileSync(settings,JSON.stringify({packages:["npm:remote-package"]}));const unavailable=await command(app,{type:"plugin.source.refresh",projectId:null,payload:{sourceId}});assert.equal((unavailable.data as any).source.status,"unavailable");const blockedRuntime=await query(app,{type:"plugin.runtime",projectId});assert.equal(blockedRuntime.status,"rejected");assert.equal(blockedRuntime.error?.code,"CONFLICT");assert.equal(PluginInstallationsResultSchema.parse((await query(app,{type:"plugin.installations",projectId})).data).installations[0]?.status,"enabled","source loss must not erase history");
});

test("repository sources are mirrored and inspected without checking out or executing plugin code",async t=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-r-git-")),repo=join(dir,"repo"),marker=join(dir,"git-marker");mkdirSync(repo);writePlugin(repo,{version:"1.0.0",permissions:["filesystem.read"],marker});execFileSync("git",["init","-q"],{cwd:repo});execFileSync("git",["add","."],{cwd:repo});execFileSync("git",["-c","user.name=Fixture","-c","user.email=fixture@example.test","commit","-qm","fixture"],{cwd:repo});t.after(()=>rmSync(dir,{recursive:true,force:true}));const app=await ResearchApplication.open({databasePath:join(dir,"research.db")});t.after(()=>app.close());await project(app);const added=await command(app,{type:"plugin.source.add",projectId:null,payload:{kind:"git",location:`file://${repo}#HEAD`,label:"Pinned repository"}}),sourceId=(added.data as any).source.id,refreshed=await command(app,{type:"plugin.source.refresh",projectId:null,payload:{sourceId}});assert.equal(refreshed.status,"accepted");assert.equal((refreshed.data as any).plugins.length,1);assert.equal(existsSync(marker),false);const result=PluginSearchResultSchema.parse((await query(app,{type:"plugin.search",projectId:null,query:"@fixture/research-plugin",filters:{sourceKind:"git"}})).data);assert.equal(result.plugins[0]?.sourceKind,"git");
});
