import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { EvidenceSynthesisService } from "../src/application/evidence-synthesis.js";
import { StudyWorkflow } from "../src/application/study-workflow.js";
import { WorkflowCoordinator } from "../src/application/workflow-coordinator.js";
import { bubblewrapArgs, runBubblewrap } from "../src/adapters/bubblewrap-runner.js";
import { EvidenceStore } from "../src/infrastructure/db/evidence-store.js";
import { EvidenceSynthesisStore } from "../src/infrastructure/db/evidence-synthesis-store.js";
import { ResearchStore } from "../src/infrastructure/db/research-store.js";
import { SearchStore } from "../src/infrastructure/db/search-store.js";
import { StudyStore } from "../src/infrastructure/db/study-store.js";

test("G workflow enforces baseline, exploration, candidate freeze, one-shot confirmation and statistics", async (t)=>{
  const dir=mkdtempSync(join(tmpdir(),"ara-g-workflow-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));const db=join(dir,"research.db");
  const research=await ResearchStore.open(db);const workflow=new WorkflowCoordinator(research);const program=workflow.createIntent({title:"G fixture",direction:"Evaluate a bounded training change under held-out corruption groups.",allowedData:["public"],constraints:[],prohibitions:[],profile:"confirmatory"});
  const question=workflow.proposeQuestion(program.id,{question:"Does the candidate improve held-out corruption robustness?",rationale:"The paired design separates training-seed variability from repeated corruption measurements.",targetPopulation:"small image classifiers",intervention:"candidate training change",comparator:"frozen baseline",primaryOutcome:"corruption accuracy",scope:"one classifier and fixed corruption groups",sourceIds:["source"]});workflow.selectQuestion(program.id,question.id);workflow.approveScope(program.id);
  const evidence=new EvidenceStore(db);evidence.upsertSource({id:"source",title:"Study",authors:[],year:2025,abstract:"Result",identifiers:[],sourceUrl:"https://example.org",accessUrl:"https://example.org",accessStatus:"open",license:"cc-by",origin:"fixture",accessedAt:new Date().toISOString()});evidence.addDocumentVersion({id:"doc",sourceId:"source",artifactHash:null,contentType:"text",parser:"fixture",parserVersion:"1",parserConfigHash:"fixture",contentHash:"a".repeat(64),status:"parsed",warning:null,createdAt:new Date().toISOString()});evidence.addPassage({id:"passage",documentVersionId:"doc",parentId:null,kind:"paragraph",sectionPath:["Results"],text:"A bounded robustness result with limitations.",pageStart:1,pageEnd:1,charStart:0,charEnd:45,locatorHash:"loc",ordinal:0});evidence.addClaim({id:"claim",runId:program.id,kind:"fact",text:"A bounded result exists.",status:"reviewed",createdAt:new Date().toISOString()});
  const synthesis=await EvidenceSynthesisStore.open(db);const searchProtocol=synthesis.createSearchProtocol(program.id,{queryFamilies:[{id:"p",kind:"problem",queries:["distribution shift"],rationale:"Define the problem boundary."},{id:"m",kind:"method",queries:["robust training"],rationale:"Find method comparisons."},{id:"a",kind:"adjacent",queries:["calibration corruption"],rationale:"Find adjacent explanations."}],databases:["fixture"],startYear:2020,endYear:2026,inclusionCriteria:["Relevant public ML study."],exclusionCriteria:["No relevant outcome."],stopConditions:["No new relevant work."]});synthesis.freezeSearchProtocol(program.id,searchProtocol.id);synthesis.screen({searchProtocolId:searchProtocol.id,sourceId:"source",documentVersionId:"doc",decision:"include",reason:"Direct result.",actor:"reviewer",sourceVersionHash:"a".repeat(64)});const map=synthesis.createEvidenceMap(program.id,{searchProtocolId:searchProtocol.id,coverageStatus:"complete",noveltyStatus:"likely_overlap",noveltyScope:null});const entry=synthesis.addEntry(map.id,{claimId:"claim",sourceId:"source",passageId:"passage",relation:"premise_support",topic:"result",summary:"Full text supports the bounded premise.",evidenceLevel:"full_text",critical:true});synthesis.addClosestWork(map.id,{sourceId:"source",proposedClaim:"Bounded comparison.",overlap:"Shared robustness task.",distinction:"Different treatment.",evidencePassageIds:["passage"],status:"partial_overlap"});const frozenMap=synthesis.freezeEvidenceMap(program.id,map.id);
  const assumption=workflow.addAssumption(question.id,{statement:"Corruption groups are valid repeated measures.",invalidationCondition:"Group labels are invalid.",evidenceIds:[entry.id]});const register=workflow.createAssumptionRegister(question.id,[assumption.id]);workflow.freezeAssumptionRegister(question.id,register.id);const service=new EvidenceSynthesisService(synthesis,research);const h=(kind:"target"|"null"|"rival",statement:string)=>({kind,statement,prediction:`Prediction for ${kind} on held-out groups.`,falsification:`Falsification condition for ${kind}.`,assumptionIds:[assumption.id],discriminatingObservations:[`A discriminating ${kind} observation.`],updateRules:[{observation:`Observed pattern for ${kind}.`,effect:"strengthen" as const,rationale:"Predeclared interpretation rule."}],evidenceIds:kind==="null"?[]:[entry.id]});const set=service.createEvidenceBoundHypothesisSet(program.id,frozenMap.id,{hypotheses:[h("target","The candidate improves held-out corruption accuracy."),h("null","The candidate has no effect on held-out corruption accuracy."),h("rival","Any gain is explained by clean-accuracy variation rather than robustness.")]});workflow.freezeHypothesisSet(program.id,set.id);const protocol=workflow.draftProtocol(program.id,{assumptionRegisterId:register.id,hypothesisSetId:set.id,primaryOutcome:"robust_accuracy",secondaryOutcomes:["clean_accuracy"],exploratoryOutcomes:["ece"],experimentUnit:"one independently trained seed",dataRoles:{train:"train",validation:"validation",confirmation:"sealed"},analysisPlan:"Paired seed by corruption analysis with held-out confirmation groups.",stoppingRules:["Stop at hard budget."],allowedChanges:["Declared parameter grid only."],baselineTolerance:"Reference interval [0.70,0.90]."});workflow.approveProtocol(program.id,protocol.id);workflow.freezeProtocol(program.id,protocol.id);
  const studies=await StudyStore.open(db);assert.ok(studies.migrationBackupPath);const searches=new SearchStore(db);const g=new StudyWorkflow(studies,searches,research);const units=[11,23,47].map(seed=>({id:`run-${seed}`,kind:"training_run",clusterId:null,attributes:{seed},legacySeed:null}));const study=studies.createStudy({programId:program.id,protocolId:protocol.id,hypothesisSetId:set.id,evidenceMapId:frozenMap.id,experimentalUnit:"independently trained run",design:"seed_by_corruption",units,blockingFactors:["corruption_group"],nuisanceFactors:["training_seed"],randomizationSeed:42});assert.deepEqual(studies.units(study.id).map(unit=>unit.id),["run-11","run-23","run-47"]);const outcome=studies.addOutcome(study.id,{name:"robust_accuracy",role:"primary",direction:"maximize",unit:"proportion",minimumMeaningfulEffect:0.01});const trainPath=join(dir,"train-data"),validationPath=join(dir,"validation-data"),confirmationPath=join(dir,"confirmation-data");for(const path of [trainPath,validationPath,confirmationPath])mkdirSync(path);for(const role of [{role:"train" as const,path:trainPath,sealed:false,hash:"1"},{role:"validation" as const,path:validationPath,sealed:false,hash:"2"},{role:"confirmation" as const,path:confirmationPath,sealed:true,hash:"3"}])studies.addDataRole(study.id,{role:role.role,path:role.path,sealed:role.sealed,manifestHash:role.hash.repeat(64)});studies.addAnalysisPlan(study.id,{design:"seed_by_corruption",primaryOutcomeId:outcome.id,confidenceLevel:0.95,multiplicityMethod:"holm",missingPolicy:"fail",outlierPolicy:"Retain all predeclared runs and report diagnostics."});studies.addDeviationPolicy(study.id,{allowedBeforeConfirmation:["debug declared failures"],forbiddenAfterVisibility:["change primary outcome","delete failed unit"],failedRunPolicy:"retain_and_analyze",missingValuePolicy:"fail"});studies.freezeStudy(study.id);assert.equal(studies.dataRoles(study.id).some(role=>role.role==="confirmation"),false);
  const sandbox=await g.runSandbox(study.id,{workspace:dir,command:"/usr/bin/python3",args:["-c","print('sandbox-study')"],timeoutMs:5000});assert.equal(sandbox.output.exitCode,0);assert.equal(studies.resourceUsage(study.id).length,1);
  const baseline=studies.recordBaseline(study.id,{expectedMin:0.7,expectedMax:0.9,observed:0.8,artifactHash:"b".repeat(64)});assert.equal(baseline.status,"passed");const nodes=await g.runExploration({studyId:study.id,strategy:"linear",candidates:[{lr:0.1},{lr:0.2}],budget:{maxCandidates:2,maxWallMs:10_000,maxCostUsd:1,concurrency:1},runner:async(parameters)=>({metric:Number(parameters.lr),costUsd:0,durationMs:1,artifactHash:"c".repeat(64)})});assert.equal(nodes.length,2);assert.equal(nodes[0]!.protocolId,protocol.id);const frozen=g.freezeBestCandidate(study.id,nodes[0]!.searchRunId,nodes[0]!.id,{codeHash:"d".repeat(64),configHash:"e".repeat(64)});assert.throws(()=>studies.issueConfirmationToken(study.id),/approved/);studies.approveCandidate(study.id);const issued=studies.issueConfirmationToken(study.id);assert.throws(()=>studies.consumeConfirmationToken(study.id,"wrong","confirm-run"),/Invalid/);const consumed=studies.consumeConfirmationToken(study.id,issued.token,"confirm-run");assert.equal(consumed.confirmation.path,confirmationPath);assert.equal(consumed.visibility.runId,"confirm-run");assert.equal(research.visibility(program.id).length,1);assert.throws(()=>studies.consumeConfirmationToken(study.id,issued.token,"again"),/ready|consumed/);
  for(const seed of [11,23,47])for(const group of ["blur","noise"]){const unitId=`run-${seed}`,base=seed===11?0.70:seed===23?0.72:0.68,delta=seed===11?0.1:seed===23?0.15:0.2;studies.addObservation(study.id,{phase:"confirmation",variant:"baseline",unitId,group,outcomeId:outcome.id,value:base,missingReason:null,runId:`b-${seed}-${group}`});studies.addObservation(study.id,{phase:"confirmation",variant:"candidate",unitId,group,outcomeId:outcome.id,value:base+delta,missingReason:null,runId:`c-${seed}-${group}`});}
  assert.throws(()=>studies.addObservation(study.id,{phase:"confirmation",variant:"candidate",unitId:"unknown",group:null,outcomeId:outcome.id,value:0.9,missingReason:null,runId:"bad-unit"}),/undeclared experimental unit/);assert.throws(()=>studies.addObservation(study.id,{phase:"exploration",variant:"candidate",unitId:"run-11",group:null,outcomeId:outcome.id,value:0.9,missingReason:null,runId:"late"}),/outside exploration/);const analysis=g.analyzeConfirmation(study.id);assert.ok(Math.abs(analysis.estimates[0]!.estimate-0.15)<1e-12);assert.equal(analysis.estimates[0]!.estimand,"candidate_minus_baseline_by_experimental_unit");assert.equal(analysis.estimates[0]!.nUnits,3);assert.equal(analysis.multiplicity[0]!.adjustedValues.length,2);assert.equal(studies.getStudy(study.id).status,"analyzed");assert.equal(frozen.status,"frozen");
  const failedStudy=studies.createStudy({programId:program.id,protocolId:protocol.id,hypothesisSetId:set.id,evidenceMapId:frozenMap.id,experimentalUnit:"independently trained seed",design:"paired_repeated_run",seeds:[11,23],blockingFactors:[],nuisanceFactors:["training_seed"],randomizationSeed:43});const failedOutcome=studies.addOutcome(failedStudy.id,{name:"robust_accuracy",role:"primary",direction:"maximize",unit:"proportion",minimumMeaningfulEffect:0.01});for(const role of [{role:"train" as const,path:"/data/train",sealed:false,hash:"4"},{role:"validation" as const,path:"/data/validation",sealed:false,hash:"5"},{role:"confirmation" as const,path:"/data/confirmation",sealed:true,hash:"6"}])studies.addDataRole(failedStudy.id,{role:role.role,path:role.path,sealed:role.sealed,manifestHash:role.hash.repeat(64)});studies.addAnalysisPlan(failedStudy.id,{design:"paired_repeated_run",primaryOutcomeId:failedOutcome.id,confidenceLevel:0.95,multiplicityMethod:"none",missingPolicy:"fail",outlierPolicy:"Retain all declared runs."});studies.addDeviationPolicy(failedStudy.id,{allowedBeforeConfirmation:[],forbiddenAfterVisibility:["change primary outcome"],failedRunPolicy:"hard_fail",missingValuePolicy:"fail"});studies.freezeStudy(failedStudy.id);assert.equal(studies.recordBaseline(failedStudy.id,{expectedMin:0.7,expectedMax:0.9,observed:0.5,artifactHash:"f".repeat(64),failureClass:"published_result_not_reproduced"}).status,"failed");await assert.rejects(g.runExploration({studyId:failedStudy.id,strategy:"linear",candidates:[{x:1}],budget:{maxCandidates:1,maxWallMs:100,maxCostUsd:0,concurrency:1},runner:async()=>({metric:1,costUsd:0,durationMs:1})}),/reproduced baseline/);
  searches.close();studies.close();synthesis.close();evidence.close();research.close();
});

test("G bubblewrap runner enforces network, secret and GPU boundaries",async(t)=>{const dir=mkdtempSync(join(tmpdir(),"ara-bwrap-test-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));assert.throws(()=>bubblewrapArgs({workspace:dir,command:"/usr/bin/python3",args:[],timeoutMs:1000,env:{API_TOKEN:"secret"}}),/Secret-like/);const args=bubblewrapArgs({workspace:dir,command:"/usr/bin/nvidia-smi",args:["-L"],timeoutMs:5000,gpuDevice:"0"});assert.ok(args.includes("--unshare-net"));assert.ok(args.includes("/dev/nvidia0"));assert.equal(args.includes("/dev/nvidia1"),false);const bridged=bubblewrapArgs({workspace:dir,command:"/usr/bin/nvidia-smi",args:["-L"],timeoutMs:5000,gpuDevice:"3",gpuEnumerationBridge:true});for(const index of [0,1,2,3])assert.ok(bridged.includes(`/dev/nvidia${index}`));assert.equal(bridged.includes("/dev/nvidia4"),false);const result=await runBubblewrap({workspace:dir,command:"/usr/bin/python3",args:["-c","import socket; s=socket.socket(); s.settimeout(1); print(s.connect_ex(('1.1.1.1',53)))"],timeoutMs:5000,maxProcesses:32,maxAddressSpaceBytes:1024**3});assert.equal(result.exitCode,0);assert.match(result.stdout,/101/);});
