-- v1.2 H: claim assessment, multidimensional review and research decisions.
CREATE TABLE IF NOT EXISTS model_role_sessions (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),role TEXT NOT NULL,provider_model TEXT NOT NULL,input_hash TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS model_invocations (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),role_session_id TEXT REFERENCES model_role_sessions(id),stage TEXT NOT NULL,provider_model TEXT NOT NULL,status TEXT NOT NULL,input_hash TEXT NOT NULL,output_hash TEXT,payload_json TEXT NOT NULL,created_at TEXT NOT NULL,finished_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS claim_assessments (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),study_id TEXT NOT NULL REFERENCES studies(id),claim_id TEXT NOT NULL,grade TEXT NOT NULL,payload_json TEXT NOT NULL,content_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS validity_threats (id TEXT PRIMARY KEY,claim_assessment_id TEXT NOT NULL REFERENCES claim_assessments(id),kind TEXT NOT NULL,severity TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS structured_reviews (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),study_id TEXT NOT NULL REFERENCES studies(id),dimension TEXT NOT NULL,role_session_id TEXT NOT NULL REFERENCES model_role_sessions(id),verdict TEXT NOT NULL,payload_json TEXT NOT NULL,input_hash TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(study_id,dimension));
CREATE TABLE IF NOT EXISTS review_findings (id TEXT PRIMARY KEY,review_id TEXT NOT NULL REFERENCES structured_reviews(id),severity TEXT NOT NULL,status TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS review_responses (id TEXT PRIMARY KEY,review_id TEXT NOT NULL REFERENCES structured_reviews(id),finding_id TEXT NOT NULL REFERENCES review_findings(id),payload_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(finding_id));
CREATE TABLE IF NOT EXISTS research_decisions (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),study_id TEXT NOT NULL REFERENCES studies(id),action TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reproduction_manifests (id TEXT PRIMARY KEY,program_id TEXT NOT NULL REFERENCES research_programs(id),study_id TEXT NOT NULL REFERENCES studies(id),payload_json TEXT NOT NULL,content_hash TEXT NOT NULL,created_at TEXT NOT NULL);
PRAGMA user_version = 7;
