# Generated by scripts/generate_python_scenario_models.py. Do not edit.
from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict

SCHEMA_HASHES = {'scenario-manifest.schema.json': '22d2f046875bb289f33315861b89c6899c693ac492a65b285ddce579913b0b96', 'scenario-data.schema.json': '901ee234d8988288625380929dea6684964a5a330012cb1a74b60c57e71420ca', 'scenario-evaluation.schema.json': '6165ad4bb8b7b040802374e3dd84c74c5ce04b15cef39602071a998827466488', 'scenario-analysis.schema.json': '51099cb5ee95443966c191c2c5684981f71c8aa1c7d4273d5a117217c4f8c1ba', 'scenario-handshake-request.schema.json': 'd712dab0688616c1c6bf61b729f3742c3164fc4177ca540fc4a2af6c527f9373', 'scenario-handshake-result.schema.json': 'd18c1b38f6c24f78e8bd8ed0af0d911624e7ea9633767aaa1a2b5cac6143533d', 'job-spec.schema.json': '19ab5489ad41b670adbb500d8d4fa3df36a91c61ec51f318141eb82acf1f2f99', 'worker-request.schema.json': '8f718c587d38fc3cfcabed479c245eb1f5e7717891d1189746d587883f90d54a', 'worker-result.schema.json': '6b088134e0124abce976401ef380d08c7b125e2eb96896faa2e56b466e8310ec', 'command.schema.json': '8ee691a444534b1539a71cffa4281d937ef04867aa3e2528c51b77e33d59633a', 'command-result.schema.json': '22892d9ec59899763a457d5cf395ab065f0f43fae8ba9362c1f4d87fd37416a4', 'query.schema.json': 'f5a6b6295cf1a180534bca46501beac53fc6e2647698bc81596403c811e4b70d', 'query-result.schema.json': 'db18b4d34d332b80f2f056012f03719602138ed00cfed8c24a0213a6c4c02938', 'service-capabilities.schema.json': 'a53da209a581f8d87c7c7d7c25d0589ac187c72c8c36c763a3039c81a182086c', 'project-bundle.schema.json': 'e10ae13d367b5dd1b745e6bab8e6ef87120a78a96567642e4911c55fee134075', 'project-dependencies.schema.json': '51dcf676a8bf6a4666c30b80cc97bbed37e168cc3c043b4674030ccc68d716c6', 'bundle-compatibility.schema.json': 'dbd6a49232998899511403386a417272f51191bfcd3df96899b2ae0950e36819'}
SCHEMA_IDS = {'scenario-manifest.schema.json': 'https://auto-research.local/schemas/v1/scenario-manifest.schema.json', 'scenario-data.schema.json': 'https://auto-research.local/schemas/v1/scenario-data.schema.json', 'scenario-evaluation.schema.json': 'https://auto-research.local/schemas/v1/scenario-evaluation.schema.json', 'scenario-analysis.schema.json': 'https://auto-research.local/schemas/v1/scenario-analysis.schema.json', 'scenario-handshake-request.schema.json': 'https://auto-research.local/schemas/v1/scenario-handshake-request.schema.json', 'scenario-handshake-result.schema.json': 'https://auto-research.local/schemas/v1/scenario-handshake-result.schema.json', 'job-spec.schema.json': 'https://auto-research.local/schemas/v1/job-spec.schema.json', 'worker-request.schema.json': 'https://auto-research.local/schemas/v1/worker-request.schema.json', 'worker-result.schema.json': 'https://auto-research.local/schemas/v1/worker-result.schema.json', 'command.schema.json': 'https://auto-research.local/schemas/v1/command.schema.json', 'command-result.schema.json': 'https://auto-research.local/schemas/v1/command-result.schema.json', 'query.schema.json': 'https://auto-research.local/schemas/v1/query.schema.json', 'query-result.schema.json': 'https://auto-research.local/schemas/v1/query-result.schema.json', 'service-capabilities.schema.json': 'https://auto-research.local/schemas/v1/service-capabilities.schema.json', 'project-bundle.schema.json': 'https://auto-research.local/schemas/v1/project-bundle.schema.json', 'project-dependencies.schema.json': 'https://auto-research.local/schemas/v1/project-dependencies.schema.json', 'bundle-compatibility.schema.json': 'https://auto-research.local/schemas/v1/bundle-compatibility.schema.json'}
SCENARIO_SDK_VERSION = "1.0.0"

Permission = Literal["filesystem.read", "filesystem.write", "network", "process", "gpu", "model", "secrets", "confirmation", "host.full"]
FailureClass = Literal["environment", "data", "scientific", "budget", "timeout", "cancelled", "worker_lost"]

class ScenarioBudget(TypedDict):
    maxWallTimeMs: int
    maxCpuCores: int
    maxMemoryMiB: int
    maxDiskMiB: int
    maxGpuCount: int
    maxKnownCostUsd: float

class ScenarioCapability(TypedDict):
    id: str
    kind: Literal["data", "experiment", "evaluation", "analysis", "domain"]
    description: str
    permissions: list[Permission]
    inputSchema: dict[str, Any]
    outputSchema: dict[str, Any]
    failureClasses: list[FailureClass]

class ArtifactDeclaration(TypedDict):
    name: str
    mediaType: str
    required: bool
    maxBytes: int
    access: Literal["public", "project", "private"]

class ScenarioManifest(TypedDict):
    id: str
    name: str
    version: str
    description: str
    domain: str
    scenarioSdkVersion: Literal["1.0.0"]
    coreSchemaRange: str
    languages: list[Literal["typescript", "python"]]
    executors: list[Literal["python", "bubblewrap", "pi"]]
    permissions: list[Permission]
    budget: ScenarioBudget
    capabilities: list[ScenarioCapability]
    artifacts: list[ArtifactDeclaration]

class DataRole(TypedDict):
    role: Literal["train", "validation", "confirmation", "audit"]
    uri: str
    sealed: bool
    contentHash: str

class DataContract(TypedDict):
    datasetId: str
    manifestHash: str
    roles: list[DataRole]
    experimentalUnit: dict[str, Any]

class EvaluationContract(TypedDict):
    metric: str
    direction: Literal["maximize", "minimize"]
    value: float | None
    missingReason: str | None
    unitId: str
    group: str | None
    artifactHashes: list[str]

class AnalysisContract(TypedDict):
    estimand: str
    clusterUnit: str
    method: str
    estimate: float | None
    interval: tuple[float, float] | None
    sensitivity: list[dict[str, Any]]
    artifactHashes: list[str]

class WorkerRequest(TypedDict):
    type: str
    requestId: str
    jobId: NotRequired[str]
    attempt: NotRequired[int]
    workerId: NotRequired[str]
    leaseToken: NotRequired[str]

class WorkerResult(TypedDict):
    requestId: str
    status: Literal["ok", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    handledAt: str

class PublicCommand(TypedDict):
    schemaVersion: Literal["1.0.0"]
    commandId: str
    idempotencyKey: str
    workspaceId: str
    projectId: str | None
    actor: dict[str, Any]
    issuedAt: str
    type: str
    payload: dict[str, Any]

class PublicQuery(TypedDict):
    schemaVersion: Literal["1.0.0"]
    queryId: str
    workspaceId: str
    projectId: str | None
    actor: dict[str, Any]
    type: str

class CommandResult(TypedDict):
    schemaVersion: Literal["1.0.0"]
    commandId: str
    workspaceId: str | None
    projectId: str | None
    status: Literal["accepted", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    eventIds: list[str]
    handledAt: str

class QueryResult(TypedDict):
    schemaVersion: Literal["1.0.0"]
    queryId: str
    workspaceId: str | None
    projectId: str | None
    status: Literal["ok", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    handledAt: str

class ServiceCapabilities(TypedDict):
    serviceVersion: Literal["1.0.0"]
    schemaVersion: Literal["1.0.0"]
    transports: dict[str, bool]
    endpoints: list[str]
    allowedPermissions: list[Permission]
    offline: bool
    telemetry: Literal[False]
    publicExports: list[str]
    startedAt: str
