#!/usr/bin/env python3
"""Generate Python TypedDict contracts from the committed public JSON Schemas."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas/public/v1"
OUTPUT = ROOT / "python/research_sdk/generated_models.py"
FILES = [
    "scenario-manifest.schema.json", "scenario-data.schema.json", "scenario-evaluation.schema.json",
    "scenario-analysis.schema.json", "scenario-handshake-request.schema.json", "scenario-handshake-result.schema.json",
    "job-spec.schema.json", "worker-request.schema.json", "worker-result.schema.json",
    "command.schema.json", "command-result.schema.json", "query.schema.json", "query-result.schema.json", "service-capabilities.schema.json",
    "project-bundle.schema.json", "project-dependencies.schema.json", "bundle-compatibility.schema.json",
]


def render() -> str:
    hashes: dict[str, str] = {}
    ids: dict[str, str] = {}
    for name in FILES:
        content = (SCHEMAS / name).read_bytes()
        hashes[name] = hashlib.sha256(content).hexdigest()
        ids[name] = json.loads(content)["$id"]
    return f'''# Generated by scripts/generate_python_scenario_models.py. Do not edit.
from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict

SCHEMA_HASHES = {hashes!r}
SCHEMA_IDS = {ids!r}
SCENARIO_SDK_VERSION = "1.0.0"

Permission = Literal["filesystem.read", "filesystem.write", "network", "process", "gpu", "model", "secrets", "confirmation", "host.full"]
FailureClass = Literal["environment", "data", "scientific", "budget", "timeout", "cancelled", "worker_lost"]

class ScenarioBudget(TypedDict):
    maxWallTimeMs: int
    maxCpuCores: int
    maxMemoryMiB: int
    maxDiskMiB: int
    maxGpuCount: int
    maxKnownCostUsd: float

class ScenarioCapability(TypedDict):
    id: str
    kind: Literal["data", "experiment", "evaluation", "analysis", "domain"]
    description: str
    permissions: list[Permission]
    inputSchema: dict[str, Any]
    outputSchema: dict[str, Any]
    failureClasses: list[FailureClass]

class ArtifactDeclaration(TypedDict):
    name: str
    mediaType: str
    required: bool
    maxBytes: int
    access: Literal["public", "project", "private"]

class ScenarioManifest(TypedDict):
    id: str
    name: str
    version: str
    description: str
    domain: str
    scenarioSdkVersion: Literal["1.0.0"]
    coreSchemaRange: str
    languages: list[Literal["typescript", "python"]]
    executors: list[Literal["python", "bubblewrap", "pi"]]
    permissions: list[Permission]
    budget: ScenarioBudget
    capabilities: list[ScenarioCapability]
    artifacts: list[ArtifactDeclaration]

class DataRole(TypedDict):
    role: Literal["train", "validation", "confirmation", "audit"]
    uri: str
    sealed: bool
    contentHash: str

class DataContract(TypedDict):
    datasetId: str
    manifestHash: str
    roles: list[DataRole]
    experimentalUnit: dict[str, Any]

class EvaluationContract(TypedDict):
    metric: str
    direction: Literal["maximize", "minimize"]
    value: float | None
    missingReason: str | None
    unitId: str
    group: str | None
    artifactHashes: list[str]

class AnalysisContract(TypedDict):
    estimand: str
    clusterUnit: str
    method: str
    estimate: float | None
    interval: tuple[float, float] | None
    sensitivity: list[dict[str, Any]]
    artifactHashes: list[str]

class WorkerRequest(TypedDict):
    type: str
    requestId: str
    jobId: NotRequired[str]
    attempt: NotRequired[int]
    workerId: NotRequired[str]
    leaseToken: NotRequired[str]

class WorkerResult(TypedDict):
    requestId: str
    status: Literal["ok", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    handledAt: str

class PublicCommand(TypedDict):
    schemaVersion: Literal["1.0.0"]
    commandId: str
    idempotencyKey: str
    workspaceId: str
    projectId: str | None
    actor: dict[str, Any]
    issuedAt: str
    type: str
    payload: dict[str, Any]

class PublicQuery(TypedDict):
    schemaVersion: Literal["1.0.0"]
    queryId: str
    workspaceId: str
    projectId: str | None
    actor: dict[str, Any]
    type: str

class CommandResult(TypedDict):
    schemaVersion: Literal["1.0.0"]
    commandId: str
    workspaceId: str | None
    projectId: str | None
    status: Literal["accepted", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    eventIds: list[str]
    handledAt: str

class QueryResult(TypedDict):
    schemaVersion: Literal["1.0.0"]
    queryId: str
    workspaceId: str | None
    projectId: str | None
    status: Literal["ok", "rejected"]
    data: Any | None
    error: dict[str, Any] | None
    handledAt: str

class ServiceCapabilities(TypedDict):
    serviceVersion: Literal["1.0.0"]
    schemaVersion: Literal["1.0.0"]
    transports: dict[str, bool]
    endpoints: list[str]
    allowedPermissions: list[Permission]
    offline: bool
    telemetry: Literal[False]
    publicExports: list[str]
    startedAt: str
'''


def main() -> None:
    expected = render()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("Python Scenario SDK models are stale; run npm run generate:python-sdk")
        print(json.dumps({"status": "pass", "schemas": len(FILES), "output": str(OUTPUT.relative_to(ROOT))}))
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(json.dumps({"status": "generated", "schemas": len(FILES), "output": str(OUTPUT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
