import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { StudyWorkflow } from "../src/application/study-workflow.js";
import { ResearchStore } from "../src/infrastructure/db/research-store.js";
import { SearchStore } from "../src/infrastructure/db/search-store.js";
import { StudyStore } from "../src/infrastructure/db/study-store.js";
import { hCaseDb, hCaseRoot, hStudyContext } from "./h_case_context.js";
const root=hCaseRoot,db=hCaseDb,studyId=hStudyContext().id,groups=["gaussian_noise-severity3","contrast-severity3"];
const load=(variant:string,seed:number)=>JSON.parse(readFileSync(join(root,"sandboxes",`confirmation-${variant}-seed${seed}`,`${variant}-seed${seed}.json`),"utf8"));const seeds=[11,23,47],baseline=seeds.map(seed=>load("baseline",seed)),candidate=seeds.map(seed=>load("augmix",seed));const studies=await StudyStore.open(db),searches=new SearchStore(db),research=await ResearchStore.open(db);
try{const outcomes=studies.outcomes(studyId),primary=outcomes.find(item=>item.name==="mean corruption accuracy")!,clean=outcomes.find(item=>item.name==="clean accuracy")!,ece=outcomes.find(item=>item.name==="expected calibration error")!;for(const [variant,rows] of [["baseline",baseline],["candidate",candidate]] as const)for(const row of rows){if(row.phase!=="confirmation"||row.epochs!==12)throw new Error("Confirmation result lineage mismatch");for(const group of groups)studies.addObservation(studyId,{phase:"confirmation",variant,seed:row.seed,group,outcomeId:primary.id,value:row.metrics[group].accuracy,missingReason:null,runId:`confirmation-${variant}-${row.seed}`});studies.addObservation(studyId,{phase:"confirmation",variant,seed:row.seed,group:"clean-test",outcomeId:clean.id,value:row.metrics["clean-test"].accuracy,missingReason:null,runId:`confirmation-${variant}-${row.seed}`});studies.addObservation(studyId,{phase:"confirmation",variant,seed:row.seed,group:"clean-test",outcomeId:ece.id,value:row.metrics["clean-test"].ece,missingReason:null,runId:`confirmation-${variant}-${row.seed}`});}const result=new StudyWorkflow(studies,searches,research).analyzeConfirmation(studyId);const artifact={studyId,baseline,candidate,analysis:result,createdAt:new Date().toISOString()};writeFileSync(join(root,"analysis.json"),JSON.stringify(artifact,null,2)+"\n");console.log(JSON.stringify(result,null,2));}finally{research.close();searches.close();studies.close();}
