import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { PiResearchModel } from "../src/adapters/pi-model.js";
import { ReviewWorkflow } from "../src/application/review-workflow.js";
import { ReviewStore } from "../src/infrastructure/db/review-store.js";
import { FactAuditStore } from "../src/infrastructure/db/fact-audit-store.js";
import { hCaseDb, hCaseRoot, hStudyContext } from "./h_case_context.js";
import { ensureHFactLedger } from "./h_fact_ledger.js";
const root=hCaseRoot,study=hStudyContext(),programId=study.programId,studyId=study.id,snapshot=JSON.parse(readFileSync(join(root,"review-snapshot.json"),"utf8")),ledger=await ensureHFactLedger();const model=await PiResearchModel.create({providerId:"local-vllm",modelId:"qwen-local",baseUrl:process.env.H_LOCAL_LLM_BASE_URL??"http://127.0.0.1:18082/v1",apiKey:"local",api:"openai-completions",timeoutMs:180000,contextWindow:8192,maxTokens:1400,temperature:0});const store=await ReviewStore.open(hCaseDb),facts=await FactAuditStore.open(hCaseDb);try{const workflow=new ReviewWorkflow(store,model,root,facts);const inputs={evidence:{question:snapshot.question,evidenceMap:snapshot.evidenceMap,evidenceEntries:snapshot.evidenceEntries,claimAssessment:snapshot.claimAssessment},methods:{question:snapshot.question,protocol:snapshot.protocol,hypothesisSet:snapshot.hypothesisSet,study:snapshot.study,validityThreats:snapshot.validityThreats},statistics:{analysisPlan:snapshot.analysisPlan,analysis:snapshot.analysis,claimAssessment:snapshot.claimAssessment,validityThreats:snapshot.validityThreats},reproducibility:{protocol:snapshot.protocol,study:snapshot.study,reproduction:snapshot.reproduction,analysis:snapshot.analysis}} as const;const completed=new Set(store.reviews(studyId).map(item=>item.dimension));const output=[...store.reviews(studyId)];for(const dimension of ["evidence","methods","statistics","reproducibility"] as const)if(!completed.has(dimension))output.push(await workflow.review({programId,studyId,dimension,auditSnapshot:inputs[dimension],factLedger:ledger,independence:"session"}));const artifact={model:model.id,reviews:output,findings:store.findings(studyId),createdAt:new Date().toISOString()};writeFileSync(join(root,"reviews.json"),JSON.stringify(artifact,null,2)+"\n");console.log(JSON.stringify(artifact,null,2));}finally{facts.close();store.close();}
