import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { runBubblewrap } from "../src/adapters/bubblewrap-runner.js";
import { hashPayload } from "../src/domain/research.js";
import { StudyStore } from "../src/infrastructure/db/study-store.js";
import { hCaseDb, hCaseRoot, hGpuDevice, hPythonEnv, hStudyContext } from "./h_case_context.js";
const [variant,seedText]=process.argv.slice(2);if(!["baseline","augmix"].includes(variant??"")||!["11","23","47"].includes(seedText??""))throw new Error("usage: h_run_confirmation.ts <baseline|augmix> <seed>");const root=hCaseRoot,studyId=hStudyContext().id,workspace=join(root,"sandboxes",`confirmation-${variant}-seed${seedText}`);mkdirSync(workspace,{recursive:true});const checkpoint=join(root,"sandboxes",`${variant}-seed${seedText}`,`${variant}-seed${seedText}.pt`);const expected=JSON.parse(readFileSync(join(root,"sandboxes",`${variant}-seed${seedText}`,`${variant}-seed${seedText}.json`),"utf8")).checkpointSha256;const actual=createHash("sha256").update(readFileSync(checkpoint)).digest("hex");if(actual!==expected)throw new Error("Frozen checkpoint hash mismatch");const args=["/data/project/examples/cifar-h/experiment.py","--data","/data/input","--variant",variant!,"--seed",seedText!,"--epochs","12","--confirmation","--checkpoint","/data/checkpoint.pt","--output",`/work/${variant}-seed${seedText}.json`];const output=await runBubblewrap({workspace,command:"/data/python/bin/python",args,timeoutMs:60*60*1000,env:{LD_LIBRARY_PATH:"/data/python/lib",OMP_NUM_THREADS:"4",MKL_NUM_THREADS:"4",OPENBLAS_NUM_THREADS:"4"},readOnlyMounts:[{source:resolve("."),target:"/data/project"},{source:join(root,"capability/confirmation"),target:"/data/input"},{source:checkpoint,target:"/data/checkpoint.pt"},{source:hPythonEnv,target:"/data/python"}],gpuDevice:hGpuDevice,maxProcesses:128,maxAddressSpaceBytes:64*1024**3,maxCpuSeconds:60*60,maxFileBytes:256*1024**2});const studies=await StudyStore.open(hCaseDb);try{const artifactHashes=output.exitCode===0?[createHash("sha256").update(readFileSync(join(workspace,`${variant}-seed${seedText}.json`))).digest("hex")]:[];const run=studies.recordSandboxRun({studyId,backend:"bubblewrap",status:output.timedOut?"timed_out":output.exitCode===0?"succeeded":"failed",commandHash:hashPayload({args,variant,seed:seedText,checkpoint:actual}),exitCode:output.exitCode,timedOut:output.timedOut,durationMs:output.durationMs,gpuDevice:hGpuDevice,artifactHashes});studies.recordResourceUsage({studyId,runId:run.id,kind:"confirmation",wallMs:output.durationMs,cpuSeconds:null,gpuSeconds:output.durationMs/1000,peakMemoryBytes:null,diskBytes:null,costUsd:0});console.log(JSON.stringify({workspace,run,output},null,2));}finally{studies.close();}
