#!/usr/bin/env node
import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { ResearchClient } from "auto-research-agent/client";
import { PUBLIC_SCHEMA_VERSION, PublicProjectBundleV2Schema, type Actor } from "auto-research-agent/contracts";
import { ScenarioManifestSchema, assertScenarioJob } from "auto-research-agent/scenario";
import { startCoreService } from "auto-research-agent/server";

const repositoryRoot=resolve("."),scenarioRoot=join(repositoryRoot,"examples/scenarios/fasttext-agnews"),preparedRoot=join(repositoryRoot,".research-data/cases/fasttext-agnews"),runRoot=join(repositoryRoot,".research-data/t2b-fasttext"),workspace=join(runRoot,"workspace"),inputRoot=join(workspace,"input"),outputRoot=join(workspace,"output"),workerCas=join(runRoot,"worker-cas"),sourceServiceDir=join(runRoot,"source-service"),targetServiceDir=join(runRoot,"target-service"),reportPath=join(repositoryRoot,"docs/reports/validation/t2b-fasttext-run.json");
rmSync(runRoot,{recursive:true,force:true});mkdirSync(inputRoot,{recursive:true});mkdirSync(outputRoot,{recursive:true});mkdirSync(workerCas,{recursive:true});
const lock=JSON.parse(readFileSync(join(scenarioRoot,"source-lock.json"),"utf8")),manifest=ScenarioManifestSchema.parse(JSON.parse(readFileSync(join(scenarioRoot,"manifest.json"),"utf8"))),{manifestHash,...lockBody}=lock;
if(hashJson(lockBody)!==manifestHash)throw new Error("T2b source lock manifest hash mismatch");
const staged=[{source:join(preparedRoot,"upstream/fastText-0.9.2/fasttext"),target:join(inputRoot,"fasttext"),expected:lock.fastText.binarySha256,bytes:lock.fastText.binaryBytes},...Object.entries(lock.data).map(([name,value]:[string,any])=>({source:join(preparedRoot,"data",name),target:join(inputRoot,name),expected:value.sha256,bytes:value.bytes}))];
for(const item of staged){if(sha256File(item.source)!==item.expected||statSync(item.source).size!==item.bytes)throw new Error(`Prepared input mismatch: ${item.source}`);copyFileSync(item.source,item.target);}
copyFileSync(join(scenarioRoot,"run_experiment.py"),join(workspace,"run_experiment.py"));copyFileSync(join(scenarioRoot,"source-lock.json"),join(workspace,"source-lock.json"));
const sourceService=await startCoreService({databasePath:join(runRoot,"source.db"),dataDir:sourceServiceDir,artifactRoots:[workerCas],streamPollMs:20}),targetService=await startCoreService({databasePath:join(runRoot,"target.db"),dataDir:targetServiceDir,streamPollMs:20}),sourceToken=readFileSync(sourceService.address.tokenFile!,"utf8").trim(),targetToken=readFileSync(targetService.address.tokenFile!,"utf8").trim(),sourceClient=await ResearchClient.connect({baseUrl:sourceService.address.baseUrl,token:sourceToken}),targetClient=await ResearchClient.connect({baseUrl:targetService.address.baseUrl,token:targetToken}),actor:Actor={id:"user:t2b",kind:"user",displayName:"T2b migration"},workspaceId="workspace:t2b";let sequence=0;
const context=(projectId:string|null)=>({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:`t2b-command-${++sequence}`,idempotencyKey:`t2b-${sequence}-${randomUUID()}`,workspaceId,projectId,actor,issuedAt:new Date().toISOString()}),q=(projectId:string,type:string,extra:Record<string,unknown>={})=>({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`t2b-query-${++sequence}`,type,workspaceId,projectId,actor,...extra});
const startedAt=new Date().toISOString();
try{
  const created=await sourceClient.execute({...context(null),type:"project.create",payload:{intent:{title:"fastText AG News word n-gram comparison",direction:"Test whether word bigrams improve fixed-test accuracy over unigrams under a locked fastText configuration.",domain:"text classification",constraints:["Use the published AG News split","Pair seeds 11, 23, and 47","Treat model training as the experimental unit"],allowedData:["Hash-locked AG News train and test files"],prohibitions:["No test-driven tuning","No population-level significance claim","No paper-score replication claim"],profile:"confirmatory",budget:{gpuHours:0.001,wallHours:1,diskGiB:1,modelCalls:6,knownCostUsd:0}}}}),projectId=created.projectId!;
  const proposed=await sourceClient.execute({...context(projectId),type:"question.propose",payload:{question:{question:"Does wordNgrams=2 improve AG News top-1 accuracy over wordNgrams=1 in the locked fastText configuration?",rationale:"A paired-seed baseline comparison tests a concrete method change while preserving all other settings.",targetPopulation:"Independent fastText trainings on the locked AG News split",intervention:"wordNgrams=2",comparator:"wordNgrams=1",primaryOutcome:"Mean paired difference in fixed-test top-1 accuracy",scope:"Six trainings: two variants paired across three predeclared seeds",sourceIds:[]}}}),questionId=(proposed.data as any).question.id;
  await sourceClient.execute({...context(projectId),type:"question.select",payload:{questionId}});await sourceClient.execute({...context(projectId),type:"scope.approve",payload:{note:"T2b paired-seed protocol, experimental unit, baseline, and claim boundary approved before execution."}});await sourceClient.execute({...context(projectId),type:"conversation.send",payload:{sessionId:null,message:"Predeclared analysis: arithmetic mean of paired-seed accuracy differences. Report three-seed results descriptively and retain all outcomes."}});
  const scenarioJob=JSON.parse(await runPythonScenario([join(scenarioRoot,"scenario.py"),"--job-workspace",workspace])),jobSpec=assertScenarioJob(manifest,scenarioJob),submitted=await sourceClient.execute({...context(projectId),type:"job.submit",payload:{spec:jobSpec,confirmationToken:null}}),jobId=(submitted.data as any).job.id,worker={workerId:"worker:t2b-local",protocolVersion:"1",executors:["bubblewrap"],capacity:{cpuCores:1,memoryMiB:2048,diskMiB:1024,gpuCount:0},gpuDevices:[],leaseDurationMs:300000},claimed=await sourceClient.worker({type:"worker.claim",requestId:"t2b-claim",worker}),lease=(claimed.data as any).lease;
  if(!lease||lease.job.id!==jobId)throw new Error("T2b Worker did not claim the expected Job");
  const execution=await runBubblewrapLease(lease.job.spec.execution.command,lease.job.spec.execution.args,workspace,lease.job.spec.limits.wallTimeMs,lease.job.spec.resources.memoryMiB,256*1024*1024);
  if(execution.stdout)await sourceClient.worker({type:"worker.log",requestId:"t2b-stdout",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"stdout",message:execution.stdout});if(execution.stderr)await sourceClient.worker({type:"worker.log",requestId:"t2b-stderr",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"stderr",message:execution.stderr});
  if(execution.exitCode!==0||execution.timedOut){await sourceClient.worker({type:"worker.fail",requestId:"t2b-fail",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,failureClass:execution.timedOut?"timeout":"scientific",message:`Experiment exit ${execution.exitCode}`});throw new Error(`T2b experiment failed: ${execution.stderr}`);}
  const resultPath=join(outputRoot,"fasttext-agnews-result.json"),result=JSON.parse(readFileSync(resultPath,"utf8")),contracts=JSON.parse(await runPythonScenario([join(scenarioRoot,"scenario.py"),"--evaluate",resultPath])),artifact=putCas(workerCas,readFileSync(resultPath));
  await sourceClient.worker({type:"worker.complete",requestId:"t2b-complete",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,artifacts:[{name:"fasttext-agnews-result.json",mediaType:"application/json",contentHash:artifact.hash,bytes:artifact.bytes,uri:`cas:sha256:${artifact.hash}`,access:"project"}]});
  const bundle=PublicProjectBundleV2Schema.parse((await sourceClient.query(q(projectId,"project.bundle",{bundleVersion:"2",artifactPolicy:"embed",maxEmbeddedBytes:2000000}))).data);writeFileSync(join(runRoot,"bundle-v2.json"),JSON.stringify(bundle));const imported=await targetClient.execute({...context(null),workspaceId:"workspace:t2b-import",type:"project.import",payload:{bundle}}),targetStatus=await targetClient.query({...q(projectId,"project.status"),workspaceId:"workspace:t2b-import"}),dependencies=await targetClient.query({...q(projectId,"project.dependencies"),workspaceId:"workspace:t2b-import"}),jobLogs=await sourceClient.query(q(projectId,"job.logs",{jobId,fromSequence:1,limit:200})),events=await sourceClient.query(q(projectId,"project.events",{fromSequence:1,limit:200})),audit=await sourceClient.audit({workspaceId,projectId,limit:200}) as any;
  if(imported.status!=="accepted"||targetStatus.status!=="ok")throw new Error("T2b Bundle v2 cross-instance import failed");
  const report={schemaVersion:1,stage:"T2b",status:"pass",startedAt,finishedAt:new Date().toISOString(),source:{paper:lock.source.paper,fastTextRelease:lock.source.fastTextRelease,manifestHash,verifiedInputs:staged.length,dataRows:{train:lock.data["train.ft"].rows,test:lock.data["test.ft"].rows}},scenario:{id:manifest.id,version:manifest.version,permissions:manifest.permissions,executors:manifest.executors},execution:{kind:result.executionKind,sandbox:"bubblewrap_unshare_net",projectId,jobId,jobStatus:"succeeded",artifactHash:artifact.hash,elapsedSeconds:result.elapsedSeconds,jobLogCount:(jobLogs.data as any).logs.length,researchEventCount:(events.data as any).events.length,serviceAuditCount:audit.records.length},experiment:{experimentalUnit:result.experimentalUnit,seeds:result.seeds,parameters:result.parameters,baseline:result.baseline,candidate:result.candidate,analysis:result.analysis,contractEvaluationCount:contracts.evaluations.length,contractAnalysis:contracts.analysis},claimBoundary:result.claimBoundary,bundle:{contentHash:bundle.contentHash,sections:bundle.manifest.sections.length,artifactDisposition:bundle.artifacts.find(item=>item.contentHash===artifact.hash)?.disposition,importCompatibility:(imported.data as any).compatibility,targetProjectStatus:(targetStatus.data as any).project.status,targetDependencies:dependencies.data},assertions:{newTrainingRun:true,allLockedHashesVerified:true,pairedExperimentalUnits:true,publicServiceOnly:true,offlineSandbox:true,noGpu:true,noNetwork:true,noModelFilesRetained:!statExists(join(outputRoot,"models"),[".bin",".vec"]),bundleCrossInstance:true}};
  writeAtomic(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:"pass",projectId,jobId,artifactHash:artifact.hash,meanDifference:result.analysis.meanDifference,bundleHash:bundle.contentHash,importStatus:(imported.data as any).compatibility.status}));
}finally{await targetService.close();await sourceService.close();}

function runPythonScenario(args:string[]):Promise<string>{return new Promise((resolveRun,reject)=>{const child=spawn("python3",args,{env:{PATH:process.env.PATH,PYTHONPATH:join(repositoryRoot,"python")},stdio:["ignore","pipe","pipe"]}),stdout:string[]=[],stderr:string[]=[];child.stdout.on("data",chunk=>stdout.push(String(chunk)));child.stderr.on("data",chunk=>stderr.push(String(chunk)));child.on("error",reject);child.on("close",code=>code===0?resolveRun(stdout.join("")):reject(new Error(stderr.join(""))));});}
function statExists(root:string,suffixes:string[]):boolean{try{const names=readdirSync(root);return names.some(name=>suffixes.some(suffix=>name.endsWith(suffix)));}catch{return false;}}
function sha256File(path:string):string{return createHash("sha256").update(readFileSync(path)).digest("hex");}
function hashJson(value:unknown):string{return createHash("sha256").update(JSON.stringify(sortValue(value))).digest("hex");}
function sortValue(value:any):any{if(Array.isArray(value))return value.map(sortValue);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sortValue(item)]));return value;}
function putCas(root:string,content:Buffer):{hash:string;bytes:number}{const hash=createHash("sha256").update(content).digest("hex"),path=join(root,"sha256",hash.slice(0,2),hash.slice(2,4),hash);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,content);return{hash,bytes:content.length};}
function writeAtomic(path:string,content:string):void{mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,content);renameSync(temporary,path);}
async function runBubblewrapLease(command:string,args:string[],cwd:string,timeoutMs:number,memoryMiB:number,maxFileBytes:number):Promise<{stdout:string;stderr:string;exitCode:number|null;timedOut:boolean}>{const bwrap=["--unshare-user","--uid","0","--gid","0","--unshare-net","--die-with-parent","--new-session","--ro-bind","/usr","/usr","--ro-bind","/bin","/bin","--ro-bind","/lib","/lib","--ro-bind","/lib64","/lib64","--proc","/proc","--dev","/dev","--tmpfs","/tmp","--dir","/home","--bind",cwd,"/work","--chdir","/work","--clearenv","--setenv","PATH","/usr/bin:/bin","--setenv","HOME","/home/sandbox","--setenv","TMPDIR","/tmp","/usr/bin/prlimit","--nproc=64","--",command,...args],prlimit=[`--as=${memoryMiB*1024**2}`,`--cpu=${Math.max(1,Math.ceil(timeoutMs/1000))}`,`--fsize=${maxFileBytes}`,"--","/usr/bin/bwrap",...bwrap];return new Promise((resolveRun,reject)=>{const child=spawn("/usr/bin/prlimit",prlimit,{stdio:["ignore","pipe","pipe"],detached:true}),stdout:string[]=[],stderr:string[]=[];let timedOut=false;child.stdout.on("data",chunk=>stdout.push(String(chunk)));child.stderr.on("data",chunk=>stderr.push(String(chunk)));const timer=setTimeout(()=>{timedOut=true;if(child.pid)try{process.kill(-child.pid,"SIGKILL");}catch{child.kill("SIGKILL");}},timeoutMs);child.on("error",error=>{clearTimeout(timer);reject(error);});child.on("close",exitCode=>{clearTimeout(timer);resolveRun({stdout:stdout.join("").slice(0,1000000),stderr:stderr.join("").slice(0,1000000),exitCode,timedOut});});});}
