#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync,mkdirSync,readFileSync,renameSync,writeFileSync } from "node:fs";
import { dirname,join,resolve } from "node:path";
import { arch,platform } from "node:os";
import { evaluateRelease } from "../src/domain/baseline-release.js";

const root=resolve("."),outputIndex=process.argv.indexOf("--output"),reportPath=resolve(outputIndex>=0&&process.argv[outputIndex+1]?process.argv[outputIndex+1]!:"docs/reports/validation/v1.6-release-audit.json"),startedAt=new Date().toISOString(),checks:any[]=[],tagsBefore=tags();let fullTests="";
function run(name:string,command:string,args:string[],timeout=900_000){const started=Date.now();try{const output=execFileSync(command,args,{cwd:root,encoding:"utf8",maxBuffer:100_000_000,timeout,env:{...process.env}});checks.push({name,status:"pass",durationMs:Date.now()-started,summary:last(output)});return output;}catch(error:any){checks.push({name,status:"fail",durationMs:Date.now()-started,summary:String(error?.stdout??error?.message??error).slice(-3000)});write("fail");throw error;}}
run("build","npm",["run","build"]);fullTests=run("full-test-suite","npm",["test"]);run("linux-ssh-workspace","npm",["run","test:ssh-workspace"]);for(const [name,args] of [["typecheck",["run","check"]],["public-boundary",["run","check:boundaries"]],["scenario-boundary",["run","check:scenarios"]],["t3-boundary",["run","check:t3-benchmark"]],["contracts",["run","check:contracts"]],["python-sdk",["run","check:python-sdk"]],["docs",["run","check:docs"]]] as Array<[string,string[]]>)run(name,"npm",args);run("package-install","npx",["tsx","scripts/validate_release_package.ts","--stage","Z","--report","docs/reports/validation/v1.6-z-package-audit.json"]);write("pass");

function write(runStatus:"pass"|"fail"){const artifactPaths=["docs/reports/validation/v1.6-v-platform-matrix.json","docs/reports/validation/v1.6-w-ssh-matrix.json","docs/reports/validation/v1.6-x-local.json","docs/reports/validation/v1.6-y-local.json","docs/reports/validation/t3-capability-v1.2-repeat.json","docs/reports/validation/t2a-mllm-run.json","docs/reports/validation/t2b-fasttext-run.json","docs/reports/validation/v1.6-z-package-audit.json"],artifacts=artifactPaths.filter(existsSync).map(path=>({path,sha256:sha256(readFileSync(path)),bytes:readFileSync(path).length,status:readJson(path)?.status??readJson(path)?.summary?.machineGate??"unknown"})),artifact=(path:string)=>artifacts.find(item=>item.path===path)?.sha256??"".padStart(64,"0"),secrets=secretScan(),packageJson=readJson("package.json"),macPath="docs/reports/validation/v1.6-z-mac-linux.json",mac=existsSync(macPath)?readJson(macPath):null,currentWorkerHash=sha256(readFileSync("remote/worker-stdio.mjs")),isHash=(value:unknown)=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value),macPassed=mac?.status==="pass"&&mac?.client?.os==="darwin"&&["arm64","x64"].includes(mac?.client?.arch)&&mac?.remote?.platform?.os==="linux"&&mac?.remote?.workerHash===currentWorkerHash&&mac?.exploration?.status==="succeeded"&&isHash(mac?.exploration?.artifactHash)&&mac?.confirmation?.status==="succeeded"&&isHash(mac?.confirmation?.artifactHash)&&mac?.confirmation?.sealedHashReturnedToCas===false&&mac?.confirmation?.sealedValueInLogsOrBundle===false;
  const releaseEvidence={checks:[
    {id:"migration",status:runStatus==="pass"&&/migration/.test(fullTests)&&/rolls back|rollback/.test(fullTests)?"passed":"failed",mandatory:true,artifactHashes:[artifact("docs/reports/validation/v1.6-y-local.json")],detail:"Full migration and rollback tests"},
    {id:"bundle",status:runStatus==="pass"&&/Bundle v2/.test(fullTests)?"passed":"failed",mandatory:true,artifactHashes:[artifact("docs/reports/validation/v1.6-x-local.json")],detail:"Bundle roundtrip, tamper, collision, and redaction tests"},
    {id:"real_scenario",status:artifacts.filter(item=>item.path.includes("t2")).every(item=>item.status==="pass")?"passed":"failed",mandatory:true,artifactHashes:[artifact("docs/reports/validation/t2a-mllm-run.json"),artifact("docs/reports/validation/t2b-fasttext-run.json")],detail:"Two recorded real scenarios"},
    {id:"t3",status:readJson("docs/reports/validation/t3-capability-v1.2-repeat.json").summary.dimensionsDemonstrated===12?"passed":"failed",mandatory:true,artifactHashes:[artifact("docs/reports/validation/t3-capability-v1.2-repeat.json")],detail:"T3 v1.2 12/12 and repeat stability"},
    {id:"package",status:readJsonOptional("docs/reports/validation/v1.6-z-package-audit.json")?.status==="pass"?"passed":"failed",mandatory:true,artifactHashes:[artifact("docs/reports/validation/v1.6-z-package-audit.json")],detail:"Clean package installation and public exports"},
    {id:"license",status:packageJson.license==="Apache-2.0"&&existsSync("LICENSE")&&existsSync("THIRD_PARTY_NOTICES.md")?"passed":"failed",mandatory:true,artifactHashes:[sha256(readFileSync("LICENSE")),sha256(readFileSync("THIRD_PARTY_NOTICES.md"))],detail:"License and third-party notices"},
    {id:"secret",status:secrets.length===0?"passed":"failed",mandatory:true,artifactHashes:[sha256(Buffer.from(JSON.stringify(secrets)))],detail:`Tracked/untracked secret scan: ${secrets.length} hits`},
    {id:"platform_matrix",status:macPassed?"passed":"not_evaluated",mandatory:true,artifactHashes:macPassed?[sha256(readFileSync(macPath))]:[artifact("docs/reports/validation/v1.6-v-platform-matrix.json"),artifact("docs/reports/validation/v1.6-w-ssh-matrix.json")],detail:macPassed?"Real Mac client completed exploration and confirmation on user Linux host":"Linux and native macOS component matrices pass; real Mac→user Linux exploration+confirmation remains pending"},
  ],knownLimitations:macPassed?[]:["Real Mac→user-controlled Linux exploration and confirmation must be run by the user before release."]},evaluation=evaluateRelease(releaseEvidence),tagsAfter=tags(),noReleaseSideEffects=JSON.stringify(tagsBefore)===JSON.stringify(tagsAfter);
  const report={schemaVersion:1,release:"v1.6.0",status:evaluation.status==="ready"&&runStatus==="pass"&&noReleaseSideEffects?"pass":"blocked",decision:evaluation.status==="ready"?"release_candidate_ready":"awaiting_mac_cross_host",startedAt,finishedAt:new Date().toISOString(),environment:{node:process.version,platform:platform(),arch:arch(),publicSchemaVersion:"1.0.0",databaseSchemaVersion:17},checks,tests:{count:Number(/# tests (\d+)/.exec(fullTests)?.[1]??0),failed:Number(/# fail (\d+)/.exec(fullTests)?.[1]??0)},releaseEvaluation:evaluation,artifacts,macCrossHost:mac??{status:"not_evaluated",expectedPath:macPath},security:{secretMatches:secrets,tagsBefore,tagsAfter,npmPublishPerformed:false,githubReleaseCreated:false},rollback:{database:"Stop writers; restore the pre-migration SQLite backup and CAS manifest snapshot.",package:"Reinstall the previously pinned package and restore its compatible database backup.",worker:"Disable the new installation hash and re-enable the previous versioned SSH Worker."}};writeAtomic(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,decision:report.decision,tests:report.tests,checks:checks.length,macCrossHost:report.macCrossHost.status}));if(runStatus==="pass"&&report.status!=="pass")process.exitCode=2;}
function readJson(path:string){return JSON.parse(readFileSync(join(root,path),"utf8"));}function readJsonOptional(path:string){try{return readJson(path);}catch{return null;}}function sha256(value:Buffer){return createHash("sha256").update(value).digest("hex");}function last(output:string){return output.trim().split("\n").filter(Boolean).at(-1)?.slice(0,1500)??"";}function tags(){return execFileSync("git",["tag","--points-at","HEAD"],{cwd:root,encoding:"utf8"}).trim().split("\n").filter(Boolean).sort();}function secretScan(){const names=execFileSync("git",["ls-files","--cached","--others","--exclude-standard"],{cwd:root,encoding:"utf8"}).split("\n").filter(Boolean),pattern=/sk-[A-Za-z0-9_-]{16,}/,hits:string[]=[];for(const name of names)try{if(pattern.test(readFileSync(join(root,name),"utf8")))hits.push(name);}catch{}return hits;}function writeAtomic(path:string,value:string){mkdirSync(dirname(path),{recursive:true});const tmp=`${path}.${process.pid}.tmp`;writeFileSync(tmp,value);renameSync(tmp,path);}
