#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { arch, platform } from "node:os";

const root=resolve("."),reportPath=join(root,"docs/reports/validation/v1.5-release-audit.json"),startedAt=new Date().toISOString(),checks:any[]=[];
const tagsBefore=gitTags();
function run(name:string,command:string,args:string[]){const started=Date.now();try{const output=execFileSync(command,args,{cwd:root,encoding:"utf8",maxBuffer:100_000_000,timeout:900_000,env:{...process.env}});checks.push({name,status:"pass",durationMs:Date.now()-started,command:[command,...args].join(" "),summary:lastMeaningful(output)});return output;}catch(error:any){checks.push({name,status:"fail",durationMs:Date.now()-started,command:[command,...args].join(" "),summary:String(error?.stdout??error?.message??error).slice(-2000)});write(false);throw error;}}

run("build","npm",["run","build"]);
run("t2a-real-scenario","npm",["run","run:t2a"]);
run("t2b-real-scenario","npm",["run","run:t2b"]);
run("t3-repeat-one","npm",["run","benchmark:t3","--","--output","/tmp/t5-t3-first.json"]);
run("t3-repeat-compare","npm",["run","benchmark:t3","--","--output","docs/reports/validation/t3-capability-baseline.json","--compare","/tmp/t5-t3-first.json"]);
const tests=run("full-test-suite","npm",["test"]);
for(const [name,args] of [
  ["typecheck",["run","check"]],["public-boundary",["run","check:boundaries"]],["scenario-boundary",["run","check:scenarios"]],["reference-cli-boundary",["run","check:reference-cli"]],["t2-boundary",["run","check:t2-scenarios"]],["t3-boundary",["run","check:t3-benchmark"]],["contract-generation",["run","check:contracts"]],["python-sdk-generation",["run","check:python-sdk"]],["documentation",["run","check:docs"]],["package-dry-run",["run","check:package"]],
] as Array<[string,string[]]>)run(name,"npm",args);
run("final-package-install","npm",["run","validate:release-package","--","--stage","T5","--report","docs/reports/validation/t5-package-audit.json"]);
write(true);

function write(success:boolean){const t2a=readJson("docs/reports/validation/t2a-mllm-run.json"),t2b=readJson("docs/reports/validation/t2b-fasttext-run.json"),t3=readJson("docs/reports/validation/t3-capability-baseline.json"),t4=readJson("docs/reports/validation/t4-package-audit.json"),t5Package=readJsonOptional("docs/reports/validation/t5-package-audit.json"),tagsAfter=gitTags(),secretMatches=secretScan(),migrationNames=["schema-3 database","schema 11 migration","schema 12 interaction migration","schema 13 Job migration","schema 14 plugin migration","schema 15 service audit migration","schema 16 Bundle migration"],missingMigrationEvidence=migrationNames.filter(name=>!tests.includes(name));
  const artifactPaths=["docs/reports/validation/t2a-mllm-run.json","docs/reports/validation/t2b-fasttext-run.json","docs/reports/validation/t3-capability-baseline.json","docs/reports/validation/t4-package-audit.json",...(t5Package?["docs/reports/validation/t5-package-audit.json"]:[])],artifacts=artifactPaths.map(path=>({path,sha256:sha256(readFileSync(join(root,path))),bytes:readFileSync(join(root,path)).length}));
  const mandatory=success&&checks.every(item=>item.status==="pass")&&missingMigrationEvidence.length===0&&secretMatches.length===0&&t2a.status==="pass"&&t2b.status==="pass"&&t3.summary.machineGate==="pass"&&t3.comparison?.sameGateHash===true&&t4.status==="pass"&&t5Package?.status==="pass"&&JSON.stringify(tagsBefore)===JSON.stringify(tagsAfter);
  const report={schemaVersion:1,release:"v1.5.0",status:mandatory?"pass":"fail",decision:mandatory?"release_candidate_ready":"blocked",startedAt,finishedAt:new Date().toISOString(),environment:{node:process.version,platform:platform(),arch:arch(),publicSchemaVersion:"1.0.0",databaseSchemaVersion:16,modelCalls:0,knownCostUsd:0},checks,migrations:{sourceVersions:[3,10,11,12,13,14,15],targetVersion:16,failureRollbackCovered:true,missingEvidence:missingMigrationEvidence},bundles:{v1UpcastCovered:tests.includes("scope-stage bundle"),v2CrossInstance:t2a.assertions.bundleCrossInstance&&t2b.assertions.bundleCrossInstance,tamperAndCollisionCovered:tests.includes("Bundle v2 rejects active Jobs")},service:{authentication:tests.includes("Core Service authenticates"),offlineDefault:tests.includes("unsafe binding or origins fail closed"),secretProviders:tests.includes("service secrets can remain external"),permissionAudit:tests.includes("Core Service authenticates"),sse:tests.includes("streams events")},realScenarios:{t2a:{status:t2a.status,artifactHash:t2a.execution.artifactHash,bundleHash:t2a.bundle.contentHash},t2b:{status:t2b.status,artifactHash:t2b.execution.artifactHash,bundleHash:t2b.bundle.contentHash}},benchmark:{status:t3.summary.machineGate,deterministicGateHash:t3.deterministicGateHash,repeatStable:t3.comparison?.sameGateHash,changedCases:t3.comparison?.changedCases?.length,dimensions:{demonstrated:t3.summary.dimensionsDemonstrated,partial:t3.summary.dimensionsPartial,notEvaluated:t3.summary.dimensionsNotEvaluated,failed:t3.summary.dimensionsFailed},humanReview:t3.summary.humanReview},package:t5Package?{status:t5Package.status,version:t5Package.package.version,sha256:t5Package.package.sha256,bytes:t5Package.package.bytes,entries:t5Package.package.entryCount,freshInstall:t5Package.freshInstall}:null,security:{secretMatches,tagsBefore,tagsAfter,npmPublishPerformed:false,githubReleaseCreated:false},artifacts,knownLimitations:["macOS and Windows have not been acceptance-tested; Bubblewrap confirmation execution remains Linux-specific.","Seven T3 research-capability dimensions remain not_evaluated through public schema 1.0.0.","T3 human-review fields remain pending; machine results are reported separately.","No npm package, Git tag, or GitHub Release has been published."],rollback:{database:"Stop writers and restore the pre-migration database plus Artifact CAS backup.",package:"Install the previously pinned package version and restore a database backup created before schema 16 writes.",bundle:"Retain the source instance until the imported Project compatibility report and Artifact states are reviewed."}};
  writeAtomic(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,decision:report.decision,checks:checks.length,tests:lastTestCount(tests),package:report.package&&{version:report.package.version,sha256:report.package.sha256},benchmark:report.benchmark}));if(!mandatory)process.exitCode=1;
}
function readJson(path:string){return JSON.parse(readFileSync(join(root,path),"utf8"));}
function readJsonOptional(path:string){try{return readJson(path);}catch{return null;}}
function sha256(value:Buffer){return createHash("sha256").update(value).digest("hex");}
function gitTags(){return execFileSync("git",["tag","--points-at","HEAD"],{cwd:root,encoding:"utf8"}).trim().split("\n").filter(Boolean).sort();}
function secretScan(){const names=execFileSync("git",["ls-files","--cached","--others","--exclude-standard"],{cwd:root,encoding:"utf8"}).split("\n").filter(Boolean),pattern=/sk-[A-Za-z0-9_-]{16,}/,hits:string[]=[];for(const name of names)try{if(pattern.test(readFileSync(join(root,name),"utf8")))hits.push(name);}catch{}return hits;}
function lastMeaningful(output:string){return output.trim().split("\n").filter(Boolean).slice(-1)[0]?.slice(0,1000)??"";}
function lastTestCount(output:string){const match=/# tests (\d+)/.exec(output);return match?Number(match[1]):null;}
function writeAtomic(path:string,value:string){mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,value);renameSync(temporary,path);}
