#!/usr/bin/env node
import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { ResearchClient } from "auto-research-agent/client";
import { PUBLIC_SCHEMA_VERSION, PublicProjectBundleV2Schema, type Actor } from "auto-research-agent/contracts";
import { ScenarioManifestSchema, assertScenarioJob } from "auto-research-agent/scenario";
import { startCoreService } from "auto-research-agent/server";

const repositoryRoot=resolve("."),scenarioRoot=join(repositoryRoot,"examples/scenarios/mllm-routing"),sourceRoot=resolve(process.env.MLLM_RESEARCH_ROOT??"/data0/linsihan/mllm-routing-generalization"),runRoot=join(repositoryRoot,".research-data/t2a-mllm"),workspace=join(runRoot,"workspace"),inputRoot=join(workspace,"input"),outputRoot=join(workspace,"output"),workerCas=join(runRoot,"worker-cas"),sourceServiceDir=join(runRoot,"source-service"),targetServiceDir=join(runRoot,"target-service"),reportPath=join(repositoryRoot,"docs/reports/validation/t2a-mllm-run.json");
rmSync(runRoot,{recursive:true,force:true});mkdirSync(inputRoot,{recursive:true});mkdirSync(outputRoot,{recursive:true});mkdirSync(workerCas,{recursive:true});const lock=JSON.parse(readFileSync(join(scenarioRoot,"source-lock.json"),"utf8")),manifest=ScenarioManifestSchema.parse(JSON.parse(readFileSync(join(scenarioRoot,"manifest.json"),"utf8"))),{manifestHash,...lockBody}=lock;if(hashJson(lockBody)!==manifestHash)throw new Error("T2a source lock manifest hash mismatch");const commit=execFileSync("git",["rev-parse","HEAD"],{cwd:sourceRoot,encoding:"utf8"}).trim();if(commit!==lock.sourceCommit)throw new Error(`MLLM source commit mismatch: ${commit}`);if(execFileSync("git",["status","--porcelain"],{cwd:sourceRoot,encoding:"utf8"}).trim())throw new Error("MLLM source repository has uncommitted changes");
for(const item of [...lock.files,...lock.images]){const source=join(sourceRoot,item.path),target=join(inputRoot,item.path);if(sha256File(source)!==item.sha256||statSync(source).size!==item.bytes)throw new Error(`Frozen source mismatch: ${item.path}`);mkdirSync(dirname(target),{recursive:true});copyFileSync(source,target);}copyFileSync(join(scenarioRoot,"evaluate_frozen.py"),join(workspace,"evaluate_frozen.py"));copyFileSync(join(scenarioRoot,"source-lock.json"),join(workspace,"source-lock.json"));
const sourceService=await startCoreService({databasePath:join(runRoot,"source.db"),dataDir:sourceServiceDir,artifactRoots:[workerCas],streamPollMs:20}),targetService=await startCoreService({databasePath:join(runRoot,"target.db"),dataDir:targetServiceDir,streamPollMs:20}),sourceToken=readFileSync(sourceService.address.tokenFile!,"utf8").trim(),targetToken=readFileSync(targetService.address.tokenFile!,"utf8").trim(),sourceClient=await ResearchClient.connect({baseUrl:sourceService.address.baseUrl,token:sourceToken}),targetClient=await ResearchClient.connect({baseUrl:targetService.address.baseUrl,token:targetToken}),actor:Actor={id:"user:t2a",kind:"user",displayName:"T2a migration"},workspaceId="workspace:t2a";let sequence=0;const context=(projectId:string|null)=>({schemaVersion:PUBLIC_SCHEMA_VERSION,commandId:`t2a-command-${++sequence}`,idempotencyKey:`t2a-${sequence}-${randomUUID()}`,workspaceId,projectId,actor,issuedAt:new Date().toISOString()}),q=(projectId:string,type:string,extra:Record<string,unknown>={})=>({schemaVersion:PUBLIC_SCHEMA_VERSION,queryId:`t2a-query-${++sequence}`,type,workspaceId,projectId,actor,...extra});
const startedAt=new Date().toISOString();try{
  const created=await sourceClient.execute({...context(null),type:"project.create",payload:{intent:{title:"RIO multimodal routing transport migration",direction:"Revalidate the bounded RIO answer-schema routing result from frozen multimodal artifacts through the public Scenario and Worker contracts.",domain:"multimodal machine learning",constraints:["No new model inference","Preserve original claim boundary"],allowedData:["Frozen v1.4 RIO artifacts at commit a954fc6"],prohibitions:["No general semantic-routing claim","No hidden confirmation access"],profile:"exploratory",budget:{gpuHours:0.01,wallHours:1,diskGiB:2,modelCalls:1,knownCostUsd:0}}}}),projectId=created.projectId!;
  const proposed=await sourceClient.execute({...context(projectId),type:"question.propose",payload:{question:{question:"Can the frozen RIO answer-schema routing result be reproduced through the v1.5 public Scenario and Worker interfaces?",rationale:"The migration must verify scientific artifacts and bounded conclusions without claiming a new model experiment.",targetPopulation:"Frozen RIO multimodal confirmation artifacts",intervention:"Public Scenario SDK artifact reanalysis",comparator:"Original v1.4 final analysis",primaryOutcome:"Router accuracy and frozen aggregate effect integrity",scope:"Five locked image units plus all locked final analysis and prediction hashes",sourceIds:[]}}}),questionId=(proposed.data as any).question.id;await sourceClient.execute({...context(projectId),type:"question.select",payload:{questionId}});await sourceClient.execute({...context(projectId),type:"scope.approve",payload:{note:"T2a public SDK migration scope approved."}});await sourceClient.execute({...context(projectId),type:"conversation.send",payload:{sessionId:null,message:"Preserve the RIO-format-only claim boundary and record that this is artifact reanalysis without new model inference."}});
  const scenarioJob=JSON.parse(execFileSync("python3",[join(scenarioRoot,"scenario.py"),"--job-workspace",workspace],{encoding:"utf8",env:{PATH:process.env.PATH,PYTHONPATH:join(repositoryRoot,"python")}})),jobSpec=assertScenarioJob(manifest,scenarioJob),submitted=await sourceClient.execute({...context(projectId),type:"job.submit",payload:{spec:jobSpec,confirmationToken:null}}),jobId=(submitted.data as any).job.id,worker={workerId:"worker:t2a-local",protocolVersion:"1",executors:["bubblewrap"],capacity:{cpuCores:1,memoryMiB:1024,diskMiB:512,gpuCount:0},gpuDevices:[],leaseDurationMs:30000},claimed=await sourceClient.worker({type:"worker.claim",requestId:"t2a-claim",worker}),lease=(claimed.data as any).lease;if(!lease||lease.job.id!==jobId)throw new Error("T2a Worker did not claim the expected Job");
  const execution=await runBubblewrapLease(lease.job.spec.execution.command,lease.job.spec.execution.args,workspace,lease.job.spec.limits.wallTimeMs,lease.job.spec.resources.memoryMiB,lease.job.spec.limits.maxArtifactBytes);if(execution.stdout)await sourceClient.worker({type:"worker.log",requestId:"t2a-stdout",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"stdout",message:execution.stdout});if(execution.stderr)await sourceClient.worker({type:"worker.log",requestId:"t2a-stderr",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,stream:"stderr",message:execution.stderr});if(execution.exitCode!==0||execution.timedOut){await sourceClient.worker({type:"worker.fail",requestId:"t2a-fail",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,failureClass:execution.timedOut?"timeout":"scientific",message:`Evaluator exit ${execution.exitCode}`});throw new Error(`T2a evaluator failed: ${execution.stderr}`);}const resultPath=join(outputRoot,"mllm-evaluation.json"),result=JSON.parse(readFileSync(resultPath,"utf8")),artifact=putCas(workerCas,readFileSync(resultPath));await sourceClient.worker({type:"worker.complete",requestId:"t2a-complete",jobId,attempt:lease.attempt,workerId:worker.workerId,leaseToken:lease.leaseToken,artifacts:[{name:"mllm-evaluation.json",mediaType:"application/json",contentHash:artifact.hash,bytes:artifact.bytes,uri:`cas:sha256:${artifact.hash}`,access:"project"}]});
  const bundle=PublicProjectBundleV2Schema.parse((await sourceClient.query(q(projectId,"project.bundle",{bundleVersion:"2",artifactPolicy:"embed",maxEmbeddedBytes:2000000}))).data);writeFileSync(join(runRoot,"bundle-v2.json"),JSON.stringify(bundle));const imported=await targetClient.execute({...context(null),workspaceId:"workspace:t2a-import",type:"project.import",payload:{bundle}}),targetStatus=await targetClient.query({...q(projectId,"project.status"),workspaceId:"workspace:t2a-import"}),dependencies=await targetClient.query({...q(projectId,"project.dependencies"),workspaceId:"workspace:t2a-import"}),jobLogs=await sourceClient.query(q(projectId,"job.logs",{jobId,fromSequence:1,limit:200})),events=await sourceClient.query(q(projectId,"project.events",{fromSequence:1,limit:200})),audit=await sourceClient.audit({workspaceId,projectId,limit:200}) as any;if(imported.status!=="accepted"||targetStatus.status!=="ok")throw new Error("T2a Bundle v2 cross-instance import failed");const report={schemaVersion:1,stage:"T2a",status:"pass",startedAt,finishedAt:new Date().toISOString(),source:{repository:"mllm-routing-generalization",commit,manifestHash,verifiedFiles:lock.files.length,verifiedImages:lock.images.length},scenario:{id:manifest.id,version:manifest.version,permissions:manifest.permissions,executors:manifest.executors},execution:{kind:result.executionKind,sandbox:"bubblewrap_unshare_net",projectId,jobId,jobStatus:"succeeded",artifactHash:artifact.hash,routerAccuracy:result.sampleEvaluation.routerAccuracy,sampleRows:result.sampleEvaluation.rowCount,sampleImages:result.sampleEvaluation.imageCount,jobLogCount:(jobLogs.data as any).logs.length,researchEventCount:(events.data as any).events.length,serviceAuditCount:audit.records.length},frozenResult:result.frozenResult,claimBoundary:result.claimBoundary,bundle:{contentHash:bundle.contentHash,sections:bundle.manifest.sections.length,artifactDisposition:bundle.artifacts.find(item=>item.contentHash===artifact.hash)?.disposition,importCompatibility:(imported.data as any).compatibility,targetProjectStatus:(targetStatus.data as any).project.status,targetDependencies:dependencies.data},assertions:{noNewModelInference:true,sourceCommitClean:true,allLockedHashesVerified:true,publicServiceOnly:true,offlineSandbox:true,bundleCrossInstance:true}};writeAtomic(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:"pass",projectId,jobId,artifactHash:artifact.hash,bundleHash:bundle.contentHash,importStatus:(imported.data as any).compatibility.status}));
}finally{await targetService.close();await sourceService.close();}

function sha256File(path:string):string{return createHash("sha256").update(readFileSync(path)).digest("hex");}
function hashJson(value:unknown):string{return createHash("sha256").update(JSON.stringify(sortValue(value))).digest("hex");}
function sortValue(value:any):any{if(Array.isArray(value))return value.map(sortValue);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sortValue(item)]));return value;}
function putCas(root:string,content:Buffer):{hash:string;bytes:number}{const hash=createHash("sha256").update(content).digest("hex"),path=join(root,"sha256",hash.slice(0,2),hash.slice(2,4),hash);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,content);return{hash,bytes:content.length};}
function writeAtomic(path:string,content:string):void{mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,content);renameSync(temporary,path);}
async function runBubblewrapLease(command:string,args:string[],cwd:string,timeoutMs:number,memoryMiB:number,maxFileBytes:number):Promise<{stdout:string;stderr:string;exitCode:number|null;timedOut:boolean}>{const bwrap=["--unshare-user","--uid","0","--gid","0","--unshare-net","--die-with-parent","--new-session","--ro-bind","/usr","/usr","--ro-bind","/bin","/bin","--ro-bind","/lib","/lib","--ro-bind","/lib64","/lib64","--proc","/proc","--dev","/dev","--tmpfs","/tmp","--dir","/home","--bind",cwd,"/work","--chdir","/work","--clearenv","--setenv","PATH","/usr/bin:/bin","--setenv","HOME","/home/sandbox","--setenv","TMPDIR","/tmp","/usr/bin/prlimit","--nproc=64","--",command,...args],prlimit=[`--as=${memoryMiB*1024**2}`,`--cpu=${Math.max(1,Math.ceil(timeoutMs/1000))}`,`--fsize=${maxFileBytes}`,"--","/usr/bin/bwrap",...bwrap];return new Promise((resolveRun,reject)=>{const child=spawn("/usr/bin/prlimit",prlimit,{stdio:["ignore","pipe","pipe"],detached:true}),stdout:string[]=[],stderr:string[]=[];let timedOut=false;child.stdout.on("data",chunk=>stdout.push(String(chunk)));child.stderr.on("data",chunk=>stderr.push(String(chunk)));const timer=setTimeout(()=>{timedOut=true;if(child.pid)try{process.kill(-child.pid,"SIGKILL");}catch{child.kill("SIGKILL");}},timeoutMs);child.on("error",error=>{clearTimeout(timer);reject(error);});child.on("close",exitCode=>{clearTimeout(timer);resolveRun({stdout:stdout.join("").slice(0,1000000),stderr:stderr.join("").slice(0,1000000),exitCode,timedOut});});});}
