import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";
import { CommandResultSchema, PublicCommandSchema, PublicQuerySchema, QueryResultSchema, WorkerRequestSchema, WorkerResultSchema, type CommandResult, type PublicQuery, type QueryResult, type WorkerRequest, type WorkerResult } from "./contracts.js";
import { CORE_SERVICE_VERSION, ServiceCapabilitiesSchema, type SecretProvider, type ServiceCapabilities } from "./service.js";

export interface ResearchClientOptions{baseUrl:string;token?:string;secretProvider?:SecretProvider;tokenSecretName?:string;fetchImpl?:typeof fetch}
export interface LocalClientOptions{dataDir:string;databasePath:string;autoStart?:boolean;serviceEntryPath?:string;secretProvider?:SecretProvider;timeoutMs?:number}
export interface StreamOptions{workspaceId:string;projectId:string;actorId?:string;fromSequence?:number;jobId?:string;logFrom?:number;signal?:AbortSignal}
export interface StreamEvent{event:string;id:string|null;data:unknown}

export class ResearchClient{
  private constructor(readonly baseUrl:string,private readonly token:string,private readonly fetchImpl:typeof fetch){}
  static async connect(options:ResearchClientOptions):Promise<ResearchClient>{const token=options.token??(await options.secretProvider?.resolve(options.tokenSecretName??"AUTO_RESEARCH_SERVICE_TOKEN","core-service-client"))?.value;if(!token)throw new Error("Core Service token is required");const client=new ResearchClient(options.baseUrl.replace(/\/$/,""),token,options.fetchImpl??fetch);await client.negotiate();return client;}
  static async connectLocal(options:LocalClientOptions):Promise<ResearchClient>{const dataDir=resolve(options.dataDir),discoveryPath=join(dataDir,"core-service.json"),timeoutMs=options.timeoutMs??10000;let discovery=readDiscovery(discoveryPath);if(discovery){try{return await ResearchClient.fromDiscovery(discovery,options.secretProvider);}catch{discovery=null;}}
    if(options.autoStart===false)throw new Error("Local Core Service is not running");const entry=options.serviceEntryPath??fileURLToPath(new URL("../service/cli.js",import.meta.url)),launch=entry.endsWith(".ts")?["--import","tsx",entry]:[entry],child=spawn(process.execPath,[...launch,"--database",resolve(options.databasePath),"--data-dir",dataDir,"--port","0"],{detached:true,stdio:"ignore",env:{...process.env}});child.unref();const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){await delay(50);discovery=readDiscovery(discoveryPath);if(discovery)try{return await ResearchClient.fromDiscovery(discovery,options.secretProvider);}catch{}}throw new Error("Timed out waiting for local Core Service discovery");}
  private static async fromDiscovery(discovery:any,provider?:SecretProvider):Promise<ResearchClient>{let token:string|undefined;if(typeof discovery.tokenFile==="string"&&existsSync(discovery.tokenFile))token=readFileSync(discovery.tokenFile,"utf8").trim();if(!token)token=(await provider?.resolve(discovery.tokenSecretName??"AUTO_RESEARCH_SERVICE_TOKEN","core-service-client"))?.value;if(!token&&typeof discovery.tokenSecretName==="string")token=process.env[discovery.tokenSecretName];return ResearchClient.connect({baseUrl:discovery.baseUrl,token});}
  async negotiate():Promise<ServiceCapabilities>{const result=ServiceCapabilitiesSchema.parse(await this.get("/v1/capabilities"));if(result.serviceVersion!==CORE_SERVICE_VERSION)throw new Error(`Unsupported Core Service version ${result.serviceVersion}`);return result;}
  async execute(input:unknown):Promise<CommandResult>{const command=PublicCommandSchema.parse(input);return CommandResultSchema.parse(await this.post("/v1/commands",command));}
  async query(input:unknown):Promise<QueryResult>{const query=PublicQuerySchema.parse(input);return QueryResultSchema.parse(await this.post("/v1/queries",query));}
  async worker(input:WorkerRequest|unknown):Promise<WorkerResult>{const request=WorkerRequestSchema.parse(input);return WorkerResultSchema.parse(await this.post("/v1/workers",request));}
  async audit(filters:{workspaceId?:string;projectId?:string;limit?:number}={}):Promise<unknown>{const params=new URLSearchParams();for(const[key,value]of Object.entries(filters))if(value!==undefined)params.set(key,String(value));return this.get(`/v1/audit?${params}`);}
  async *stream(options:StreamOptions):AsyncGenerator<StreamEvent>{const params=new URLSearchParams({workspaceId:options.workspaceId,projectId:options.projectId,actorId:options.actorId??"user:sdk",fromSequence:String(options.fromSequence??1),logFrom:String(options.logFrom??1)});if(options.jobId)params.set("jobId",options.jobId);const response=await this.fetchImpl(`${this.baseUrl}/v1/stream?${params}`,{headers:{authorization:`Bearer ${this.token}`,accept:"text/event-stream"},signal:options.signal});if(!response.ok||!response.body)throw await responseError(response);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",current:{event:string;id:string|null;data:string[]}={event:"message",id:null,data:[]};while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});const lines=buffer.split(/\r?\n/);buffer=lines.pop()??"";for(const line of lines){if(line===""){if(current.data.length){const raw=current.data.join("\n");yield{event:current.event,id:current.id,data:JSON.parse(raw)};}current={event:"message",id:null,data:[]};}else if(line.startsWith("event:"))current.event=line.slice(6).trim();else if(line.startsWith("id:"))current.id=line.slice(3).trim();else if(line.startsWith("data:"))current.data.push(line.slice(5).trimStart());}if(done)break;}}
  private async get(path:string):Promise<unknown>{const response=await this.fetchImpl(`${this.baseUrl}${path}`,{headers:{authorization:`Bearer ${this.token}`,accept:"application/json"}});if(!response.ok)throw await responseError(response);return response.json();}
  private async post(path:string,body:unknown):Promise<unknown>{const response=await this.fetchImpl(`${this.baseUrl}${path}`,{method:"POST",headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body)});if(!response.ok)throw await responseError(response);return response.json();}
}

function readDiscovery(path:string):any|null{try{return JSON.parse(readFileSync(path,"utf8"));}catch{return null;}}
async function responseError(response:Response):Promise<Error>{let message=`Core Service returned HTTP ${response.status}`;try{const body=await response.json() as any;message=body.error?.message??message;}catch{}return new Error(message);}
function delay(ms:number):Promise<void>{return new Promise(resolveDelay=>setTimeout(resolveDelay,ms));}
