import { randomUUID } from "node:crypto";
import { EvidenceStore } from "../infrastructure/db/evidence-store.js";
import { MemoryStore } from "../infrastructure/db/memory-store.js";
import { FactAuditStore } from "../infrastructure/db/fact-audit-store.js";
import { SourceRecordSchema,DocumentVersionSchema,PassageSchema,ClaimSchema,ClaimEvidenceSchema,claimEvidenceRequirement,type CanonicalDocument } from "../domain/evidence.js";
import { HypothesisSetSchema,assertHypothesisSetComplete,hashPayload } from "../domain/research.js";
import { createFactLedger,auditFactAssertions,assertFactAudit } from "../domain/facts.js";
import { renderStructuredReport,StructuredReportSchema } from "./structured-report.js";
import type { Actor,ScientificCapabilityId } from "../public/contracts.js";

const CATALOG:Array<{id:ScientificCapabilityId;version:string;description:string;operations:string[];sideEffects:string[]}>= [
  {id:"literature-evidence",version:"1.0.0",description:"Ingest hash-bound documents, search full-text passages, and reject unsupported claims.",operations:["ingest","search","claim-check"],sideEffects:["project evidence write","retrieval audit"]},
  {id:"novelty-boundary",version:"1.0.0",description:"Enforce coverage, gap, closest-work, and scoped-novelty gates.",operations:["evaluate"],sideEffects:["none"]},
  {id:"rival-hypotheses",version:"1.0.0",description:"Validate target, null, rival, discriminating predictions, and update rules.",operations:["evaluate"],sideEffects:["none"]},
  {id:"design-confounding",version:"1.0.0",description:"Validate experimental units, assignment, controls, repeated measures, and confounders.",operations:["evaluate"],sideEffects:["none"]},
  {id:"statistics-units",version:"1.0.0",description:"Compute paired unit-level effects and reject pseudoreplication or incomplete pairs.",operations:["analyze"],sideEffects:["none"]},
  {id:"memory-improvement",version:"1.0.0",description:"Create, review, verify, and retrieve project-scoped memory without candidate injection.",operations:["create","review","verify","search"],sideEffects:["project memory write","access audit"]},
  {id:"scientific-writing",version:"1.0.0",description:"Audit fact assertions and render fact-bound structured reports.",operations:["render"],sideEffects:["fact ledger and audit write"]},
];

export class PublicScientificCapabilities{
  private constructor(private readonly evidence:EvidenceStore,private readonly memory:MemoryStore,private readonly facts:FactAuditStore){}
  static async open(databasePath:string){return new PublicScientificCapabilities(new EvidenceStore(databasePath),new MemoryStore(databasePath),await FactAuditStore.open(databasePath));}
  close(){this.facts.close();this.memory.close();this.evidence.close();}
  catalog(){return{capabilities:CATALOG};}
  invoke(projectId:string,actor:Actor,request:any):unknown{
    if(request.capability==="literature-evidence")return this.evidenceCapability(projectId,request.input);
    if(request.capability==="novelty-boundary")return this.noveltyCapability(request.input);
    if(request.capability==="rival-hypotheses")return this.hypothesisCapability(projectId,request.input);
    if(request.capability==="design-confounding")return this.designCapability(request.input);
    if(request.capability==="statistics-units")return this.statisticsCapability(request.input);
    if(request.capability==="memory-improvement")return this.memoryCapability(projectId,actor,request.input);
    return this.writingCapability(projectId,request.input);
  }
  private evidenceCapability(projectId:string,input:any){const prefix=`${projectId}:`;
    if(input.action==="ingest"){
      const raw=input.document,source=SourceRecordSchema.parse({...raw.source,id:prefix+raw.source.id}),version=DocumentVersionSchema.parse({...raw.version,id:prefix+raw.version.id,sourceId:source.id}),passages=(raw.passages??[]).map((item:any)=>PassageSchema.parse({...item,id:prefix+item.id,documentVersionId:version.id,parentId:item.parentId?prefix+item.parentId:null})),document:CanonicalDocument={source,version,passages,references:raw.references??[],quality:raw.quality??{warnings:[],parserConfidence:null}};
      return{operation:"ingest",...this.evidence.addCanonicalDocument(document),sourceId:raw.source.id,contentHash:version.contentHash};
    }
    if(input.action==="search"){
      const passages=this.evidence.searchPassages(input.query,10000).filter(item=>item.id.startsWith(prefix)).slice(0,input.limit).map(item=>({...item,id:item.id.slice(prefix.length),documentVersionId:item.documentVersionId.slice(prefix.length),parentId:item.parentId?.slice(prefix.length)??null}));this.evidence.recordRetrieval(input.query,{projectId,resultCount:passages.length});return{operation:"search",passages};
    }
    const raw=input.claim,claim=ClaimSchema.parse({...raw,id:prefix+raw.id,runId:projectId}),links=input.links.map((item:any)=>ClaimEvidenceSchema.parse({...item,claimId:claim.id,passageId:item.passageId?prefix+item.passageId:null})),requirement=claimEvidenceRequirement(claim.kind),passageCount=new Set(links.filter((item:any)=>item.passageId).map((item:any)=>item.passageId)).size,experimentCount=links.filter((item:any)=>item.experimentRunId).length;if(passageCount<requirement.minPassages&&(!requirement.allowExperiment||experimentCount===0))throw new Error(`Unsupported scientific claim: requires_${requirement.minPassages}_passages_or_experiment`);this.evidence.addClaim(claim);for(const link of links)this.evidence.linkClaim(link);const validation=this.evidence.validateClaimForFinal(claim.id);if(!validation.ok)throw new Error(`Unsupported scientific claim: ${validation.reasons.join(", ")}`);return{operation:"claim-check",accepted:true,claimId:raw.id};
  }
  private noveltyCapability(input:any){const unresolved=input.gaps.some((gap:any)=>!gap.resolved&&(gap.severity==="high"||gap.kind==="coverage"||gap.kind==="full_text_unavailable"));if((input.coverageStatus==="incomplete"||unresolved)&&input.noveltyStatus!=="unresolved")throw new Error("Incomplete coverage requires novelty=unresolved");if(input.noveltyStatus==="likely_overlap"&&!input.comparisons.length)throw new Error("Likely overlap requires a closest-work comparison");if(input.noveltyStatus==="supported_with_scope"&&(!input.noveltyScope?.trim()||!input.comparisons.length||input.comparisons.some((item:any)=>["unresolved","exact_overlap"].includes(item.status)||!item.evidencePassageIds.length)))throw new Error("Scoped novelty requires resolved closest-work comparisons with passage evidence");return{accepted:true,noveltyStatus:input.noveltyStatus,scope:input.noveltyScope};}
  private hypothesisCapability(projectId:string,input:any){const hypotheses=input.hypotheses.map((item:any)=>({...item,id:`hypothesis-${randomUUID()}`,status:"testable",assumptionIds:[]})),body={hypotheses,rivalAbsenceJustification:input.rivalAbsenceJustification},set=HypothesisSetSchema.parse({id:`hypothesis-set-${randomUUID()}`,programId:projectId,questionId:"public-capability",evidenceMapId:null,version:1,status:"draft",...body,contentHash:hashPayload(body),parentId:null,createdAt:new Date().toISOString()});assertHypothesisSetComplete(set);return{accepted:true,hypothesisCount:set.hypotheses.length,kinds:[...new Set(set.hypotheses.map(item=>item.kind))]};}
  private designCapability(input:any){const controls=new Set(input.controls.map((item:string)=>item.toLowerCase())),uncontrolled=input.confounders.filter((item:string)=>!controls.has(item.toLowerCase()));if(uncontrolled.length)throw new Error(`Uncontrolled confounders: ${uncontrolled.join(", ")}`);if(input.repeatedMeasures&&!input.clusterField)throw new Error("Repeated measures require a clusterField");if(input.experimentalUnit.toLowerCase().includes("row")&&input.repeatedMeasures)throw new Error("Repeated rows cannot replace the declared independent experimental unit");return{accepted:true,experimentalUnit:input.experimentalUnit,assignment:input.assignment,controlledConfounders:input.confounders};}
  private statisticsCapability(input:any){const units=new Map<string,{baseline?:number;candidate?:number}>();for(const item of input.observations){if(item.value===null)continue;const unit=units.get(item.unitId)??{},variant=item.variant as "baseline"|"candidate";if(unit[variant]!==undefined)throw new Error(`Duplicate ${item.variant} observation for experimental unit ${item.unitId}`);unit[variant]=item.value;units.set(item.unitId,unit);}const incomplete=[...units].filter(([,value])=>value.baseline===undefined||value.candidate===undefined).map(([id])=>id);if(incomplete.length)throw new Error(`Incomplete paired experimental units: ${incomplete.join(", ")}`);const differences=[...units.values()].map(value=>(value.candidate!-value.baseline!)*(input.direction==="maximize"?1:-1));if(differences.length<2)throw new Error("At least two independent experimental units are required");const estimate=differences.reduce((a,b)=>a+b,0)/differences.length;return{accepted:true,estimand:"paired candidate minus baseline by experimental unit",nUnits:differences.length,estimate,differences};}
  private memoryCapability(projectId:string,actor:Actor,input:any){const prefix=`${projectId}:`;if(input.action==="create"){const item=this.memory.createCandidate({id:prefix+input.id,type:input.memoryType,namespace:"project",content:input.content,sourceRunId:projectId,evidenceIds:input.evidenceIds,applicability:input.applicability,invalidationCondition:input.invalidationCondition,revalidateAfter:input.revalidateAfter});return{operation:"create",id:input.id,status:item.status,contentHash:item.contentHash};}if(input.action==="review"||input.action==="verify"){const item=this.memory.promote(prefix+input.id,input.action==="review"?"reviewed":"verified",actor.id,input.note);return{operation:input.action,id:input.id,status:item.status};}const items=this.memory.search(input.query,["project"],1000).filter(item=>item.id.startsWith(prefix)).slice(0,input.limit);for(const item of items)this.memory.access(item.id,projectId,"public capability search");return{operation:"search",items:items.map(item=>({id:item.id.slice(prefix.length),type:item.type,status:item.status,content:item.content,evidenceIds:item.evidenceIds,contentHash:item.contentHash}))};}
  private writingCapability(projectId:string,input:any){const ledger=createFactLedger({id:`${projectId}:${input.ledgerId}`,programId:projectId,studyId:input.studyId,facts:input.facts,requiredFactIds:input.requiredFactIds}),audit=auditFactAssertions(ledger,"public-scientific-writing",input.assertions,{requireAll:true});assertFactAudit(audit);const rendered=renderStructuredReport(StructuredReportSchema.parse(input.report),ledger);this.facts.addLedger(ledger);this.facts.addAudit(audit);return{accepted:true,ledgerId:input.ledgerId,auditStatus:audit.status,contentHash:ledger.contentHash,rendered};}
}
