import Database from "better-sqlite3";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  JobArtifactSchema, JobLeaseSchema, JobLogSchema, JobRecordSchema, JobSpecSchema, WorkerDescriptorSchema,
  type JobArtifact, type JobFailureClass, type JobLease, type JobLog, type JobRecord, type JobSpec, type WorkerDescriptor,
} from "../../domain/job.js";
import { ConfirmationTokenSchema, DataRoleManifestSchema, StudyDesignSchema } from "../../domain/study.js";
import { VisibilityEventSchema } from "../../domain/research.js";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";

interface JsonRow{payload_json:string}
interface LeaseRow{job_id:string;attempt:number;worker_id:string;token_hash:string;resources_json:string;expires_at:string}

export class JobStore{
  private constructor(private readonly db:Database.Database,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}

  static async open(path:string):Promise<JobStore>{
    mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");const version=db.pragma("user_version",{simple:true}) as number;
    if(version<12){db.close();throw new Error("Job store requires schema version 12 before migration");}if(version>16){db.close();throw new Error(`Job database ${version} is newer than supported version 16`);}
    let backup:string|null=null,manifest:string|null=null;if(version===12){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-012-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"012");try{applyMigrationTransaction(db,readFileSync(resolve("migrations/012_job_worker.sql"),"utf8"));}catch(error){db.close();throw error;}}
    return new JobStore(db,backup,manifest);
  }
  close():void{this.db.close();}

  submit(input:{workspaceId:string;projectId:string;spec:unknown;confirmationToken?:string|null}):JobRecord{
    const spec=JobSpecSchema.parse(input.spec);this.assertProject(input.workspaceId,input.projectId);this.assertSafeEnvironment(spec);
    const now=new Date().toISOString(),job=JobRecordSchema.parse({id:`job-${randomUUID()}`,workspaceId:input.workspaceId,projectId:input.projectId,status:"queued",spec,currentAttempt:0,cancelRequested:false,failureClass:null,failureMessage:null,createdAt:now,updatedAt:now,startedAt:null,finishedAt:null});
    const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO research_jobs_v15(id,workspace_id,project_id,status,data_role,priority,available_at,cancel_requested,current_attempt,payload_json,created_at,updated_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NULL)").run(job.id,job.workspaceId,job.projectId,job.status,spec.dataRole,spec.priority,now,0,0,JSON.stringify(job),now,now);if(spec.dataRole==="confirmation")this.reserveConfirmationTx(job,spec.studyId!,input.confirmationToken);else if(input.confirmationToken)throw new Error("Exploration jobs must not provide a confirmation token");});tx();return job;
  }

  job(workspaceId:string,projectId:string,jobId:string):JobRecord{const job=this.jobTx(jobId);if(job.workspaceId!==workspaceId||job.projectId!==projectId)throw new Error("Job does not belong to this project and workspace");return job;}
  artifacts(workspaceId:string,projectId:string,jobId:string):JobArtifact[]{this.job(workspaceId,projectId,jobId);return(this.db.prepare("SELECT * FROM job_artifacts_v15 WHERE job_id=? ORDER BY name").all(jobId) as Array<Record<string,unknown>>).map(row=>JobArtifactSchema.parse({id:row.id,jobId:row.job_id,attempt:row.attempt,name:row.name,mediaType:row.media_type,contentHash:row.content_hash,bytes:row.bytes,uri:row.uri,access:row.access,createdAt:row.created_at}));}
  logs(workspaceId:string,projectId:string,jobId:string,fromSequence=1,limit=200):JobLog[]{this.job(workspaceId,projectId,jobId);return(this.db.prepare("SELECT id,job_id,attempt,sequence,stream,message,data_json,created_at FROM job_logs_v15 WHERE job_id=? AND sequence>=? ORDER BY sequence LIMIT ?").all(jobId,fromSequence,limit) as Array<Record<string,any>>).map(row=>JobLogSchema.parse({id:row.id,jobId:row.job_id,attempt:row.attempt,sequence:row.sequence,stream:row.stream,message:row.message,data:row.data_json===null?null:JSON.parse(row.data_json),createdAt:row.created_at}));}

  cancel(workspaceId:string,projectId:string,jobId:string):JobRecord{const current=this.job(workspaceId,projectId,jobId);if(["succeeded","failed","cancelled"].includes(current.status))return current;const now=new Date().toISOString();if(current.status==="queued")return this.updateJob({...current,status:"cancelled",cancelRequested:true,failureClass:"cancelled",failureMessage:"Cancelled before execution",updatedAt:now,finishedAt:now});return this.updateJob({...current,cancelRequested:true,updatedAt:now});}

  retry(workspaceId:string,projectId:string,jobId:string):JobRecord{const current=this.job(workspaceId,projectId,jobId);if(!["failed","cancelled"].includes(current.status))throw new Error("Only failed or cancelled jobs can be retried");if(current.spec.execution.kind!=="pi"&&current.spec.execution.workspace==="[source-workspace-redacted]")throw new Error("Imported Job requires explicit execution environment rebinding before retry");if(current.currentAttempt>=current.spec.maxAttempts)throw new Error("Job retry exceeds maxAttempts");const now=new Date().toISOString();return this.updateJob({...current,status:"queued",cancelRequested:false,failureClass:null,failureMessage:null,updatedAt:now,finishedAt:null});}

  claim(rawWorker:unknown,nowDate=new Date()):JobLease|null{
    const worker=WorkerDescriptorSchema.parse(rawWorker),now=nowDate.toISOString();return this.db.transaction(()=>{this.recoverExpiredTx(nowDate);const active=this.activeWorkerLeasesTx(worker.workerId,nowDate),used=this.sumResources(active),usedGpus=new Set(active.flatMap(item=>(JSON.parse(item.resources_json) as{gpuDevices:string[]}).gpuDevices));const candidates=(this.db.prepare("SELECT payload_json FROM research_jobs_v15 WHERE status='queued' AND cancel_requested=0 AND available_at<=? ORDER BY priority DESC,created_at").all(now) as JsonRow[]).map(row=>JobRecordSchema.parse(JSON.parse(row.payload_json)));
      const job=candidates.find(item=>worker.executors.includes(item.spec.execution.kind)&&this.fits(item.spec.resources,worker,used,usedGpus));if(!job)return null;const attempt=job.currentAttempt+1;if(attempt>job.spec.maxAttempts){this.updateJobTx({...job,status:"failed",failureClass:"worker_lost",failureMessage:"No attempts remain",updatedAt:now,finishedAt:now});return null;}
      const allocatedGpuDevices=worker.gpuDevices.filter(device=>!usedGpus.has(device)).slice(0,job.spec.resources.gpuCount),authorizedMounts=job.spec.dataRole==="confirmation"?this.consumeConfirmationGrantTx(job,now):[];
      const token=randomBytes(32).toString("hex"),expiresAt=new Date(nowDate.getTime()+worker.leaseDurationMs).toISOString(),running=JobRecordSchema.parse({...job,status:"running",currentAttempt:attempt,cancelRequested:false,startedAt:job.startedAt??now,updatedAt:now,finishedAt:null,failureClass:null,failureMessage:null});this.updateJobTx(running);
      this.db.prepare("INSERT INTO job_attempts_v15(id,job_id,attempt,status,worker_id,started_at) VALUES(?,?,?,?,?,?)").run(`attempt-${randomUUID()}`,job.id,attempt,"running",worker.workerId,now);
      this.db.prepare("INSERT INTO job_leases_v15(job_id,attempt,worker_id,token_hash,resources_json,acquired_at,heartbeat_at,expires_at) VALUES(?,?,?,?,?,?,?,?)").run(job.id,attempt,worker.workerId,this.hashToken(token),JSON.stringify({...job.spec.resources,gpuDevices:allocatedGpuDevices}),now,now,expiresAt);
      this.appendLogTx(job.id,attempt,"system",`Lease acquired by ${worker.workerId}`,{expiresAt,allocatedGpuDevices});return JobLeaseSchema.parse({protocolVersion:"1",job:running,attempt,leaseToken:token,expiresAt,allocatedGpuDevices,authorizedMounts});})();
  }

  heartbeat(input:{jobId:string;attempt:number;workerId:string;leaseToken:string;leaseDurationMs:number},nowDate=new Date()):{cancelRequested:boolean;expiresAt:string}{return this.db.transaction(()=>{const lease=this.requireLeaseTx(input);const job=this.jobTx(input.jobId),now=nowDate.toISOString(),expiresAt=new Date(nowDate.getTime()+input.leaseDurationMs).toISOString();if(new Date(lease.expires_at)<=nowDate)throw new Error("Job lease has expired");this.db.prepare("UPDATE job_leases_v15 SET heartbeat_at=?,expires_at=? WHERE job_id=?").run(now,expiresAt,input.jobId);return{cancelRequested:job.cancelRequested,expiresAt};})();}

  appendLog(input:{jobId:string;attempt:number;workerId:string;leaseToken:string;stream:"stdout"|"stderr"|"progress"|"system";message:string;data?:unknown}):JobLog{return this.db.transaction(()=>{this.requireLeaseTx(input);return this.appendLogTx(input.jobId,input.attempt,input.stream,input.message,input.data??null);})();}

  complete(input:{jobId:string;attempt:number;workerId:string;leaseToken:string;artifacts:unknown[]}):JobRecord{return this.db.transaction(()=>{this.requireLeaseTx(input);const current=this.jobTx(input.jobId);if(current.cancelRequested)throw new Error("Cancelled job cannot be completed");const artifacts=input.artifacts.map(raw=>JobArtifactSchema.omit({id:true,jobId:true,attempt:true,createdAt:true}).parse(raw)),now=new Date().toISOString();for(const artifact of artifacts){const item=JobArtifactSchema.parse({...artifact,id:`artifact-${randomUUID()}`,jobId:current.id,attempt:input.attempt,createdAt:now});this.db.prepare("INSERT INTO job_artifacts_v15(id,job_id,attempt,name,media_type,content_hash,bytes,uri,access,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(item.id,item.jobId,item.attempt,item.name,item.mediaType,item.contentHash,item.bytes,item.uri,item.access,item.createdAt);}this.db.prepare("UPDATE job_attempts_v15 SET status='succeeded',finished_at=? WHERE job_id=? AND attempt=?").run(now,current.id,input.attempt);this.db.prepare("DELETE FROM job_leases_v15 WHERE job_id=?").run(current.id);this.appendLogTx(current.id,input.attempt,"system","Job completed",{artifactCount:artifacts.length});return this.updateJobTx({...current,status:"succeeded",updatedAt:now,finishedAt:now,failureClass:null,failureMessage:null});})();}

  fail(input:{jobId:string;attempt:number;workerId:string;leaseToken:string;failureClass:JobFailureClass;message:string}):JobRecord{return this.db.transaction(()=>{this.requireLeaseTx(input);const current=this.jobTx(input.jobId),now=new Date().toISOString(),status=input.failureClass==="cancelled"?"cancelled" as const:"failed" as const;this.db.prepare("UPDATE job_attempts_v15 SET status=?,failure_class=?,failure_message=?,finished_at=? WHERE job_id=? AND attempt=?").run(status,input.failureClass,input.message,now,current.id,input.attempt);this.db.prepare("DELETE FROM job_leases_v15 WHERE job_id=?").run(current.id);this.appendLogTx(current.id,input.attempt,"system",`Job ${status}: ${input.message}`,{failureClass:input.failureClass});return this.updateJobTx({...current,status,cancelRequested:input.failureClass==="cancelled"||current.cancelRequested,failureClass:input.failureClass,failureMessage:input.message,updatedAt:now,finishedAt:now});})();}

  recoverExpired(nowDate=new Date()):JobRecord[]{return this.db.transaction(()=>this.recoverExpiredTx(nowDate))();}

  private recoverExpiredTx(nowDate:Date):JobRecord[]{const now=nowDate.toISOString(),rows=this.db.prepare("SELECT job_id,attempt,worker_id,token_hash,resources_json,expires_at FROM job_leases_v15 WHERE expires_at<=? ORDER BY expires_at").all(now) as LeaseRow[],recovered:JobRecord[]=[];for(const lease of rows){const current=this.jobTx(lease.job_id);if(current.status!=="running"){this.db.prepare("DELETE FROM job_leases_v15 WHERE job_id=?").run(current.id);continue;}const canResume=current.spec.resumable&&current.currentAttempt<current.spec.maxAttempts&&!current.cancelRequested,next=JobRecordSchema.parse({...current,status:canResume?"queued":current.cancelRequested?"cancelled":"failed",failureClass:canResume?null:current.cancelRequested?"cancelled":"worker_lost",failureMessage:canResume?null:current.cancelRequested?"Cancelled after worker lease expired":"Worker lease expired and job cannot resume",updatedAt:now,finishedAt:canResume?null:now});this.db.prepare("UPDATE job_attempts_v15 SET status='worker_lost',failure_class='worker_lost',failure_message='Worker lease expired',finished_at=? WHERE job_id=? AND attempt=?").run(now,current.id,lease.attempt);this.db.prepare("DELETE FROM job_leases_v15 WHERE job_id=?").run(current.id);this.appendLogTx(current.id,lease.attempt,"system",canResume?"Expired lease recovered; job requeued":"Expired lease closed job",{workerId:lease.worker_id});recovered.push(this.updateJobTx(next));}return recovered;}

  private reserveConfirmationTx(job:JobRecord,studyId:string,token:string|null|undefined):void{if(!token)throw new Error("Confirmation job requires a confirmation token");const row=this.db.prepare("SELECT c.id,c.payload_json,s.payload_json study_json FROM confirmation_tokens c JOIN studies s ON s.id=c.study_id WHERE c.study_id=?").get(studyId) as{id:string;payload_json:string;study_json:string}|undefined;if(!row)throw new Error("Confirmation token was not issued");const record=ConfirmationTokenSchema.parse(JSON.parse(row.payload_json)),study=StudyDesignSchema.parse(JSON.parse(row.study_json));if(study.programId!==job.projectId)throw new Error("Confirmation study does not belong to the job project");if(study.status!=="confirmation_ready"||record.status!=="issued")throw new Error("Confirmation capability is not available");if(this.db.prepare("SELECT 1 ok FROM job_confirmation_grants_v15 WHERE token_id=?").get(record.id))throw new Error("Confirmation capability is already reserved by another job");const tokenHash=this.hashToken(token);if(tokenHash!==record.tokenHash)throw new Error("Invalid confirmation token");this.db.prepare("INSERT INTO job_confirmation_grants_v15(job_id,study_id,token_id,token_hash,status) VALUES(?,?,?,?,?)").run(job.id,studyId,record.id,tokenHash,"reserved");}

  private consumeConfirmationGrantTx(job:JobRecord,now:string):Array<{source:string;target:string}>{const grant=this.db.prepare("SELECT * FROM job_confirmation_grants_v15 WHERE job_id=?").get(job.id) as{study_id:string;token_id:string;token_hash:string;status:string}|undefined;if(!grant)throw new Error("Confirmation job has no reserved capability");const tokenRow=this.db.prepare("SELECT payload_json FROM confirmation_tokens WHERE id=?").get(grant.token_id) as JsonRow|undefined;if(!tokenRow)throw new Error("Confirmation token disappeared");const token=ConfirmationTokenSchema.parse(JSON.parse(tokenRow.payload_json));if(grant.status==="consumed"){const role=this.confirmationRoleTx(grant.study_id);return[{source:role.path,target:"/data/confirmation"}];}if(token.status!=="issued"||token.tokenHash!==grant.token_hash)throw new Error("Confirmation capability is no longer valid");const studyRow=this.db.prepare("SELECT payload_json FROM studies WHERE id=?").get(grant.study_id) as JsonRow,study=StudyDesignSchema.parse(JSON.parse(studyRow.payload_json)),role=this.confirmationRoleTx(grant.study_id),consumed=ConfirmationTokenSchema.parse({...token,status:"consumed",consumedAt:now,runId:job.id}),visibility=VisibilityEventSchema.parse({id:`visibility-${randomUUID()}`,programId:study.programId,runId:job.id,dataRole:"confirmation",artifactHash:role.manifestHash,observedAt:now}),updatedStudy=StudyDesignSchema.parse({...study,status:"confirmation_consumed",updatedAt:now});this.db.prepare("UPDATE confirmation_tokens SET status='consumed',payload_json=?,consumed_at=? WHERE id=?").run(JSON.stringify(consumed),now,token.id);this.db.prepare("UPDATE job_confirmation_grants_v15 SET status='consumed',consumed_at=? WHERE job_id=?").run(now,job.id);this.db.prepare("INSERT INTO research_visibility_events(id,program_id,run_id,data_role,artifact_hash,payload_json,observed_at) VALUES(?,?,?,?,?,?,?)").run(visibility.id,visibility.programId,visibility.runId,visibility.dataRole,visibility.artifactHash,JSON.stringify(visibility),now);this.db.prepare("UPDATE research_programs SET status='confirmation_observed',payload_json=json_set(payload_json,'$.status','confirmation_observed','$.updatedAt',?),updated_at=? WHERE id=?").run(now,now,study.programId);this.db.prepare("UPDATE studies SET status=?,payload_json=?,updated_at=? WHERE id=?").run(updatedStudy.status,JSON.stringify(updatedStudy),now,study.id);return[{source:role.path,target:"/data/confirmation"}];}

  private confirmationRoleTx(studyId:string){const row=this.db.prepare("SELECT payload_json FROM study_data_roles WHERE study_id=? AND role='confirmation'").get(studyId) as JsonRow|undefined;if(!row)throw new Error("Confirmation data role is missing");return DataRoleManifestSchema.parse(JSON.parse(row.payload_json));}
  private appendLogTx(jobId:string,attempt:number,stream:JobLog["stream"],message:string,data:unknown):JobLog{const sequence=(this.db.prepare("SELECT COALESCE(MAX(sequence),0)+1 next FROM job_logs_v15 WHERE job_id=?").get(jobId) as{next:number}).next,log=JobLogSchema.parse({id:`job-log-${randomUUID()}`,jobId,attempt,sequence,stream,message,data:data??null,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO job_logs_v15(id,job_id,attempt,sequence,stream,message,data_json,created_at) VALUES(?,?,?,?,?,?,?,?)").run(log.id,log.jobId,log.attempt,log.sequence,log.stream,log.message,log.data===null?null:JSON.stringify(log.data),log.createdAt);return log;}
  private requireLeaseTx(input:{jobId:string;attempt:number;workerId:string;leaseToken:string}):LeaseRow{const lease=this.db.prepare("SELECT job_id,attempt,worker_id,token_hash,resources_json,expires_at FROM job_leases_v15 WHERE job_id=?").get(input.jobId) as LeaseRow|undefined;if(!lease||lease.attempt!==input.attempt||lease.worker_id!==input.workerId||lease.token_hash!==this.hashToken(input.leaseToken)||new Date(lease.expires_at)<=new Date())throw new Error("Invalid, expired, or stale job lease");return lease;}
  private activeWorkerLeasesTx(workerId:string,now:Date):LeaseRow[]{return this.db.prepare("SELECT job_id,attempt,worker_id,token_hash,resources_json,expires_at FROM job_leases_v15 WHERE worker_id=? AND expires_at>?").all(workerId,now.toISOString()) as LeaseRow[];}
  private sumResources(rows:LeaseRow[]):{cpuCores:number;memoryMiB:number;diskMiB:number;gpuCount:number}{return rows.reduce((sum,row)=>{const value=JSON.parse(row.resources_json) as{cpuCores:number;memoryMiB:number;diskMiB:number;gpuCount:number};return{cpuCores:sum.cpuCores+value.cpuCores,memoryMiB:sum.memoryMiB+value.memoryMiB,diskMiB:sum.diskMiB+value.diskMiB,gpuCount:sum.gpuCount+value.gpuCount};},{cpuCores:0,memoryMiB:0,diskMiB:0,gpuCount:0});}
  private fits(resources:JobSpec["resources"],worker:WorkerDescriptor,used:ReturnType<JobStore["sumResources"]>,usedGpus:Set<string>):boolean{return resources.cpuCores+used.cpuCores<=worker.capacity.cpuCores&&resources.memoryMiB+used.memoryMiB<=worker.capacity.memoryMiB&&resources.diskMiB+used.diskMiB<=worker.capacity.diskMiB&&resources.gpuCount+used.gpuCount<=worker.capacity.gpuCount&&worker.gpuDevices.filter(device=>!usedGpus.has(device)).length>=resources.gpuCount;}
  private updateJob(job:JobRecord):JobRecord{return this.db.transaction(()=>this.updateJobTx(JobRecordSchema.parse(job)))();}
  private updateJobTx(job:JobRecord):JobRecord{this.db.prepare("UPDATE research_jobs_v15 SET status=?,cancel_requested=?,current_attempt=?,payload_json=?,updated_at=?,finished_at=? WHERE id=?").run(job.status,job.cancelRequested?1:0,job.currentAttempt,JSON.stringify(job),job.updatedAt,job.finishedAt,job.id);return job;}
  private jobTx(id:string):JobRecord{const row=this.db.prepare("SELECT payload_json FROM research_jobs_v15 WHERE id=?").get(id) as JsonRow|undefined;if(!row)throw new Error(`Unknown job ${id}`);return JobRecordSchema.parse(JSON.parse(row.payload_json));}
  private assertProject(workspaceId:string,projectId:string):void{const row=this.db.prepare("SELECT workspace_id FROM research_projects_v15 WHERE id=?").get(projectId) as{workspace_id:string}|undefined;if(!row)throw new Error(`Unknown project ${projectId}`);if(row.workspace_id!==workspaceId)throw new Error("Project does not belong to this workspace");}
  private assertSafeEnvironment(spec:JobSpec):void{if("env" in spec.execution)for(const key of Object.keys(spec.execution.env))if(/KEY|TOKEN|SECRET|PASSWORD/i.test(key))throw new Error(`Secret-like job environment variable blocked: ${key}`);}
  private hashToken(token:string):string{return createHash("sha256").update(token).digest("hex");}
}
