import Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  PluginDescriptorSchema, PluginInstallationSchema, PluginPermissionSchema, PluginSourceSchema, permissionDiff,
  type PluginDescriptor, type PluginInstallation, type PluginPermission, type PluginSource,
} from "../../domain/plugin.js";
import { PiPluginBridge } from "../../runtime/pi-plugin-bridge.js";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";
import { readMigration } from "./migration-path.js";

interface JsonRow{payload_json:string}
export interface PluginSearchFilters{domain?:string;permission?:PluginPermission;sourceKind?:PluginSource["kind"];compatibleOnly?:boolean;contribution?:"skills"|"tools"|"apps"|"mcp"|"scenarios"}

export class PluginStore{
  private constructor(private readonly db:Database.Database,private readonly bridge:PiPluginBridge,private readonly cacheRoot:string,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}
  static async open(path:string,options:{cacheRoot?:string;bridge?:PiPluginBridge}={}):Promise<PluginStore>{mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");const version=db.pragma("user_version",{simple:true}) as number;if(version<13){db.close();throw new Error("Plugin store requires schema version 13 before migration");}if(version>17){db.close();throw new Error(`Plugin database ${version} is newer than supported version 17`);}let backup:string|null=null,manifest:string|null=null;if(version===13){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-013-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"013");try{applyMigrationTransaction(db,readMigration("013_scenarios_plugins.sql"));}catch(error){db.close();throw error;}}const cacheRoot=resolve(options.cacheRoot??dirname(path),"plugin-cache");mkdirSync(cacheRoot,{recursive:true});return new PluginStore(db,options.bridge??new PiPluginBridge(join(cacheRoot,"sources")),cacheRoot,backup,manifest);}
  close():void{this.db.close();}

  addSource(input:{workspaceId:string;kind:PluginSource["kind"];location:string;label:string}):PluginSource{this.assertWorkspace(input.workspaceId);const now=new Date().toISOString(),source=PluginSourceSchema.parse({...input,id:`plugin-source-${randomUUID()}`,status:"active",createdAt:now,updatedAt:now});this.db.prepare("INSERT INTO plugin_sources_v15(id,workspace_id,kind,location,label,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(source.id,source.workspaceId,source.kind,source.location,source.label,source.status,JSON.stringify(source),now,now);return source;}
  source(workspaceId:string,sourceId:string):PluginSource{const row=this.db.prepare("SELECT payload_json FROM plugin_sources_v15 WHERE id=?").get(sourceId) as JsonRow|undefined;if(!row)throw new Error(`Unknown plugin source ${sourceId}`);const source=PluginSourceSchema.parse(JSON.parse(row.payload_json));if(source.workspaceId!==workspaceId)throw new Error("Plugin source does not belong to this workspace");return source;}
  sources(workspaceId:string):PluginSource[]{this.assertWorkspace(workspaceId);return(this.db.prepare("SELECT payload_json FROM plugin_sources_v15 WHERE workspace_id=? ORDER BY created_at").all(workspaceId) as JsonRow[]).map(row=>PluginSourceSchema.parse(JSON.parse(row.payload_json)));}
  refresh(workspaceId:string,sourceId:string):{source:PluginSource;descriptors:PluginDescriptor[];issues:string[]}{const source=this.source(workspaceId,sourceId);if(source.status==="disabled")throw new Error("Disabled plugin source cannot be refreshed");const result=this.bridge.discover(source),now=new Date().toISOString(),updated=PluginSourceSchema.parse({...source,status:result.descriptors.length?"active":"unavailable",updatedAt:now});this.db.transaction(()=>{this.db.prepare("UPDATE plugin_sources_v15 SET status=?,payload_json=?,updated_at=? WHERE id=?").run(updated.status,JSON.stringify(updated),now,source.id);for(const descriptor of result.descriptors)this.db.prepare("INSERT OR IGNORE INTO plugin_catalog_v15(descriptor_id,workspace_id,source_id,plugin_id,version,content_hash,compatibility_status,payload_json,discovered_at) VALUES(?,?,?,?,?,?,?,?,?)").run(descriptor.descriptorId,workspaceId,source.id,descriptor.pluginId,descriptor.version,descriptor.contentHash,descriptor.compatibilityStatus,JSON.stringify(descriptor),descriptor.discoveredAt);})();return{source:updated,descriptors:result.descriptors,issues:result.issues};}

  search(workspaceId:string,query:string,filters:PluginSearchFilters={}):PluginDescriptor[]{this.assertWorkspace(workspaceId);const needle=query.trim().toLowerCase();return(this.db.prepare("SELECT payload_json FROM plugin_catalog_v15 WHERE workspace_id=? ORDER BY discovered_at DESC").all(workspaceId) as JsonRow[]).map(row=>PluginDescriptorSchema.parse(JSON.parse(row.payload_json))).filter((item,index,all)=>all.findIndex(other=>other.descriptorId===item.descriptorId)===index).filter(item=>!needle||[item.pluginId,item.name,item.description,...item.domain,...Object.values(item.contributions).flat()].some(value=>value.toLowerCase().includes(needle))).filter(item=>!filters.domain||item.domain.includes(filters.domain)).filter(item=>!filters.permission||item.permissions.includes(filters.permission)).filter(item=>!filters.sourceKind||item.sourceKind===filters.sourceKind).filter(item=>!filters.compatibleOnly||item.compatibilityStatus==="compatible").filter(item=>!filters.contribution||item.contributions[filters.contribution].length>0);}
  descriptor(workspaceId:string,descriptorId:string):PluginDescriptor{const row=this.db.prepare("SELECT payload_json FROM plugin_catalog_v15 WHERE descriptor_id=? AND workspace_id=?").get(descriptorId,workspaceId) as JsonRow|undefined;if(!row)throw new Error(`Unknown plugin descriptor ${descriptorId}`);return PluginDescriptorSchema.parse(JSON.parse(row.payload_json));}

  install(input:{workspaceId:string;projectId:string|null;scope:"project"|"workspace";descriptorId:string;approvedPermissions:PluginPermission[];actorId:string}):PluginInstallation{this.assertScope(input.workspaceId,input.projectId,input.scope);const descriptor=this.descriptor(input.workspaceId,input.descriptorId);if(descriptor.compatibilityStatus!=="compatible")throw new Error(`Plugin is incompatible: ${descriptor.compatibilityIssues.join("; ")}`);this.assertExactPermissions(descriptor.permissions,input.approvedPermissions);const existing=this.db.prepare("SELECT 1 ok FROM plugin_installations_v15 WHERE workspace_id=? AND plugin_id=? AND scope=? AND project_id IS ? AND status!='removed'").get(input.workspaceId,descriptor.pluginId,input.scope,input.projectId);if(existing)throw new Error("Plugin is already installed in this scope");const source=this.source(input.workspaceId,descriptor.sourceId);if(source.status!=="active"||!this.bridge.verify(descriptor,source))throw new Error("Plugin source changed or is unavailable; refresh before installation");const cachePath=this.bridge.materialize(descriptor,this.cacheRoot),now=new Date().toISOString(),installation=PluginInstallationSchema.parse({id:`plugin-installation-${randomUUID()}`,workspaceId:input.workspaceId,projectId:input.projectId,scope:input.scope,pluginId:descriptor.pluginId,version:descriptor.version,contentHash:descriptor.contentHash,sourceId:descriptor.sourceId,descriptorId:descriptor.descriptorId,status:"installed",approvedPermissions:input.approvedPermissions,cachePath,installedAt:now,updatedAt:now});this.db.transaction(()=>{this.insertInstallationTx(installation);this.lifecycleTx(installation.id,"installed",input.actorId,{descriptorId:descriptor.descriptorId,permissions:installation.approvedPermissions,contentHash:installation.contentHash});})();return installation;}

  enable(input:{workspaceId:string;installationId:string;actorId:string}):PluginInstallation{const current=this.installation(input.workspaceId,input.installationId);if(current.status==="removed")throw new Error("Removed plugin cannot be enabled");const descriptor=this.descriptor(input.workspaceId,current.descriptorId),source=this.source(input.workspaceId,current.sourceId);if(descriptor.compatibilityStatus!=="compatible")return this.setStatus(current,"incompatible",input.actorId,{issues:descriptor.compatibilityIssues});if(source.status!=="active"||!this.bridge.verify(descriptor,source)){this.setStatus(current,"quarantined",input.actorId,{reason:"source_hash_mismatch_or_unavailable"});throw new Error("Plugin content no longer matches the installed lock and was quarantined");}this.assertExactPermissions(descriptor.permissions,current.approvedPermissions);return this.setStatus(current,"enabled",input.actorId,{contentHash:current.contentHash});}
  disable(workspaceId:string,installationId:string,actorId:string):PluginInstallation{const current=this.installation(workspaceId,installationId);if(current.status==="removed")throw new Error("Removed plugin cannot be disabled");return this.setStatus(current,"disabled",actorId,{});}
  remove(workspaceId:string,installationId:string,actorId:string):PluginInstallation{const current=this.installation(workspaceId,installationId);if(current.status==="removed")return current;return this.setStatus(current,"removed",actorId,{historyRetained:true});}

  update(input:{workspaceId:string;installationId:string;targetDescriptorId:string;approvedPermissions:PluginPermission[];actorId:string}):{installation:PluginInstallation;permissionDiff:ReturnType<typeof permissionDiff>}{const current=this.installation(input.workspaceId,input.installationId),target=this.descriptor(input.workspaceId,input.targetDescriptorId);if(current.status==="removed")throw new Error("Removed plugin cannot be updated");if(target.pluginId!==current.pluginId)throw new Error("Plugin update target has a different identity");if(target.compatibilityStatus!=="compatible")throw new Error(`Plugin update is incompatible: ${target.compatibilityIssues.join("; ")}`);const diff=permissionDiff(current.approvedPermissions,target.permissions);this.assertExactPermissions(target.permissions,input.approvedPermissions);const source=this.source(input.workspaceId,target.sourceId);if(source.status!=="active"||!this.bridge.verify(target,source))throw new Error("Plugin update source changed or is unavailable");const cachePath=this.bridge.materialize(target,this.cacheRoot),now=new Date().toISOString(),updated=PluginInstallationSchema.parse({...current,version:target.version,contentHash:target.contentHash,sourceId:target.sourceId,descriptorId:target.descriptorId,status:"installed",approvedPermissions:input.approvedPermissions,cachePath,updatedAt:now});this.db.transaction(()=>{this.updateInstallationTx(updated);this.lifecycleTx(updated.id,"updated",input.actorId,{from:{version:current.version,contentHash:current.contentHash},to:{version:updated.version,contentHash:updated.contentHash},permissionDiff:diff});})();return{installation:updated,permissionDiff:diff};}

  installation(workspaceId:string,id:string):PluginInstallation{const row=this.db.prepare("SELECT payload_json FROM plugin_installations_v15 WHERE id=?").get(id) as JsonRow|undefined;if(!row)throw new Error(`Unknown plugin installation ${id}`);const item=PluginInstallationSchema.parse(JSON.parse(row.payload_json));if(item.workspaceId!==workspaceId)throw new Error("Plugin installation does not belong to this workspace");return item;}
  installations(workspaceId:string,projectId?:string|null):PluginInstallation[]{this.assertWorkspace(workspaceId);const rows=(projectId===undefined?this.db.prepare("SELECT payload_json FROM plugin_installations_v15 WHERE workspace_id=? ORDER BY installed_at").all(workspaceId):this.db.prepare("SELECT payload_json FROM plugin_installations_v15 WHERE workspace_id=? AND (project_id IS ? OR scope='workspace') ORDER BY installed_at").all(workspaceId,projectId??null)) as JsonRow[];return rows.map(row=>PluginInstallationSchema.parse(JSON.parse(row.payload_json)));}
  runtimeSelection(workspaceId:string,projectId:string):Array<{installationId:string;pluginId:string;version:string;contentHash:string;cachePath:string;permissions:PluginPermission[];contributions:PluginDescriptor["contributions"]}>{this.assertScope(workspaceId,projectId,"project");const enabled=this.installations(workspaceId,projectId).filter(item=>item.status==="enabled"&&item.cachePath!==null);if(this.db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name='project_plugin_requirements_v15'").get()){const requirements=this.db.prepare("SELECT id,plugin_id,version,content_hash FROM project_plugin_requirements_v15 WHERE project_id=?").all(projectId) as Array<{id:string;plugin_id:string;version:string;content_hash:string}>,now=new Date().toISOString();for(const requirement of requirements){const same=enabled.find(item=>item.pluginId===requirement.plugin_id&&item.version===requirement.version&&item.contentHash===requirement.content_hash),identity=enabled.some(item=>item.pluginId===requirement.plugin_id),status=same?"available":identity?"incompatible":"missing";this.db.prepare("UPDATE project_plugin_requirements_v15 SET status=?,updated_at=? WHERE id=?").run(status,now,requirement.id);if(status!=="available")throw new Error(`Plugin capability unavailable: ${requirement.plugin_id}@${requirement.version} is ${status}`);}}return enabled.map(item=>{const descriptor=this.descriptor(workspaceId,item.descriptorId),source=this.source(workspaceId,item.sourceId);if(source.status!=="active")throw new Error(`Plugin capability unavailable because source ${source.id} is ${source.status}`);return{installationId:item.id,pluginId:item.pluginId,version:item.version,contentHash:item.contentHash,cachePath:item.cachePath!,permissions:item.approvedPermissions,contributions:descriptor.contributions};});}

  private setStatus(current:PluginInstallation,status:PluginInstallation["status"],actorId:string,details:unknown):PluginInstallation{const updated=PluginInstallationSchema.parse({...current,status,updatedAt:new Date().toISOString()});this.db.transaction(()=>{this.updateInstallationTx(updated);this.lifecycleTx(updated.id,status,actorId,details);})();return updated;}
  private insertInstallationTx(item:PluginInstallation):void{this.db.prepare("INSERT INTO plugin_installations_v15(id,workspace_id,project_id,scope,plugin_id,version,content_hash,source_id,descriptor_id,status,approved_permissions_json,cache_path,payload_json,installed_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(item.id,item.workspaceId,item.projectId,item.scope,item.pluginId,item.version,item.contentHash,item.sourceId,item.descriptorId,item.status,JSON.stringify(item.approvedPermissions),item.cachePath,JSON.stringify(item),item.installedAt,item.updatedAt);}
  private updateInstallationTx(item:PluginInstallation):void{this.db.prepare("UPDATE plugin_installations_v15 SET version=?,content_hash=?,source_id=?,descriptor_id=?,status=?,approved_permissions_json=?,cache_path=?,payload_json=?,updated_at=? WHERE id=?").run(item.version,item.contentHash,item.sourceId,item.descriptorId,item.status,JSON.stringify(item.approvedPermissions),item.cachePath,JSON.stringify(item),item.updatedAt,item.id);}
  private lifecycleTx(installationId:string,action:string,actorId:string,details:unknown):void{const now=new Date().toISOString(),payload={installationId,action,actorId,details,createdAt:now};this.db.prepare("INSERT INTO plugin_lifecycle_v15(id,installation_id,action,actor_id,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(`plugin-event-${randomUUID()}`,installationId,action,actorId,JSON.stringify(payload),now);}
  private assertExactPermissions(required:PluginPermission[],approved:PluginPermission[]):void{const normalized=[...new Set(approved.map(item=>PluginPermissionSchema.parse(item)))].sort(),expected=[...new Set(required)].sort();if(JSON.stringify(normalized)!==JSON.stringify(expected))throw new Error(`Plugin permissions require explicit exact approval: ${expected.join(", ")}`);}
  private assertScope(workspaceId:string,projectId:string|null,scope:"project"|"workspace"):void{this.assertWorkspace(workspaceId);if(scope==="project"){if(!projectId)throw new Error("Project-scoped plugin requires projectId");const row=this.db.prepare("SELECT workspace_id FROM research_projects_v15 WHERE id=?").get(projectId) as{workspace_id:string}|undefined;if(!row||row.workspace_id!==workspaceId)throw new Error("Plugin project does not belong to this workspace");}else if(projectId!==null)throw new Error("Workspace-scoped plugin must not provide projectId");}
  private assertWorkspace(id:string):void{if(!this.db.prepare("SELECT 1 ok FROM workspaces WHERE id=?").get(id))throw new Error(`Unknown workspace ${id}`);}
}
