import Database from "better-sqlite3";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { ApprovalSchema, ResearchProgramSchema, ResearchQuestionSchema, hashPayload } from "../../domain/research.js";
import {
  CommandReceiptSchema, PersistedActorSchema, PersistedResearchEventSchema, ProjectBundleSchema, ProjectProjectionSchema,
  ProjectRecordSchema, WorkspaceRecordSchema, createProjectProjection,
  type CommandReceipt, type PersistedActor, type PersistedResearchEvent, type ProjectBundle, type ProjectProjection,
  type ProjectRecord, type WorkspaceRecord,
} from "../../domain/project.js";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";

interface JsonRow{payload_json:string}
export interface CommandActor{id:string;kind:"user"|"agent"|"worker"|"system";displayName?:string}
export interface PreparedCommand{kind:"new"|"replay";receipt:CommandReceipt}
export interface EventDraft{eventId:string;type:string;schemaVersion:string;actor:CommandActor;causationId:string;correlationId:string;payload:unknown;permissions?:string[];externalServices?:string[];occurredAt?:string;projectionPatch?:{researchStatus?:string}}

export class ProjectStore{
  private constructor(private readonly db:Database.Database,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}

  static async open(path:string):Promise<ProjectStore>{
    mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");
    const version=db.pragma("user_version",{simple:true}) as number;if(version<10){db.close();throw new Error("Project events require schema version 10 before migration");}if(version>15){db.close();throw new Error(`Project database ${version} is newer than supported version 15`);}
    let backup:string|null=null,manifest:string|null=null;if(version===10){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-010-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"010");try{applyMigrationTransaction(db,readFileSync(resolve("migrations/010_project_events.sql"),"utf8"));}catch(error){db.close();throw error;}}
    return new ProjectStore(db,backup,manifest);
  }
  close():void{this.db.close();}

  ensureWorkspace(id:string,name=id):WorkspaceRecord{
    const existing=this.workspace(id);if(existing)return existing;const now=new Date().toISOString(),body={id,name,status:"active" as const},record=WorkspaceRecordSchema.parse({...body,contentHash:hashPayload(body),createdAt:now,updatedAt:now});
    this.db.prepare("INSERT INTO workspaces(id,name,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(record.id,record.name,record.status,JSON.stringify(record),record.contentHash,record.createdAt,record.updatedAt);return record;
  }
  workspace(id:string):WorkspaceRecord|undefined{const row=this.db.prepare("SELECT payload_json FROM workspaces WHERE id=?").get(id) as JsonRow|undefined;return row?WorkspaceRecordSchema.parse(JSON.parse(row.payload_json)):undefined;}
  project(id:string):ProjectRecord|undefined{const row=this.db.prepare("SELECT payload_json FROM research_projects_v15 WHERE id=?").get(id) as JsonRow|undefined;return row?ProjectRecordSchema.parse(JSON.parse(row.payload_json)):undefined;}
  projection(id:string):ProjectProjection{const row=this.db.prepare("SELECT payload_json FROM project_projections_v15 WHERE project_id=?").get(id) as JsonRow|undefined;if(!row)throw new Error(`Unknown project projection ${id}`);return ProjectProjectionSchema.parse(JSON.parse(row.payload_json));}

  prepareCommand(input:{workspaceId:string;projectId:string|null;commandId:string;idempotencyKey:string;commandHash:string;actor:CommandActor}):PreparedCommand{
    this.ensureWorkspace(input.workspaceId);const scope=input.projectId??"__workspace__";const transaction=this.db.transaction(()=>{
      this.ensureActorTx(input.workspaceId,input.actor);if(input.projectId)this.assertProjectWorkspaceTx(input.projectId,input.workspaceId);
      const row=this.db.prepare("SELECT payload_json FROM command_receipts_v15 WHERE workspace_id=? AND project_scope=? AND idempotency_key=?").get(input.workspaceId,scope,input.idempotencyKey) as JsonRow|undefined;
      if(row){const receipt=CommandReceiptSchema.parse(JSON.parse(row.payload_json));if(receipt.commandHash!==input.commandHash)throw new Error("Idempotency key was already used for a different command");if(receipt.status==="pending")throw new Error(`Command ${receipt.commandId} is in doubt and requires reconciliation`);return{kind:"replay" as const,receipt};}
      const now=new Date().toISOString(),receipt=CommandReceiptSchema.parse({commandId:input.commandId,workspaceId:input.workspaceId,projectScope:scope,projectId:input.projectId,idempotencyKey:input.idempotencyKey,commandHash:input.commandHash,status:"pending",result:null,createdAt:now,completedAt:null});
      this.db.prepare("INSERT INTO command_receipts_v15(command_id,workspace_id,project_scope,project_id,idempotency_key,command_hash,status,result_json,payload_json,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(receipt.commandId,receipt.workspaceId,receipt.projectScope,receipt.projectId,receipt.idempotencyKey,receipt.commandHash,receipt.status,null,JSON.stringify(receipt),receipt.createdAt,null);return{kind:"new" as const,receipt};
    });return transaction();
  }

  completeProjectCreation(input:{receipt:CommandReceipt;projectId:string;branchName:string;researchStatus:string;result:unknown;event:EventDraft}):PersistedResearchEvent{
    const transaction=this.db.transaction(()=>{this.assertPendingTx(input.receipt.commandId);const project=this.makeProject({id:input.projectId,workspaceId:input.receipt.workspaceId,rootProjectId:input.projectId,parentProjectId:null,forkedFromEventId:null,branchName:input.branchName});this.insertProjectTx(project,input.researchStatus);const event=this.appendEventTx(project,input.event);this.completeReceiptTx(input.receipt.commandId,input.result);return event;});return transaction();
  }

  completeExistingCommand(input:{receipt:CommandReceipt;result:unknown;event?:EventDraft}):PersistedResearchEvent[]{
    const transaction=this.db.transaction(()=>{this.assertPendingTx(input.receipt.commandId);const events=input.event?[this.appendEventTx(this.requireProjectTx(input.receipt.projectId!),input.event)]:[];this.completeReceiptTx(input.receipt.commandId,input.result);return events;});return transaction();
  }

  completeFork(input:{receipt:CommandReceipt;childProjectId:string;branchName:string;researchStatus:string;result:unknown;parentEvent:EventDraft;childEvent:EventDraft}):PersistedResearchEvent[]{
    const transaction=this.db.transaction(()=>{this.assertPendingTx(input.receipt.commandId);const parent=this.requireProjectTx(input.receipt.projectId!),parentProjection=this.projectionTx(parent.id),child=this.makeProject({id:input.childProjectId,workspaceId:parent.workspaceId,rootProjectId:parent.rootProjectId,parentProjectId:parent.id,forkedFromEventId:parentProjection.lastSequence?this.eventAtTx(parent.id,parentProjection.lastSequence).eventId:null,branchName:input.branchName});this.insertProjectTx(child,input.researchStatus);const parentEvent=this.appendEventTx(parent,input.parentEvent),childEvent=this.appendEventTx(child,input.childEvent);this.completeReceiptTx(input.receipt.commandId,input.result);return[parentEvent,childEvent];});return transaction();
  }

  adoptLegacyProject(input:{projectId:string;workspaceId:string;branchName?:string;actor:CommandActor;schemaVersion:string}):ProjectRecord{
    this.ensureWorkspace(input.workspaceId);const existing=this.project(input.projectId);if(existing){if(existing.workspaceId!==input.workspaceId)throw new Error("Project already belongs to another workspace");return existing;}
    const transaction=this.db.transaction(()=>{if(!this.db.prepare("SELECT 1 ok FROM research_programs WHERE id=?").get(input.projectId))throw new Error(`Unknown research program ${input.projectId}`);this.ensureActorTx(input.workspaceId,input.actor);const program=this.programTx(input.projectId),project=this.makeProject({id:input.projectId,workspaceId:input.workspaceId,rootProjectId:input.projectId,parentProjectId:null,forkedFromEventId:null,branchName:input.branchName??"main"});this.insertProjectTx(project,program.status);this.appendEventTx(project,{eventId:`event-${randomUUID()}`,type:"project.adopted",schemaVersion:input.schemaVersion,actor:input.actor,causationId:`adopt-${randomUUID()}`,correlationId:input.projectId,payload:{projectId:input.projectId,branchName:project.branchName,projectionPatch:{researchStatus:program.status}}});return project;});return transaction();
  }

  events(projectId:string):PersistedResearchEvent[]{this.requireProjectTx(projectId);return(this.db.prepare("SELECT payload_json FROM research_events_v15 WHERE project_id=? ORDER BY sequence").all(projectId) as JsonRow[]).map(row=>this.upcastEvent(JSON.parse(row.payload_json)));}
  pendingReceipts(workspaceId?:string):CommandReceipt[]{const rows=(workspaceId?this.db.prepare("SELECT payload_json FROM command_receipts_v15 WHERE status='pending' AND workspace_id=? ORDER BY created_at").all(workspaceId):this.db.prepare("SELECT payload_json FROM command_receipts_v15 WHERE status='pending' ORDER BY created_at").all()) as JsonRow[];return rows.map(row=>CommandReceiptSchema.parse(JSON.parse(row.payload_json)));}

  auditProject(projectId:string):{status:"pass"|"fail";issues:string[]}{const project=this.requireProjectTx(projectId),events=this.events(projectId),projection=this.projection(projectId),stored=this.db.prepare("SELECT last_sequence,projection_hash FROM project_projections_v15 WHERE project_id=?").get(projectId) as{last_sequence:number;projection_hash:string},storedEvents=new Map((this.db.prepare("SELECT event_id,schema_version,payload_hash FROM research_events_v15 WHERE project_id=?").all(projectId) as Array<{event_id:string;schema_version:string;payload_hash:string}>).map(item=>[item.event_id,item])),issues:string[]=[];events.forEach((event,index)=>{if(event.sequence!==index+1)issues.push(`non_contiguous_sequence:${event.sequence}`);if(hashPayload(event.payload)!==event.payloadHash)issues.push(`payload_hash:${event.eventId}`);const row=storedEvents.get(event.eventId);if(row?.schema_version==="1.0.0"&&row.payload_hash!==event.payloadHash)issues.push(`stored_payload_hash:${event.eventId}`);if(event.workspaceId!==project.workspaceId)issues.push(`workspace_mismatch:${event.eventId}`);});if(projection.lastSequence!==events.length||projection.eventCount!==events.length||stored.last_sequence!==projection.lastSequence)issues.push("projection_sequence_mismatch");const rebuilt=this.computeProjection(project,events,this.programTx(projectId).status);if(rebuilt.projectionHash!==projection.projectionHash||stored.projection_hash!==projection.projectionHash)issues.push("projection_hash_mismatch");return{status:issues.length?"fail":"pass",issues:[...new Set(issues)]};}

  rebuildProjection(projectId:string):ProjectProjection{const project=this.requireProjectTx(projectId),events=this.events(projectId),rebuilt=this.computeProjection(project,events,this.programTx(projectId).status);this.db.prepare("UPDATE project_projections_v15 SET workspace_id=?,last_sequence=?,payload_json=?,projection_hash=?,updated_at=? WHERE project_id=?").run(rebuilt.workspaceId,rebuilt.lastSequence,JSON.stringify(rebuilt),rebuilt.projectionHash,rebuilt.updatedAt,projectId);return rebuilt;}

  exportBundle(projectId:string,publicSchemaVersion:string):ProjectBundle{
    const project=this.requireProjectTx(projectId);this.assertScopeBundleSupportedTx(projectId);const program=this.programTx(projectId),questions=this.jsonRows("SELECT payload_json FROM research_questions WHERE program_id=? ORDER BY version",projectId),approvals=this.jsonRows("SELECT payload_json FROM research_approvals WHERE program_id=? ORDER BY created_at",projectId),stateBody={format:"research-scope-snapshot-v1" as const,program,questions,approvals},state={...stateBody,stateHash:hashPayload(stateBody)},body={bundleVersion:"1" as const,publicSchemaVersion,exportedAt:new Date().toISOString(),source:{workspaceId:project.workspaceId,projectId},project,events:this.events(projectId),projection:this.projection(projectId),state};return ProjectBundleSchema.parse({...body,contentHash:hashPayload(body)});
  }

  importBundle(input:unknown,destinationWorkspaceId:string,actor:CommandActor):{project:ProjectRecord;event:PersistedResearchEvent}{
    const bundle=ProjectBundleSchema.parse(input),{contentHash,...body}=bundle;if(hashPayload(body)!==contentHash)throw new Error("Project bundle content hash mismatch");const{stateHash,...stateBody}=bundle.state;if(hashPayload(stateBody)!==stateHash)throw new Error("Project bundle state hash mismatch");if(this.project(bundle.project.id)||this.db.prepare("SELECT 1 ok FROM research_programs WHERE id=?").get(bundle.project.id))throw new Error("Project bundle ID already exists");this.ensureWorkspace(destinationWorkspaceId);const transaction=this.db.transaction(()=>{this.ensureActorTx(destinationWorkspaceId,actor);const program=ResearchProgramSchema.parse(bundle.state.program);this.db.prepare("INSERT INTO research_programs(id,profile,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(program.id,program.profile,program.status,JSON.stringify(program),program.contentHash,program.createdAt,program.updatedAt);for(const raw of bundle.state.questions){const item=ResearchQuestionSchema.parse(raw);this.db.prepare("INSERT INTO research_questions(id,program_id,version,status,payload_json,content_hash,supersedes_id,created_at) VALUES(?,?,?,?,?,?,?,?)").run(item.id,item.programId,item.version,item.status,JSON.stringify(item),item.contentHash,item.supersedesId,item.createdAt);}for(const raw of bundle.state.approvals){const item=ApprovalSchema.parse(raw);this.db.prepare("INSERT INTO research_approvals(id,program_id,kind,object_id,object_hash,decision,actor,note,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(item.id,item.programId,item.kind,item.objectId,item.objectHash,item.decision,item.actor,item.note,JSON.stringify(item),item.createdAt);}const imported=this.makeProject({...bundle.project,workspaceId:destinationWorkspaceId});this.insertProjectTx(imported,program.status);const importedEvents=bundle.events.map(source=>PersistedResearchEventSchema.parse({...source,workspaceId:destinationWorkspaceId}));for(const event of importedEvents){this.ensureActorTx(destinationWorkspaceId,event.actor);this.insertEventTx(event);}const rebuilt=this.computeProjection(imported,importedEvents,program.status);this.db.prepare("UPDATE project_projections_v15 SET workspace_id=?,last_sequence=?,payload_json=?,projection_hash=?,updated_at=? WHERE project_id=?").run(rebuilt.workspaceId,rebuilt.lastSequence,JSON.stringify(rebuilt),rebuilt.projectionHash,rebuilt.updatedAt,imported.id);const event=this.appendEventTx(imported,{eventId:`event-${randomUUID()}`,type:"project.imported",schemaVersion:"1.0.0",actor,causationId:`import-${randomUUID()}`,correlationId:imported.id,payload:{sourceWorkspaceId:bundle.source.workspaceId,sourceProjectId:bundle.source.projectId,projectionPatch:{researchStatus:program.status}},projectionPatch:{researchStatus:program.status}});return{project:imported,event};});return transaction();
  }

  private ensureActorTx(workspaceId:string,input:CommandActor):PersistedActor{const row=this.db.prepare("SELECT payload_json FROM workspace_actors WHERE workspace_id=? AND actor_id=?").get(workspaceId,input.id) as JsonRow|undefined;if(row){const actor=PersistedActorSchema.parse(JSON.parse(row.payload_json));if(actor.kind!==input.kind)throw new Error("Actor kind conflicts with the persisted workspace actor");return actor;}const now=new Date().toISOString(),actor=PersistedActorSchema.parse({id:input.id,workspaceId,kind:input.kind,displayName:input.displayName??null,createdAt:now,updatedAt:now});this.db.prepare("INSERT INTO workspace_actors(workspace_id,actor_id,kind,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(workspaceId,actor.id,actor.kind,JSON.stringify(actor),actor.createdAt,actor.updatedAt);return actor;}
  private makeProject(input:{id:string;workspaceId:string;rootProjectId:string;parentProjectId:string|null;forkedFromEventId:string|null;branchName:string;status?:"active"|"archived";createdAt?:string;updatedAt?:string;contentHash?:string}):ProjectRecord{const now=input.createdAt??new Date().toISOString(),body={id:input.id,workspaceId:input.workspaceId,rootProjectId:input.rootProjectId,parentProjectId:input.parentProjectId,forkedFromEventId:input.forkedFromEventId,branchName:input.branchName,status:input.status??"active" as const};return ProjectRecordSchema.parse({...body,contentHash:hashPayload(body),createdAt:now,updatedAt:input.updatedAt??now});}
  private insertProjectTx(project:ProjectRecord,researchStatus:string):void{this.db.prepare("INSERT INTO research_projects_v15(id,workspace_id,root_project_id,parent_project_id,forked_from_event_id,branch_name,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(project.id,project.workspaceId,project.rootProjectId,project.parentProjectId,project.forkedFromEventId,project.branchName,project.status,JSON.stringify(project),project.contentHash,project.createdAt,project.updatedAt);const projection=createProjectProjection({projectId:project.id,workspaceId:project.workspaceId,rootProjectId:project.rootProjectId,parentProjectId:project.parentProjectId,branchName:project.branchName,projectStatus:project.status,researchStatus,lastSequence:0,eventCount:0,lastEventType:null,updatedAt:project.updatedAt});this.db.prepare("INSERT INTO project_projections_v15(project_id,workspace_id,last_sequence,payload_json,projection_hash,updated_at) VALUES(?,?,?,?,?,?)").run(project.id,project.workspaceId,0,JSON.stringify(projection),projection.projectionHash,projection.updatedAt);}
  private appendEventTx(project:ProjectRecord,draft:EventDraft):PersistedResearchEvent{const last=(this.db.prepare("SELECT coalesce(max(sequence),0) n FROM research_events_v15 WHERE project_id=?").get(project.id) as{n:number}).n,normalizedPayload=JSON.parse(JSON.stringify(draft.payload)),payloadHash=hashPayload(normalizedPayload),event=PersistedResearchEventSchema.parse({schemaVersion:draft.schemaVersion,eventId:draft.eventId,type:draft.type,workspaceId:project.workspaceId,projectId:project.id,sequence:last+1,actor:draft.actor,causationId:draft.causationId,correlationId:draft.correlationId,occurredAt:draft.occurredAt??new Date().toISOString(),permissions:draft.permissions??[],externalServices:draft.externalServices??[],payloadHash,payload:normalizedPayload});this.insertEventTx(event);const current=this.projectionTx(project.id),{projectionHash:_,...base}=current,updated=createProjectProjection({...base,researchStatus:draft.projectionPatch?.researchStatus??current.researchStatus,lastSequence:event.sequence,eventCount:event.sequence,lastEventType:event.type,updatedAt:event.occurredAt});this.db.prepare("UPDATE project_projections_v15 SET last_sequence=?,payload_json=?,projection_hash=?,updated_at=? WHERE project_id=?").run(updated.lastSequence,JSON.stringify(updated),updated.projectionHash,updated.updatedAt,project.id);return event;}
  private insertEventTx(event:PersistedResearchEvent):void{this.db.prepare("INSERT INTO research_events_v15(event_id,workspace_id,project_id,sequence,event_type,schema_version,actor_id,actor_kind,causation_id,correlation_id,payload_json,payload_hash,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(event.eventId,event.workspaceId,event.projectId,event.sequence,event.type,event.schemaVersion,event.actor.id,event.actor.kind,event.causationId,event.correlationId,JSON.stringify(event),event.payloadHash,event.occurredAt);}
  private completeReceiptTx(commandId:string,result:unknown):void{const row=this.db.prepare("SELECT payload_json FROM command_receipts_v15 WHERE command_id=?").get(commandId) as JsonRow|undefined;if(!row)throw new Error(`Unknown command receipt ${commandId}`);const receipt=CommandReceiptSchema.parse(JSON.parse(row.payload_json)),now=new Date().toISOString(),done=CommandReceiptSchema.parse({...receipt,status:"completed",result,completedAt:now});this.db.prepare("UPDATE command_receipts_v15 SET status='completed',result_json=?,payload_json=?,completed_at=? WHERE command_id=?").run(JSON.stringify(result),JSON.stringify(done),now,commandId);}
  private assertPendingTx(commandId:string):void{const row=this.db.prepare("SELECT status FROM command_receipts_v15 WHERE command_id=?").get(commandId) as{status:string}|undefined;if(row?.status!=="pending")throw new Error(`Command ${commandId} is not pending`);}
  private assertProjectWorkspaceTx(projectId:string,workspaceId:string):void{const project=this.requireProjectTx(projectId);if(project.workspaceId!==workspaceId)throw new Error("Project does not belong to this workspace");if(project.status!=="active")throw new Error("Project is archived");}
  private requireProjectTx(id:string):ProjectRecord{const project=this.project(id);if(!project)throw new Error(`Unknown project ${id}`);return project;}
  private projectionTx(id:string):ProjectProjection{return this.projection(id);}
  private eventAtTx(projectId:string,sequence:number):PersistedResearchEvent{const row=this.db.prepare("SELECT payload_json FROM research_events_v15 WHERE project_id=? AND sequence=?").get(projectId,sequence) as JsonRow|undefined;if(!row)throw new Error("Fork source event is missing");return this.upcastEvent(JSON.parse(row.payload_json));}
  private programTx(id:string){const row=this.db.prepare("SELECT payload_json FROM research_programs WHERE id=?").get(id) as JsonRow|undefined;if(!row)throw new Error(`Unknown research program ${id}`);return ResearchProgramSchema.parse(JSON.parse(row.payload_json));}
  private jsonRows(sql:string,id:string):unknown[]{return(this.db.prepare(sql).all(id) as JsonRow[]).map(row=>JSON.parse(row.payload_json));}
  private upcastEvent(raw:any):PersistedResearchEvent{if(raw.schemaVersion==="0.9.0"){const{actorId,actorKind,...rest}=raw;raw={...rest,schemaVersion:"1.0.0",actor:raw.actor??{id:actorId,kind:actorKind},payloadHash:hashPayload(raw.payload)};}if(raw.schemaVersion!=="1.0.0")throw new Error(`No event upcaster for schema ${String(raw.schemaVersion)}`);return PersistedResearchEventSchema.parse(raw);}
  private computeProjection(project:ProjectRecord,events:PersistedResearchEvent[],fallbackResearchStatus:string):ProjectProjection{let researchStatus=fallbackResearchStatus;for(const event of events){const payload=event.payload as{projectionPatch?:{researchStatus?:string}}|null;if(payload?.projectionPatch?.researchStatus)researchStatus=payload.projectionPatch.researchStatus;}const last=events.at(-1);return createProjectProjection({projectId:project.id,workspaceId:project.workspaceId,rootProjectId:project.rootProjectId,parentProjectId:project.parentProjectId,branchName:project.branchName,projectStatus:project.status,researchStatus,lastSequence:last?.sequence??0,eventCount:events.length,lastEventType:last?.type??null,updatedAt:last?.occurredAt??project.updatedAt});}
  private assertScopeBundleSupportedTx(projectId:string):void{const checks:Array<[string,string[]]>=[["SELECT count(*) n FROM research_assumptions a JOIN research_questions q ON q.id=a.question_id WHERE q.program_id=?",[projectId]],["SELECT count(*) n FROM research_hypothesis_sets WHERE program_id=?",[projectId]],["SELECT count(*) n FROM research_protocols WHERE program_id=?",[projectId]],["SELECT count(*) n FROM search_protocols WHERE program_id=?",[projectId]],["SELECT count(*) n FROM evidence_maps WHERE program_id=?",[projectId]],["SELECT count(*) n FROM dataset_substitutions WHERE program_id=?",[projectId]],["SELECT count(*) n FROM studies WHERE program_id=?",[projectId]],["SELECT count(*) n FROM research_run_derivations WHERE parent_program_id=? OR child_program_id=?",[projectId,projectId]]];if(this.tableExistsTx("conversation_sessions_v15"))checks.push(["SELECT count(*) n FROM conversation_sessions_v15 WHERE project_id=?",[projectId]],["SELECT count(*) n FROM execution_policies_v15 WHERE project_id=?",[projectId]]);if(this.tableExistsTx("research_jobs_v15"))checks.push(["SELECT count(*) n FROM research_jobs_v15 WHERE project_id=?",[projectId]]);if(this.tableExistsTx("plugin_installations_v15"))checks.push(["SELECT count(*) n FROM plugin_installations_v15 WHERE status!='removed' AND (project_id=? OR (scope='workspace' AND workspace_id=(SELECT workspace_id FROM research_projects_v15 WHERE id=?)))",[projectId,projectId]]);for(const[sql,parameters]of checks)if((this.db.prepare(sql).get(...parameters) as{n:number}).n>0)throw new Error("Project bundle scope snapshot cannot export advanced research, interaction, Job or plugin state yet");}
  private tableExistsTx(name:string):boolean{return!!this.db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=?").get(name);}
}
