import Database from "better-sqlite3";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";
import { hashPayload } from "../../domain/research.js";
import { ClaimAssessmentSchema, ModelInvocationSchema, ModelRoleSessionSchema, ReproductionManifestSchema, ResearchDecisionSchema, ReviewFindingSchema, ReviewResponseSchema, StructuredReviewSchema, ValidityThreatSchema, type ClaimAssessment, type ModelInvocation, type ModelRoleSession, type ReproductionManifest, type ResearchDecision, type ReviewFinding, type ReviewResponse, type StructuredReview, type ValidityThreat } from "../../domain/review.js";

interface PayloadRow{payload_json:string}
export class ReviewStore{
  private constructor(private readonly db:Database.Database,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}
  static async open(path:string):Promise<ReviewStore>{mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");const version=db.pragma("user_version",{simple:true}) as number;if(version<6){db.close();throw new Error("G schema version 6 is required before H migration");}if(version>7){db.close();throw new Error(`Review database ${version} is newer than supported version 7`);}let backup:string|null=null,manifest:string|null=null;if(version<7){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-006-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"006");try{applyMigrationTransaction(db,readFileSync(resolve("migrations/006_claim_review_decision.sql"),"utf8"));}catch(error){db.close();throw error;}}if((db.pragma("user_version",{simple:true}) as number)!==7){db.close();throw new Error("H migration did not reach schema version 7");}return new ReviewStore(db,backup,manifest);}
  close():void{this.db.close();}
  addRoleSession(input:Omit<ModelRoleSession,"id"|"createdAt">):ModelRoleSession{const session=ModelRoleSessionSchema.parse({...input,id:`role-session-${randomUUID()}`,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO model_role_sessions(id,program_id,role,provider_model,input_hash,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").run(session.id,session.programId,session.role,session.providerModel,session.inputHash,JSON.stringify(session),session.createdAt);return session;}
  addModelInvocation(input:Omit<ModelInvocation,"id"|"createdAt"|"finishedAt">&{createdAt?:string;finishedAt?:string}):ModelInvocation{const invocation=ModelInvocationSchema.parse({...input,id:`model-invocation-${randomUUID()}`,createdAt:input.createdAt??new Date().toISOString(),finishedAt:input.finishedAt??new Date().toISOString()});if(invocation.roleSessionId&&!this.db.prepare("SELECT 1 ok FROM model_role_sessions WHERE id=? AND program_id=?").get(invocation.roleSessionId,invocation.programId))throw new Error("Model invocation role session does not belong to program");this.db.prepare("INSERT INTO model_invocations(id,program_id,role_session_id,stage,provider_model,status,input_hash,output_hash,payload_json,created_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(invocation.id,invocation.programId,invocation.roleSessionId,invocation.stage,invocation.providerModel,invocation.status,invocation.inputHash,invocation.outputHash,JSON.stringify(invocation),invocation.createdAt,invocation.finishedAt);return invocation;}
  modelInvocations(programId:string):ModelInvocation[]{return(this.db.prepare("SELECT payload_json FROM model_invocations WHERE program_id=? ORDER BY created_at").all(programId) as PayloadRow[]).map(row=>ModelInvocationSchema.parse(JSON.parse(row.payload_json)));}
  addClaimAssessment(input:Omit<ClaimAssessment,"id"|"contentHash"|"createdAt">):ClaimAssessment{const study=this.db.prepare("SELECT status,protocol_id,evidence_map_id FROM studies WHERE id=? AND program_id=?").get(input.studyId,input.programId) as{status:string;protocol_id:string;evidence_map_id:string}|undefined;if(!study||study.status!=="analyzed")throw new Error("Claim assessment requires an analyzed study");if(study.protocol_id!==input.protocolId||study.evidence_map_id!==input.evidenceMapId)throw new Error("Claim assessment lineage does not match study");if(!this.db.prepare("SELECT 1 ok FROM claims WHERE id=?").get(input.claimId))throw new Error("Claim assessment requires a recorded claim");if(!this.db.prepare("SELECT 1 ok FROM analysis_runs WHERE id=? AND study_id=? AND status='completed'").get(input.analysisRunId,input.studyId))throw new Error("Claim assessment requires a completed analysis run");for(const estimate of input.estimateIds)if(!this.db.prepare("SELECT 1 ok FROM statistical_estimates WHERE id=? AND analysis_run_id=?").get(estimate,input.analysisRunId))throw new Error(`Unknown estimate ${estimate}`);for(const evidenceId of [...input.supportingEvidenceIds,...input.opposingEvidenceIds])if(!this.evidenceExists(evidenceId))throw new Error(`Unknown claim evidence ${evidenceId}`);if(input.grade==="replicated")throw new Error("Replicated grade requires external replication, which is not available in v1.2 H acceptance");const body={...input};const assessment=ClaimAssessmentSchema.parse({...body,id:`claim-assessment-${randomUUID()}`,contentHash:hashPayload(body),createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO claim_assessments(id,program_id,study_id,claim_id,grade,payload_json,content_hash,created_at) VALUES(?,?,?,?,?,?,?,?)").run(assessment.id,assessment.programId,assessment.studyId,assessment.claimId,assessment.grade,JSON.stringify(assessment),assessment.contentHash,assessment.createdAt);return assessment;}
  private evidenceExists(id:string):boolean{return Boolean(this.db.prepare("SELECT 1 ok FROM evidence_map_entries WHERE id=? UNION SELECT 1 FROM observations WHERE id=? UNION SELECT 1 FROM statistical_estimates WHERE id=? LIMIT 1").get(id,id,id));}
  addThreat(input:Omit<ValidityThreat,"id"|"createdAt">):ValidityThreat{if(!this.db.prepare("SELECT 1 ok FROM claim_assessments WHERE id=?").get(input.claimAssessmentId))throw new Error("Unknown claim assessment");const threat=ValidityThreatSchema.parse({...input,id:`validity-threat-${randomUUID()}`,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO validity_threats(id,claim_assessment_id,kind,severity,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(threat.id,threat.claimAssessmentId,threat.kind,threat.severity,JSON.stringify(threat),threat.createdAt);return threat;}
  addReview(input:Omit<StructuredReview,"id"|"createdAt">,findings:Array<Omit<ReviewFinding,"id"|"reviewId"|"status"|"createdAt">>):{review:StructuredReview;findings:ReviewFinding[]}{const session=this.db.prepare("SELECT payload_json FROM model_role_sessions WHERE id=?").get(input.roleSessionId) as PayloadRow|undefined;if(!session)throw new Error("Review requires a recorded role session");const sessionValue=ModelRoleSessionSchema.parse(JSON.parse(session.payload_json));if(sessionValue.sessionKind!=="independent"||sessionValue.toolAccess.some(tool=>/(write|execute|experiment|approve)/i.test(tool)))throw new Error("Reviewer role session must be independent and read-only");const review=StructuredReviewSchema.parse({...input,id:`review-${randomUUID()}`,createdAt:new Date().toISOString()});const rows=findings.map(item=>ReviewFindingSchema.parse({...item,id:`review-finding-${randomUUID()}`,reviewId:review.id,status:"open",createdAt:new Date().toISOString()}));const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO structured_reviews(id,program_id,study_id,dimension,role_session_id,verdict,payload_json,input_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(review.id,review.programId,review.studyId,review.dimension,review.roleSessionId,review.verdict,JSON.stringify(review),review.inputHash,review.createdAt);for(const row of rows)this.db.prepare("INSERT INTO review_findings(id,review_id,severity,status,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(row.id,row.reviewId,row.severity,row.status,JSON.stringify(row),row.createdAt);});tx();return{review,findings:rows};}
  respond(input:Omit<ReviewResponse,"id"|"createdAt">):ReviewResponse{const findingRow=this.db.prepare("SELECT payload_json FROM review_findings WHERE id=? AND review_id=?").get(input.findingId,input.reviewId) as PayloadRow|undefined;if(!findingRow)throw new Error("Finding does not belong to review");const finding=ReviewFindingSchema.parse(JSON.parse(findingRow.payload_json));if(finding.status!=="open")throw new Error("Finding is already resolved");for(const id of input.evidenceIds)if(!this.evidenceExists(id)&&!this.db.prepare("SELECT 1 ok FROM claim_assessments WHERE id=?").get(id))throw new Error(`Unknown response evidence ${id}`);const response=ReviewResponseSchema.parse({...input,id:`review-response-${randomUUID()}`,createdAt:new Date().toISOString()});const updated={...finding,status:response.disposition};const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO review_responses(id,review_id,finding_id,payload_json,created_at) VALUES(?,?,?,?,?)").run(response.id,response.reviewId,response.findingId,JSON.stringify(response),response.createdAt);this.db.prepare("UPDATE review_findings SET status=?,payload_json=? WHERE id=?").run(updated.status,JSON.stringify(updated),updated.id);});tx();return response;}
  addReproductionManifest(input:Omit<ReproductionManifest,"id"|"contentHash"|"createdAt">):ReproductionManifest{const body={...input};const manifest=ReproductionManifestSchema.parse({...body,id:`reproduction-${randomUUID()}`,contentHash:hashPayload(body),createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO reproduction_manifests(id,program_id,study_id,payload_json,content_hash,created_at) VALUES(?,?,?,?,?,?)").run(manifest.id,manifest.programId,manifest.studyId,JSON.stringify(manifest),manifest.contentHash,manifest.createdAt);return manifest;}
  decide(input:Omit<ResearchDecision,"id"|"createdAt">):ResearchDecision{const reviews=this.reviews(input.studyId);const dimensions=new Set(reviews.map(review=>review.dimension));if(dimensions.size!==4)throw new Error("Final decision requires all four review dimensions");if(input.reviewIds.some(id=>!reviews.some(review=>review.id===id)))throw new Error("Decision review IDs do not match study reviews");const findings=this.findings(input.studyId);if(findings.some(finding=>finding.severity==="major"&&finding.status==="open"))throw new Error("Major review findings must be resolved before decision");if(input.action==="publish_bounded_result"&&reviews.some(review=>review.verdict==="invalid"))throw new Error("Invalid review blocks publish_bounded_result");for(const id of input.claimAssessmentIds)if(!this.db.prepare("SELECT 1 ok FROM claim_assessments WHERE id=? AND study_id=?").get(id,input.studyId))throw new Error(`Claim assessment ${id} does not belong to study`);const decision=ResearchDecisionSchema.parse({...input,id:`decision-${randomUUID()}`,createdAt:new Date().toISOString()});const terminal=new Set(["publish_bounded_result","stop_low_value","stop_inconclusive","debug_reproduction"]);const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO research_decisions(id,program_id,study_id,action,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(decision.id,decision.programId,decision.studyId,decision.action,JSON.stringify(decision),decision.createdAt);if(terminal.has(decision.action)){this.db.prepare("UPDATE studies SET status='closed',payload_json=json_set(payload_json,'$.status','closed','$.updatedAt',?),updated_at=? WHERE id=?").run(decision.createdAt,decision.createdAt,decision.studyId);this.db.prepare("UPDATE research_programs SET status='closed',payload_json=json_set(payload_json,'$.status','closed','$.updatedAt',?),updated_at=? WHERE id=?").run(decision.createdAt,decision.createdAt,decision.programId);}});tx();return decision;}
  assessments(studyId:string):ClaimAssessment[]{return(this.db.prepare("SELECT payload_json FROM claim_assessments WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(row=>ClaimAssessmentSchema.parse(JSON.parse(row.payload_json)));}
  reviews(studyId:string):StructuredReview[]{return(this.db.prepare("SELECT payload_json FROM structured_reviews WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(row=>StructuredReviewSchema.parse(JSON.parse(row.payload_json)));}
  findings(studyId:string):ReviewFinding[]{return(this.db.prepare("SELECT f.payload_json FROM review_findings f JOIN structured_reviews r ON r.id=f.review_id WHERE r.study_id=? ORDER BY f.created_at").all(studyId) as PayloadRow[]).map(row=>ReviewFindingSchema.parse(JSON.parse(row.payload_json)));}
  responses(studyId:string):ReviewResponse[]{return(this.db.prepare("SELECT rr.payload_json FROM review_responses rr JOIN structured_reviews r ON r.id=rr.review_id WHERE r.study_id=? ORDER BY rr.created_at").all(studyId) as PayloadRow[]).map(row=>ReviewResponseSchema.parse(JSON.parse(row.payload_json)));}
  threats(assessmentId:string):ValidityThreat[]{return(this.db.prepare("SELECT payload_json FROM validity_threats WHERE claim_assessment_id=? ORDER BY created_at").all(assessmentId) as PayloadRow[]).map(row=>ValidityThreatSchema.parse(JSON.parse(row.payload_json)));}
  reproductionManifests(studyId:string):ReproductionManifest[]{return(this.db.prepare("SELECT payload_json FROM reproduction_manifests WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(row=>ReproductionManifestSchema.parse(JSON.parse(row.payload_json)));}
}
