import Database from "better-sqlite3";
import { mkdirSync,readFileSync } from "node:fs";
import { dirname,resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { auditFactAssertions,assertFactAudit,FactLedgerSchema } from "../../domain/facts.js";
import { createScientificDecision,ScientificDecisionResultSchema,ScientificDecisionSchema,type ExperimentOption,type ScientificDecision,type ScientificDecisionResult } from "../../domain/scientific-decision.js";
import { applyMigrationTransaction } from "./research-store.js";
interface Row{payload_json:string}
export class ScientificDecisionStore{
  private constructor(private readonly db:Database.Database){}
  static async open(path:string):Promise<ScientificDecisionStore>{mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("foreign_keys = ON");const version=db.pragma("user_version",{simple:true}) as number;if(version<9){db.close();throw new Error("Scientific decisions require schema version 9");}if(version>12){db.close();throw new Error(`Scientific decision database ${version} is newer than supported version 12`);}if(version<10)applyMigrationTransaction(db,readFileSync(resolve("migrations/009_scientific_decisions.sql"),"utf8"));return new ScientificDecisionStore(db);}
  close():void{this.db.close();}
  decisions(studyId:string):ScientificDecision[]{return(this.db.prepare("SELECT payload_json FROM scientific_decisions WHERE study_id=? ORDER BY sequence").all(studyId) as Row[]).map(row=>ScientificDecisionSchema.parse(JSON.parse(row.payload_json)));}
  results(studyId:string):ScientificDecisionResult[]{return(this.db.prepare("SELECT payload_json FROM scientific_decision_results WHERE study_id=? ORDER BY created_at").all(studyId) as Row[]).map(row=>ScientificDecisionResultSchema.parse(JSON.parse(row.payload_json)));}
  register(input:{programId:string;studyId:string;action:ScientificDecision["action"];selectedOptionId?:string|null;hypothesisIds:string[];rivalHypothesisIds:string[];factLedgerId:string;factAssertions:ScientificDecision["factAssertions"];rationale:string;stopCondition:string;options:ExperimentOption[];remainingGpuHours:number;remainingWallHours:number}):ScientificDecision{const study=this.db.prepare("SELECT program_id,status,payload_json FROM studies WHERE id=?").get(input.studyId) as{program_id:string;status:string;payload_json:string}|undefined;if(!study||study.program_id!==input.programId)throw new Error("Scientific decision study/program mismatch");if(!["exploring","candidate_frozen","confirmation_ready","confirmation_consumed","analyzed"].includes(study.status))throw new Error(`Scientific decision is not allowed in study state ${study.status}`);const prior=this.decisions(input.studyId),unresolved=prior.find(item=>!this.db.prepare("SELECT 1 ok FROM scientific_decision_results WHERE decision_id=?").get(item.id));if(unresolved)throw new Error(`Previous scientific decision ${unresolved.id} has no recorded result`);const ledgerRow=this.db.prepare("SELECT payload_json FROM fact_ledgers WHERE id=? AND study_id=?").get(input.factLedgerId,input.studyId) as Row|undefined;if(!ledgerRow)throw new Error("Scientific decision requires a study FactLedger");const ledger=FactLedgerSchema.parse(JSON.parse(ledgerRow.payload_json)),setId=(JSON.parse(study.payload_json) as{hypothesisSetId:string}).hypothesisSetId,setRow=this.db.prepare("SELECT payload_json FROM research_hypothesis_sets WHERE id=? AND status='frozen'").get(setId) as Row|undefined;if(!setRow)throw new Error("Scientific decision requires the frozen hypothesis set");const known=new Set((JSON.parse(setRow.payload_json) as{hypotheses:Array<{id:string}>}).hypotheses.map(item=>item.id));for(const id of [...input.hypothesisIds,...input.rivalHypothesisIds])if(!known.has(id))throw new Error(`Unknown decision hypothesis ${id}`);const decision=createScientificDecision({...input,sequence:prior.length+1,factLedger:ledger,confirmationVisible:["confirmation_consumed","analyzed"].includes(study.status)});this.db.prepare("INSERT INTO scientific_decisions(id,program_id,study_id,sequence,action,payload_json,input_hash,created_at) VALUES(?,?,?,?,?,?,?,?)").run(decision.id,decision.programId,decision.studyId,decision.sequence,decision.action,JSON.stringify(decision),decision.inputHash,decision.createdAt);return decision;}
  recordResult(input:{decisionId:string;factLedgerId:string;factAssertions:ScientificDecisionResult["factAssertions"];conclusion:ScientificDecisionResult["conclusion"];details:string}):ScientificDecisionResult{const row=this.db.prepare("SELECT payload_json FROM scientific_decisions WHERE id=?").get(input.decisionId) as Row|undefined;if(!row)throw new Error("Unknown scientific decision");const decision=ScientificDecisionSchema.parse(JSON.parse(row.payload_json));if(this.db.prepare("SELECT 1 ok FROM scientific_decision_results WHERE decision_id=?").get(decision.id))throw new Error("Scientific decision result is already recorded");const ledgerRow=this.db.prepare("SELECT payload_json FROM fact_ledgers WHERE id=? AND study_id=?").get(input.factLedgerId,decision.studyId) as Row|undefined;if(!ledgerRow)throw new Error("Decision result requires a study FactLedger");const audit=auditFactAssertions(FactLedgerSchema.parse(JSON.parse(ledgerRow.payload_json)),`scientific-decision-result-${decision.sequence}`,input.factAssertions,{requireAll:true});assertFactAudit(audit);const result=ScientificDecisionResultSchema.parse({...input,id:`scientific-decision-result-${randomUUID()}`,studyId:decision.studyId,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO scientific_decision_results(id,decision_id,study_id,payload_json,created_at) VALUES(?,?,?,?,?)").run(result.id,result.decisionId,result.studyId,JSON.stringify(result),result.createdAt);return result;}
}
