import Database from "better-sqlite3";
import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { z } from "zod";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";

export const ServiceAuditRecordSchema=z.object({id:z.string(),requestId:z.string(),method:z.string(),endpoint:z.string(),workspaceId:z.string().nullable(),projectId:z.string().nullable(),actorId:z.string().nullable(),status:z.enum(["accepted","rejected","error"]),requiredPermissions:z.array(z.string()),externalServices:z.array(z.string()),payloadHash:z.string().regex(/^[a-f0-9]{64}$/),errorCode:z.string().nullable(),remoteAddress:z.string().nullable(),startedAt:z.string(),finishedAt:z.string()}).strict();
export type ServiceAuditRecord=z.infer<typeof ServiceAuditRecordSchema>;

export class ServiceAuditStore{
  private constructor(private readonly db:Database.Database,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}
  static async open(path:string):Promise<ServiceAuditStore>{mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");const version=db.pragma("user_version",{simple:true}) as number;if(version<14){db.close();throw new Error("Service audit requires schema version 14 before migration");}if(version>15){db.close();throw new Error(`Service audit database ${version} is newer than supported version 15`);}let backup:string|null=null,manifest:string|null=null;if(version===14){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-014-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"014");try{applyMigrationTransaction(db,readFileSync(resolve("migrations/014_core_service_audit.sql"),"utf8"));}catch(error){db.close();throw error;}}return new ServiceAuditStore(db,backup,manifest);}
  close():void{this.db.close();}
  record(input:Omit<ServiceAuditRecord,"id">):ServiceAuditRecord{const item=ServiceAuditRecordSchema.parse({...input,id:`service-audit-${randomUUID()}`});this.db.prepare("INSERT INTO service_audit_v15(id,request_id,method,endpoint,workspace_id,project_id,actor_id,status,required_permissions_json,external_services_json,payload_hash,error_code,remote_address,started_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(item.id,item.requestId,item.method,item.endpoint,item.workspaceId,item.projectId,item.actorId,item.status,JSON.stringify(item.requiredPermissions),JSON.stringify(item.externalServices),item.payloadHash,item.errorCode,item.remoteAddress,item.startedAt,item.finishedAt);return item;}
  secret(input:{name:string;provider:string;found:boolean;purpose:string}):void{this.db.prepare("INSERT INTO secret_access_audit_v15(id,secret_name_hash,provider,found,purpose,created_at) VALUES(?,?,?,?,?,?)").run(`secret-audit-${randomUUID()}`,createHash("sha256").update(input.name).digest("hex"),input.provider,input.found?1:0,input.purpose,new Date().toISOString());}
  list(input:{workspaceId?:string|null;projectId?:string|null;limit?:number}={}):ServiceAuditRecord[]{const limit=Math.min(1000,Math.max(1,input.limit??200)),rows=input.projectId?this.db.prepare("SELECT * FROM service_audit_v15 WHERE project_id=? ORDER BY started_at DESC LIMIT ?").all(input.projectId,limit):input.workspaceId?this.db.prepare("SELECT * FROM service_audit_v15 WHERE workspace_id=? ORDER BY started_at DESC LIMIT ?").all(input.workspaceId,limit):this.db.prepare("SELECT * FROM service_audit_v15 ORDER BY started_at DESC LIMIT ?").all(limit);return(rows as Array<Record<string,any>>).map(row=>ServiceAuditRecordSchema.parse({id:row.id,requestId:row.request_id,method:row.method,endpoint:row.endpoint,workspaceId:row.workspace_id,projectId:row.project_id,actorId:row.actor_id,status:row.status,requiredPermissions:JSON.parse(row.required_permissions_json),externalServices:JSON.parse(row.external_services_json),payloadHash:row.payload_hash,errorCode:row.error_code,remoteAddress:row.remote_address,startedAt:row.started_at,finishedAt:row.finished_at}));}
}
