import Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { dirname,resolve } from "node:path";
import { RemoteWorkerInstallationSchema,SshHostProfileSchema,SshPreflightResultSchema,ProjectSshRequirementSchema,type RemoteWorkerInstallation,type SshHostProfile } from "../../public/contracts.js";
import { hashPayload } from "../../domain/research.js";
import { applyMigrationTransaction,snapshotArtifactManifest } from "./research-store.js";
import { readMigration } from "./migration-path.js";

interface Row{payload_json:string}
export class SshWorkerStore{
  private constructor(private readonly db:Database.Database,readonly migrationBackupPath:string|null,readonly artifactManifestSnapshotPath:string|null){}
  static async open(path:string):Promise<SshWorkerStore>{mkdirSync(dirname(path),{recursive:true});const db=new Database(path);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");const version=db.pragma("user_version",{simple:true}) as number;if(version<16){db.close();throw new Error("SSH Worker store requires schema version 16 before migration");}if(version>17){db.close();throw new Error(`SSH Worker database ${version} is newer than supported version 17`);}let backup:string|null=null,manifest:string|null=null;if(version===16){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-016-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"016");try{applyMigrationTransaction(db,readMigration("016_ssh_remote_workers.sql"));}catch(error){db.close();throw error;}}return new SshWorkerStore(db,backup,manifest);}
  close(){this.db.close();}
  addProfile(workspaceId:string,input:{name:string;hostAlias:string;sshConfigFile:string|null;remoteRoot:string;expectedArch:string|null}){this.requireWorkspace(workspaceId);const now=new Date().toISOString(),profile=SshHostProfileSchema.parse({id:`ssh-profile-${randomUUID()}`,workspaceId,...input,expectedOs:"linux",status:"pending",pendingFingerprint:null,pendingHostKey:null,approvedFingerprint:null,workerProtocolVersion:"1",createdAt:now,updatedAt:now});this.db.prepare("INSERT INTO ssh_host_profiles_v16(id,workspace_id,name,host_alias,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(profile.id,workspaceId,profile.name,profile.hostAlias,profile.status,JSON.stringify(profile),now,now);return profile;}
  updateProfile(workspaceId:string,id:string,patch:Record<string,unknown>){const current=this.profile(workspaceId,id),connectionChanged=["hostAlias","sshConfigFile"].some(key=>key in patch&&patch[key]!==current[key as keyof SshHostProfile]),now=new Date().toISOString(),{enabled,...profilePatch}=patch,next=SshHostProfileSchema.parse({...current,...profilePatch,status:enabled===false?"disabled":enabled===true?(connectionChanged?"pending":current.status):connectionChanged?"pending":current.status,pendingFingerprint:connectionChanged?null:current.pendingFingerprint,pendingHostKey:connectionChanged?null:current.pendingHostKey,approvedFingerprint:connectionChanged?null:current.approvedFingerprint,updatedAt:now});this.db.prepare("UPDATE ssh_host_profiles_v16 SET name=?,host_alias=?,status=?,payload_json=?,updated_at=? WHERE id=?").run(next.name,next.hostAlias,next.status,JSON.stringify(next),now,id);if(connectionChanged)this.db.prepare("UPDATE remote_worker_installations_v16 SET status='quarantined',payload_json=json_set(payload_json,'$.status','quarantined'),updated_at=? WHERE profile_id=?").run(now,id);return next;}
  removeProfile(workspaceId:string,id:string){const profile=this.profile(workspaceId,id),used=this.db.prepare("SELECT 1 ok FROM project_ssh_requirements_v16 WHERE profile_id=? LIMIT 1").get(id);if(used)throw new Error("SSH profile is locked by a Project");this.db.prepare("DELETE FROM ssh_host_preflights_v16 WHERE profile_id=?").run(id);this.db.prepare("DELETE FROM ssh_host_approvals_v16 WHERE profile_id=?").run(id);this.db.prepare("DELETE FROM remote_worker_installations_v16 WHERE profile_id=?").run(id);this.db.prepare("DELETE FROM ssh_host_profiles_v16 WHERE id=?").run(id);return{id:profile.id,removed:true};}
  profile(workspaceId:string,id:string):SshHostProfile{const row=this.db.prepare("SELECT payload_json FROM ssh_host_profiles_v16 WHERE id=? AND workspace_id=?").get(id,workspaceId) as Row|undefined;if(!row)throw new Error(`Unknown SSH profile ${id}`);return SshHostProfileSchema.parse(JSON.parse(row.payload_json));}
  profiles(workspaceId:string){return(this.db.prepare("SELECT payload_json FROM ssh_host_profiles_v16 WHERE workspace_id=? ORDER BY name").all(workspaceId) as Row[]).map(row=>SshHostProfileSchema.parse(JSON.parse(row.payload_json)));}
  recordPreflight(workspaceId:string,id:string,result:unknown,pending:{fingerprint:string;hostKey:string}){const profile=this.profile(workspaceId,id),parsed=SshPreflightResultSchema.parse(result),now=new Date().toISOString(),next=SshHostProfileSchema.parse({...profile,status:profile.approvedFingerprint&&profile.approvedFingerprint!==pending.fingerprint?"quarantined":profile.status,pendingFingerprint:pending.fingerprint,pendingHostKey:pending.hostKey,updatedAt:now});this.db.transaction(()=>{this.db.prepare("UPDATE ssh_host_profiles_v16 SET status=?,payload_json=?,updated_at=? WHERE id=?").run(next.status,JSON.stringify(next),now,id);this.db.prepare("INSERT INTO ssh_host_preflights_v16(id,workspace_id,profile_id,payload_json,created_at) VALUES(?,?,?,?,?)").run(`ssh-preflight-${randomUUID()}`,workspaceId,id,JSON.stringify(parsed),now);})();return{profile:next,preflight:parsed};}
  lastPreflight(workspaceId:string,id:string){this.profile(workspaceId,id);const row=this.db.prepare("SELECT payload_json FROM ssh_host_preflights_v16 WHERE profile_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1").get(id) as Row|undefined;return row?SshPreflightResultSchema.parse(JSON.parse(row.payload_json)):null;}
  approve(workspaceId:string,id:string,fingerprint:string,actorId:string){const profile=this.profile(workspaceId,id);if(!profile.pendingFingerprint||!profile.pendingHostKey)throw new Error("SSH profile requires a successful fingerprint probe");if(profile.pendingFingerprint!==fingerprint)throw new Error("SSH host fingerprint mismatch");const now=new Date().toISOString(),next=SshHostProfileSchema.parse({...profile,status:"trusted",approvedFingerprint:fingerprint,updatedAt:now});this.db.transaction(()=>{this.db.prepare("UPDATE ssh_host_profiles_v16 SET status=?,payload_json=?,updated_at=? WHERE id=?").run(next.status,JSON.stringify(next),now,id);this.db.prepare("INSERT INTO ssh_host_approvals_v16(id,workspace_id,profile_id,fingerprint,actor_id,decision,created_at) VALUES(?,?,?,?,?,'approved',?)").run(`ssh-approval-${randomUUID()}`,workspaceId,id,fingerprint,actorId,now);})();return next;}
  quarantine(workspaceId:string,id:string,actorId:string){const profile=this.profile(workspaceId,id),now=new Date().toISOString(),next=SshHostProfileSchema.parse({...profile,status:"quarantined",updatedAt:now});this.db.transaction(()=>{this.db.prepare("UPDATE ssh_host_profiles_v16 SET status=?,payload_json=?,updated_at=? WHERE id=?").run(next.status,JSON.stringify(next),now,id);this.db.prepare("UPDATE remote_worker_installations_v16 SET status='quarantined',payload_json=json_set(payload_json,'$.status','quarantined'),updated_at=? WHERE profile_id=?").run(now,id);if(profile.pendingFingerprint)this.db.prepare("INSERT INTO ssh_host_approvals_v16(id,workspace_id,profile_id,fingerprint,actor_id,decision,created_at) VALUES(?,?,?,?,?,'quarantined',?)").run(`ssh-approval-${randomUUID()}`,workspaceId,id,profile.pendingFingerprint,actorId,now);})();return next;}
  addInstallation(workspaceId:string,profileId:string,input:{contentHash:string;remotePath:string;platform:unknown}){this.profile(workspaceId,profileId);const now=new Date().toISOString(),installation=RemoteWorkerInstallationSchema.parse({id:`remote-worker-${randomUUID()}`,workspaceId,profileId,protocolVersion:"1",...input,status:"installed",createdAt:now,updatedAt:now});this.db.prepare("INSERT OR REPLACE INTO remote_worker_installations_v16(id,workspace_id,profile_id,protocol_version,content_hash,remote_path,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(installation.id,workspaceId,profileId,"1",installation.contentHash,installation.remotePath,installation.status,JSON.stringify(installation),now,now);return installation;}
  setInstallation(workspaceId:string,id:string,status:"enabled"|"disabled"|"quarantined"){const current=this.installation(workspaceId,id),now=new Date().toISOString(),next=RemoteWorkerInstallationSchema.parse({...current,status,updatedAt:now});this.db.prepare("UPDATE remote_worker_installations_v16 SET status=?,payload_json=?,updated_at=? WHERE id=?").run(status,JSON.stringify(next),now,id);return next;}
  installation(workspaceId:string,id:string):RemoteWorkerInstallation{const row=this.db.prepare("SELECT payload_json FROM remote_worker_installations_v16 WHERE id=? AND workspace_id=?").get(id,workspaceId) as Row|undefined;if(!row)throw new Error(`Unknown remote Worker installation ${id}`);return RemoteWorkerInstallationSchema.parse(JSON.parse(row.payload_json));}
  installations(workspaceId:string,profileId?:string){const rows=(profileId?this.db.prepare("SELECT payload_json FROM remote_worker_installations_v16 WHERE workspace_id=? AND profile_id=? ORDER BY created_at").all(workspaceId,profileId):this.db.prepare("SELECT payload_json FROM remote_worker_installations_v16 WHERE workspace_id=? ORDER BY created_at").all(workspaceId))as Row[];return rows.map(row=>RemoteWorkerInstallationSchema.parse(JSON.parse(row.payload_json)));}
  attach(workspaceId:string,projectId:string,profileId:string,installationId:string){const profile=this.profile(workspaceId,profileId),installation=this.installation(workspaceId,installationId);if(installation.profileId!==profile.id||profile.status!=="trusted"||installation.status!=="enabled")throw new Error("Project SSH attachment requires a trusted profile and enabled matching Worker");const project=this.db.prepare("SELECT 1 ok FROM research_projects_v15 WHERE id=? AND workspace_id=?").get(projectId,workspaceId);if(!project)throw new Error("Project does not belong to SSH profile workspace");const now=new Date().toISOString(),body={id:`project-ssh-${randomUUID()}`,workspaceId,projectId,profileId,installationId,profileHash:hashPayload(profile),workerHash:installation.contentHash,status:"available",createdAt:now,updatedAt:now},value=ProjectSshRequirementSchema.parse(body);this.db.prepare("INSERT OR REPLACE INTO project_ssh_requirements_v16(id,workspace_id,project_id,profile_id,installation_id,profile_hash,worker_hash,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(value.id,workspaceId,projectId,profileId,installationId,value.profileHash,value.workerHash,value.status,JSON.stringify(value),now,now);return value;}
  requirements(workspaceId:string,projectId:string){return(this.db.prepare("SELECT payload_json FROM project_ssh_requirements_v16 WHERE workspace_id=? AND project_id=? ORDER BY created_at").all(workspaceId,projectId)as Row[]).map(row=>ProjectSshRequirementSchema.parse(JSON.parse(row.payload_json)));}
  private requireWorkspace(id:string){if(!this.db.prepare("SELECT 1 ok FROM workspaces WHERE id=?").get(id))throw new Error(`Unknown workspace ${id}`);}
}
