import Database from "better-sqlite3";
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import {
  AnalysisPlanSchema, AnalysisRunSchema, BaselineReproductionSchema, CandidateFreezeSchema, ConfirmationTokenSchema,
  DataRoleManifestSchema, DeviationPolicySchema, DiagnosticResultSchema, MultiplicityRecordSchema, ObservationSchema,
  ExperimentalUnitSchema,OutcomeDefinitionSchema,SensitivityAnalysisSchema,StatisticalEstimateSchema,StudyDesignSchema,UnitObservationSchema,
  type AnalysisPlan, type AnalysisRun, type BaselineReproduction, type CandidateFreeze, type ConfirmationToken,
  type DataRoleManifest, type DeviationPolicy, type DiagnosticResult, type MultiplicityRecord, type Observation,
  ResourceUsageSchema, SandboxRunSchema, type ExperimentalUnit, type ObservationRecord, type UnitObservation, type OutcomeDefinition, type ResourceUsage, type SandboxRun, type SensitivityAnalysis, type StatisticalEstimate, type StudyDesign, validateDataRoles,
} from "../../domain/study.js";
import { hashPayload } from "../../domain/research.js";
import { VisibilityEventSchema, type VisibilityEvent } from "../../domain/research.js";
import { applyMigrationTransaction, snapshotArtifactManifest } from "./research-store.js";

interface PayloadRow { payload_json: string }
type StudyDraft = Omit<StudyDesign,"id"|"status"|"contentHash"|"createdAt"|"updatedAt"|"units"|"seeds"|"reliabilityPolicy"|"confirmationExecutionPolicy">&{units?:ExperimentalUnit[];seeds?:number[];reliabilityPolicy?:StudyDesign["reliabilityPolicy"];confirmationExecutionPolicy?:StudyDesign["confirmationExecutionPolicy"]};
type AnalysisPlanDraft = Omit<AnalysisPlan, "id" | "studyId" | "status" | "contentHash" | "createdAt">;
type DeviationPolicyDraft = Omit<DeviationPolicy, "id" | "studyId" | "contentHash" | "createdAt">;

export class StudyStore {
  private constructor(private readonly db: Database.Database, readonly migrationBackupPath: string | null, readonly artifactManifestSnapshotPath: string | null) {}

  static async open(path: string): Promise<StudyStore> {
    mkdirSync(dirname(path), { recursive: true }); const db = new Database(path); db.pragma("journal_mode = WAL"); db.pragma("foreign_keys = ON");
    const version = db.pragma("user_version", { simple: true }) as number;
    if (version < 5) { db.close(); throw new Error("F schema version 5 is required before G migration"); }
    if(version>10){db.close();throw new Error(`Study database ${version} is newer than supported version 10`);}
    let backup:string|null=null,manifest:string|null=null;
    if(version<9){const backupDir=resolve(dirname(path),"backups");mkdirSync(backupDir,{recursive:true});backup=resolve(backupDir,`research-before-008-${new Date().toISOString().replaceAll(":","-")}.db`);await db.backup(backup);manifest=snapshotArtifactManifest(path,backupDir,"008");}
    if (version < 6) {
      const backupDir = resolve(dirname(path), "backups"); mkdirSync(backupDir, { recursive: true });
      try { applyMigrationTransaction(db, readFileSync(resolve("migrations/005_study_analysis.sql"), "utf8")); } catch (error) { db.close(); throw error; }
    }
    let current=db.pragma("user_version", { simple: true }) as number;
    if(current<7){try{applyMigrationTransaction(db,readFileSync(resolve("migrations/006_claim_review_decision.sql"),"utf8"));}catch(error){db.close();throw error;}current=7;}
    if(current<8){try{applyMigrationTransaction(db,readFileSync(resolve("migrations/007_reliability_foundations.sql"),"utf8"));}catch(error){db.close();throw error;}current=8;}
    if(current<9){try{applyMigrationTransaction(db,readFileSync(resolve("migrations/008_enforced_reliability_gates.sql"),"utf8"));}catch(error){db.close();throw error;}current=9;}
    if(current<9||current>10){db.close();throw new Error(`Study schema compatibility failed at version ${current}`);}
    return new StudyStore(db, backup, manifest);
  }

  close(): void { this.db.close(); }

  createStudy(input: StudyDraft): StudyDesign {
    const protocol = this.db.prepare("SELECT payload_json FROM research_protocols WHERE id=? AND program_id=? AND status='frozen'").get(input.protocolId, input.programId) as PayloadRow | undefined;
    const hypotheses = this.db.prepare("SELECT payload_json FROM research_hypothesis_sets WHERE id=? AND program_id=? AND status='frozen'").get(input.hypothesisSetId, input.programId) as PayloadRow | undefined;
    const evidence = this.db.prepare("SELECT payload_json FROM evidence_maps WHERE id=? AND program_id=? AND status='frozen'").get(input.evidenceMapId, input.programId) as PayloadRow | undefined;
    if (!protocol || !hypotheses || !evidence) throw new Error("Study requires frozen protocol, hypothesis set and evidence map from the same program");
    const protocolPayload = JSON.parse(protocol.payload_json) as { hypothesisSetId?: string; assumptionRegisterId?: string };
    const hypothesisPayload = JSON.parse(hypotheses.payload_json) as { evidenceMapId?: string };
    if (protocolPayload.hypothesisSetId !== input.hypothesisSetId || hypothesisPayload.evidenceMapId !== input.evidenceMapId) throw new Error("Study references do not match the frozen research lineage");
    const now=new Date().toISOString(),seeds=input.seeds??[],units=input.units??seeds.map(seed=>({id:`seed:${seed}`,kind:"training_seed",clusterId:null,attributes:{},legacySeed:seed})),body={...input,seeds,units,reliabilityPolicy:input.reliabilityPolicy??"fact_bound_v1",confirmationExecutionPolicy:input.confirmationExecutionPolicy??"bubblewrap_required"};
    const study = StudyDesignSchema.parse({ ...body, id: `study-${randomUUID()}`, status: "draft", contentHash: hashPayload(body), createdAt: now, updatedAt: now });
    const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO studies(id,program_id,protocol_id,hypothesis_set_id,evidence_map_id,status,payload_json,content_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)")
      .run(study.id,study.programId,study.protocolId,study.hypothesisSetId,study.evidenceMapId,study.status,JSON.stringify(study),study.contentHash,study.createdAt,study.updatedAt);for(const unit of study.units)this.db.prepare("INSERT INTO experimental_units(study_id,unit_id,kind,payload_json,created_at) VALUES(?,?,?,?,?)").run(study.id,unit.id,unit.kind,JSON.stringify(unit),study.createdAt);});tx();
    return study;
  }

  getStudy(id: string): StudyDesign { const row=this.db.prepare("SELECT payload_json FROM studies WHERE id=?").get(id) as PayloadRow|undefined; if(!row) throw new Error(`Unknown study ${id}`); return StudyDesignSchema.parse(JSON.parse(row.payload_json)); }
  units(studyId:string):ExperimentalUnit[]{this.getStudy(studyId);return(this.db.prepare("SELECT payload_json FROM experimental_units WHERE study_id=? ORDER BY unit_id").all(studyId) as PayloadRow[]).map(row=>ExperimentalUnitSchema.parse(JSON.parse(row.payload_json)));}
  private updateStudy(study: StudyDesign, status: StudyDesign["status"]): StudyDesign { const updated=StudyDesignSchema.parse({...study,status,updatedAt:new Date().toISOString()}); this.db.prepare("UPDATE studies SET status=?,payload_json=?,updated_at=? WHERE id=?").run(status,JSON.stringify(updated),updated.updatedAt,updated.id); return updated; }

  addOutcome(studyId: string, input: Omit<OutcomeDefinition,"id"|"studyId"|"createdAt">): OutcomeDefinition {
    const study=this.getStudy(studyId); if(study.status!=="draft") throw new Error("Outcomes must be declared before study freeze");
    if(input.role==="primary" && this.outcomes(studyId).some((item)=>item.role==="primary")) throw new Error("Study can have only one primary outcome");
    const outcome=OutcomeDefinitionSchema.parse({...input,id:`outcome-${randomUUID()}`,studyId,createdAt:new Date().toISOString()});
    this.db.prepare("INSERT INTO outcome_definitions(id,study_id,role,payload_json,created_at) VALUES(?,?,?,?,?)").run(outcome.id,studyId,outcome.role,JSON.stringify(outcome),outcome.createdAt); return outcome;
  }
  outcomes(studyId:string):OutcomeDefinition[]{return (this.db.prepare("SELECT payload_json FROM outcome_definitions WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(r=>OutcomeDefinitionSchema.parse(JSON.parse(r.payload_json)));}

  addDataRole(studyId:string,input:Omit<DataRoleManifest,"id"|"studyId"|"createdAt">):DataRoleManifest{const study=this.getStudy(studyId);if(study.status!=="draft")throw new Error("Data roles must be declared before study freeze");const role=DataRoleManifestSchema.parse({...input,id:`data-role-${randomUUID()}`,studyId,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO study_data_roles(id,study_id,role,manifest_hash,sealed,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").run(role.id,studyId,role.role,role.manifestHash,role.sealed?1:0,JSON.stringify(role),role.createdAt);return role;}
  private allDataRoles(studyId:string):DataRoleManifest[]{return (this.db.prepare("SELECT payload_json FROM study_data_roles WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(r=>DataRoleManifestSchema.parse(JSON.parse(r.payload_json)));}
  dataRoles(studyId:string):DataRoleManifest[]{return this.allDataRoles(studyId).filter(role=>!role.sealed);}
  dataManifestHash(studyId:string):string{return hashPayload(this.allDataRoles(studyId));}

  addAnalysisPlan(studyId:string,input:AnalysisPlanDraft):AnalysisPlan{const study=this.getStudy(studyId);if(study.status!=="draft")throw new Error("Analysis plan must be declared before study freeze");if(!this.outcomes(studyId).some(item=>item.id===input.primaryOutcomeId&&item.role==="primary"))throw new Error("Analysis plan primary outcome must be the declared primary outcome");const body={...input};const plan=AnalysisPlanSchema.parse({...body,id:`analysis-plan-${randomUUID()}`,studyId,status:"draft",contentHash:hashPayload(body),createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO analysis_plans(id,study_id,status,payload_json,content_hash,created_at) VALUES(?,?,?,?,?,?)").run(plan.id,studyId,plan.status,JSON.stringify(plan),plan.contentHash,plan.createdAt);return plan;}
  addDeviationPolicy(studyId:string,input:DeviationPolicyDraft):DeviationPolicy{const study=this.getStudy(studyId);if(study.status!=="draft")throw new Error("Deviation policy must be declared before study freeze");const body={...input};const policy=DeviationPolicySchema.parse({...body,id:`deviation-policy-${randomUUID()}`,studyId,contentHash:hashPayload(body),createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO deviation_policies(id,study_id,payload_json,content_hash,created_at) VALUES(?,?,?,?,?)").run(policy.id,studyId,JSON.stringify(policy),policy.contentHash,policy.createdAt);return policy;}
  getAnalysisPlan(studyId:string):AnalysisPlan{const row=this.db.prepare("SELECT payload_json FROM analysis_plans WHERE study_id=? ORDER BY created_at DESC LIMIT 1").get(studyId) as PayloadRow|undefined;if(!row)throw new Error("Study has no analysis plan");return AnalysisPlanSchema.parse(JSON.parse(row.payload_json));}

  freezeStudy(studyId:string):StudyDesign{const study=this.getStudy(studyId);if(study.status!=="draft")throw new Error("Only draft study can freeze");const outcomes=this.outcomes(studyId);if(outcomes.filter(item=>item.role==="primary").length!==1)throw new Error("Study requires exactly one primary outcome");const roles=this.allDataRoles(studyId);validateDataRoles(roles);const plan=this.getAnalysisPlan(studyId);if(!this.db.prepare("SELECT 1 ok FROM deviation_policies WHERE study_id=?").get(studyId))throw new Error("Study requires a deviation policy");const frozenPlan={...plan,status:"frozen" as const};const tx=this.db.transaction(()=>{this.db.prepare("UPDATE analysis_plans SET status=?,payload_json=? WHERE id=?").run(frozenPlan.status,JSON.stringify(frozenPlan),frozenPlan.id);this.updateStudy(study,"frozen");});tx();return this.getStudy(studyId);}

  recordBaseline(studyId:string,input:Omit<BaselineReproduction,"id"|"studyId"|"status"|"failureClass"|"createdAt">&{failureClass?:BaselineReproduction["failureClass"]}):BaselineReproduction{const study=this.getStudy(studyId);if(study.status!=="frozen")throw new Error("Baseline reproduction requires a frozen study");const passed=input.observed!==null&&input.observed>=input.expectedMin&&input.observed<=input.expectedMax;const result=BaselineReproductionSchema.parse({...input,id:`baseline-${randomUUID()}`,studyId,status:passed?"passed":"failed",failureClass:passed?"none":input.failureClass??"published_result_not_reproduced",createdAt:new Date().toISOString()});const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO baseline_reproductions(id,study_id,status,payload_json,created_at) VALUES(?,?,?,?,?)").run(result.id,studyId,result.status,JSON.stringify(result),result.createdAt);this.updateStudy(study,passed?"baseline_passed":"baseline_failed");});tx();return result;}

  beginExploration(studyId:string):StudyDesign{const study=this.getStudy(studyId);if(study.status!=="baseline_passed")throw new Error("Exploration requires a reproduced baseline");if(this.db.prepare("SELECT 1 ok FROM confirmation_tokens WHERE study_id=? AND status='consumed'").get(studyId))throw new Error("Exploration is closed after confirmation visibility");return this.updateStudy(study,"exploring");}

  freezeCandidate(studyId:string,input:Omit<CandidateFreeze,"id"|"studyId"|"nodeSignature"|"status"|"createdAt"|"approvedAt"|"approvedBy">):CandidateFreeze{const study=this.getStudy(studyId);if(study.status!=="exploring")throw new Error("Candidate freeze requires exploration state");const run=this.db.prepare("SELECT status FROM search_runs WHERE id=?").get(input.searchRunId) as{status:string}|undefined;if(!run||!["completed","stopped"].includes(run.status))throw new Error("Search run is not complete");const row=this.db.prepare("SELECT payload_json FROM experiment_nodes WHERE id=? AND search_run_id=?").get(input.nodeId,input.searchRunId) as PayloadRow|undefined;if(!row)throw new Error("Candidate node does not belong to search run");const node=JSON.parse(row.payload_json) as{status:string;signature:string;artifactHash?:string|null};if(node.status!=="succeeded")throw new Error("Only a successful candidate can freeze");const freeze=CandidateFreezeSchema.parse({...input,id:`candidate-freeze-${randomUUID()}`,studyId,nodeSignature:node.signature,status:"frozen",createdAt:new Date().toISOString(),approvedAt:null,approvedBy:null});const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO candidate_freezes(id,study_id,search_run_id,node_id,status,payload_json,created_at) VALUES(?,?,?,?,?,?,?)").run(freeze.id,studyId,freeze.searchRunId,freeze.nodeId,freeze.status,JSON.stringify(freeze),freeze.createdAt);this.updateStudy(study,"candidate_frozen");});tx();return freeze;}
  approveCandidate(studyId:string,actor="researcher"):CandidateFreeze{const study=this.getStudy(studyId);if(study.status!=="candidate_frozen")throw new Error("Study is not awaiting candidate approval");const row=this.db.prepare("SELECT payload_json FROM candidate_freezes WHERE study_id=?").get(studyId) as PayloadRow;const freeze=CandidateFreezeSchema.parse(JSON.parse(row.payload_json));const approved=CandidateFreezeSchema.parse({...freeze,status:"approved",approvedAt:new Date().toISOString(),approvedBy:actor});const tx=this.db.transaction(()=>{this.db.prepare("UPDATE candidate_freezes SET status=?,payload_json=? WHERE id=?").run(approved.status,JSON.stringify(approved),approved.id);this.updateStudy(study,"confirmation_ready");});tx();return approved;}

  issueConfirmationToken(studyId:string):{token:string;record:ConfirmationToken}{const study=this.getStudy(studyId);if(study.status!=="confirmation_ready")throw new Error("Confirmation token requires approved frozen candidate");if(this.db.prepare("SELECT 1 ok FROM confirmation_tokens WHERE study_id=?").get(studyId))throw new Error("Confirmation token already exists");const freezeRow=this.db.prepare("SELECT id FROM candidate_freezes WHERE study_id=? AND status='approved'").get(studyId) as{id:string}|undefined;if(!freezeRow)throw new Error("Approved candidate freeze is required");const token=randomBytes(32).toString("hex");const record=ConfirmationTokenSchema.parse({id:`confirmation-token-${randomUUID()}`,studyId,candidateFreezeId:freezeRow.id,tokenHash:createHash("sha256").update(token).digest("hex"),status:"issued",issuedAt:new Date().toISOString(),consumedAt:null,runId:null});this.db.prepare("INSERT INTO confirmation_tokens(id,study_id,candidate_freeze_id,token_hash,status,payload_json,issued_at,consumed_at) VALUES(?,?,?,?,?,?,?,?)").run(record.id,studyId,record.candidateFreezeId,record.tokenHash,record.status,JSON.stringify(record),record.issuedAt,null);return{token,record};}
  consumeConfirmationToken(studyId:string,token:string,runId:string):{record:ConfirmationToken;confirmation:DataRoleManifest;visibility:VisibilityEvent}{const study=this.getStudy(studyId);if(study.status!=="confirmation_ready")throw new Error("Study is not ready for confirmation");const row=this.db.prepare("SELECT payload_json FROM confirmation_tokens WHERE study_id=?").get(studyId) as PayloadRow|undefined;if(!row)throw new Error("Confirmation token was not issued");const current=ConfirmationTokenSchema.parse(JSON.parse(row.payload_json));if(current.status!=="issued")throw new Error("Confirmation token is already consumed");if(createHash("sha256").update(token).digest("hex")!==current.tokenHash)throw new Error("Invalid confirmation token");const confirmation=this.allDataRoles(studyId).find(role=>role.role==="confirmation")!;const now=new Date().toISOString();const consumed=ConfirmationTokenSchema.parse({...current,status:"consumed",consumedAt:now,runId});const visibility=VisibilityEventSchema.parse({id:`visibility-${randomUUID()}`,programId:study.programId,runId,dataRole:"confirmation",artifactHash:confirmation.manifestHash,observedAt:now});const tx=this.db.transaction(()=>{this.db.prepare("UPDATE confirmation_tokens SET status=?,payload_json=?,consumed_at=? WHERE id=?").run(consumed.status,JSON.stringify(consumed),consumed.consumedAt,consumed.id);this.db.prepare("INSERT INTO research_visibility_events(id,program_id,run_id,data_role,artifact_hash,payload_json,observed_at) VALUES(?,?,?,?,?,?,?)").run(visibility.id,visibility.programId,visibility.runId,visibility.dataRole,visibility.artifactHash,JSON.stringify(visibility),visibility.observedAt);this.db.prepare("UPDATE research_programs SET status='confirmation_observed',payload_json=json_set(payload_json,'$.status','confirmation_observed','$.updatedAt',?),updated_at=? WHERE id=?").run(now,now,study.programId);this.updateStudy(study,"confirmation_consumed");});tx();return{record:consumed,confirmation,visibility};}

  addObservation(studyId:string,input:Omit<Observation,"id"|"studyId"|"createdAt">|Omit<UnitObservation,"id"|"studyId"|"createdAt">):ObservationRecord{const study=this.getStudy(studyId);if(input.phase==="confirmation"&&study.status!=="confirmation_consumed")throw new Error("Confirmation observation requires a consumed token");if(input.phase==="exploration"&&!['exploring','candidate_frozen'].includes(study.status))throw new Error("Exploration observation is outside exploration state");const common={...input,id:`observation-${randomUUID()}`,studyId,createdAt:new Date().toISOString()};if("unitId" in input){if(!this.units(studyId).some(unit=>unit.id===input.unitId))throw new Error(`Observation references undeclared experimental unit ${input.unitId}`);const observation=UnitObservationSchema.parse(common);this.db.prepare("INSERT INTO unit_observations(id,study_id,phase,variant,unit_id,group_name,outcome_id,value,missing_reason,run_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(observation.id,studyId,observation.phase,observation.variant,observation.unitId,observation.group,observation.outcomeId,observation.value,observation.missingReason,observation.runId,JSON.stringify(observation),observation.createdAt);return observation;}const observation=ObservationSchema.parse(common);this.db.prepare("INSERT INTO observations(id,study_id,phase,variant,seed,group_name,outcome_id,value,missing_reason,run_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(observation.id,studyId,observation.phase,observation.variant,observation.seed,observation.group,observation.outcomeId,observation.value,observation.missingReason,observation.runId,JSON.stringify(observation),observation.createdAt);return observation;}
  observations(studyId:string,phase?:Observation["phase"]):ObservationRecord[]{const legacy=(phase?this.db.prepare("SELECT payload_json FROM observations WHERE study_id=? AND phase=? ORDER BY created_at").all(studyId,phase):this.db.prepare("SELECT payload_json FROM observations WHERE study_id=? ORDER BY created_at").all(studyId)) as PayloadRow[],generic=(phase?this.db.prepare("SELECT payload_json FROM unit_observations WHERE study_id=? AND phase=? ORDER BY created_at").all(studyId,phase):this.db.prepare("SELECT payload_json FROM unit_observations WHERE study_id=? ORDER BY created_at").all(studyId)) as PayloadRow[];return[...legacy.map(row=>ObservationSchema.parse(JSON.parse(row.payload_json))),...generic.map(row=>UnitObservationSchema.parse(JSON.parse(row.payload_json)))];}

  recordAnalysis(studyId:string,input:{run:AnalysisRun;estimates:StatisticalEstimate[];diagnostics:DiagnosticResult[];multiplicity:MultiplicityRecord[];sensitivity:SensitivityAnalysis[]}):void{const study=this.getStudy(studyId);if(study.status!=="confirmation_consumed")throw new Error("Analysis requires consumed confirmation data");const tx=this.db.transaction(()=>{this.db.prepare("INSERT INTO analysis_runs(id,study_id,analysis_plan_id,status,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(input.run.id,studyId,input.run.analysisPlanId,input.run.status,JSON.stringify(input.run),input.run.createdAt);for(const item of input.estimates)this.db.prepare("INSERT INTO statistical_estimates(id,analysis_run_id,payload_json,created_at) VALUES(?,?,?,?)").run(item.id,item.analysisRunId,JSON.stringify(item),item.createdAt);for(const item of input.diagnostics)this.db.prepare("INSERT INTO diagnostic_results(id,analysis_run_id,status,payload_json,created_at) VALUES(?,?,?,?,?)").run(item.id,item.analysisRunId,item.status,JSON.stringify(item),item.createdAt);for(const item of input.multiplicity)this.db.prepare("INSERT INTO multiplicity_records(id,analysis_run_id,payload_json,created_at) VALUES(?,?,?,?)").run(item.id,item.analysisRunId,JSON.stringify(item),item.createdAt);for(const item of input.sensitivity)this.db.prepare("INSERT INTO sensitivity_analyses(id,analysis_run_id,payload_json,created_at) VALUES(?,?,?,?)").run(item.id,item.analysisRunId,JSON.stringify(item),item.createdAt);this.updateStudy(study,"analyzed");});tx();}
  recordSandboxRun(input:Omit<SandboxRun,"id"|"createdAt"|"finishedAt"|"purpose">&{purpose?:SandboxRun["purpose"]}):SandboxRun{const now=new Date().toISOString();const run=SandboxRunSchema.parse({...input,id:`sandbox-run-${randomUUID()}`,purpose:input.purpose??"general",createdAt:now,finishedAt:now});this.db.prepare("INSERT INTO sandbox_runs(id,study_id,backend,status,payload_json,created_at,finished_at) VALUES(?,?,?,?,?,?,?)").run(run.id,run.studyId,run.backend,run.status,JSON.stringify(run),run.createdAt,run.finishedAt);return run;}
  recordResourceUsage(input:Omit<ResourceUsage,"id"|"createdAt">):ResourceUsage{this.getStudy(input.studyId);const usage=ResourceUsageSchema.parse({...input,id:`resource-${randomUUID()}`,createdAt:new Date().toISOString()});this.db.prepare("INSERT INTO resource_usage(id,study_id,run_id,kind,payload_json,created_at) VALUES(?,?,?,?,?,?)").run(usage.id,usage.studyId,usage.runId,usage.kind,JSON.stringify(usage),usage.createdAt);return usage;}
  resourceUsage(studyId:string):ResourceUsage[]{return(this.db.prepare("SELECT payload_json FROM resource_usage WHERE study_id=? ORDER BY created_at").all(studyId) as PayloadRow[]).map(row=>ResourceUsageSchema.parse(JSON.parse(row.payload_json)));}
}
